## Modules

Note: modules `pympi-ling` and `pandas` are required for the work of `cortex`!

In [1]:
import re, os
import cortex as cx
from collections import Counter

## Loading the data

### Loading the corpus

Load all files within the folder `corpus new`, attach metadata from the csv-file `sgh_corpus_metadata.csv` (it might take a few seconds!):

In [2]:
corpus = cx.Corpus(folderpath="corpus new", metadata_path="sgh_corpus_metadata.csv")

100%|██████████| 108/108 [00:52<00:00,  2.05it/s]

In [3]:
corpus

[Text("Idioms (Alamshoev 1994)"),
 Text("Imam"),
 Text("Rivoyati рīri bomāfili yāxsūz"),
 Text("Poyi Xoǰā"),
 Text("Sokhcharv"),
 Text("Sumbi Duldul"),
 Text("The Anjin dragon"),
 Text("The king of Khwarazm"),
 Text("Two people in green"),
 Text("Song lyrics (Alamshoev 1994)"),
 Text("Proverbs (Alamshoev 1994)"),
 Text("Riddles (Alamshoev 1994)"),
 Text("Sentences (Alamshoev 1994)"),
 Text("Azizkhon №1"),
 Text("Azizkhon №2"),
 Text("First resettlement"),
 Text("Gulasanjon"),
 Text("Hero Odilsho"),
 Text("Karamāli"),
 Text("Khan’s hunt"),
 Text("Luknitskiy"),
 Text("Mangits, Bukhara khans"),
 Text("Second resettlement"),
 Text("Story"),
 Text("The Dirum lake"),
 Text("The quarrel of Sayīd Māmūdšo and Sayīd Yusfališo"),
 Text("Voydak"),
 Text("A black-skinned servant"),
 Text("A king, his sons and his wife"),
 Text("Buor and Nuqra"),
 Text("Owl, gyrfalcon, nightingale and hawk"),
 Text("The king’s son and the vizier’s son"),
 Text("The king of the east and the west"),
 Text("White camel"),
 Text("Who to eat, who to eat, we will eat our little sister"),
 Text("A boy and his grandmother’s corpse"),
 Text("Game of makak"),
 Text("Hairy dev"),
 Text("Snuffbox with a female voice"),
 Text("The Jawshangoz fortress"),
 Text("Wedding"),
 Text("Codebreaker (NG06 & SK06) №1"),
 Text("Codebreaker (NG06 & SK06) №2"),
 Text("Alexander the Golden-horned"),
 Text("A man’s namaz"),
 Text("Giving away eyes"),
 Text("How birds took colors"),
 Text("Man and wolf"),
 Text("Nasir Khusraw, snake and eagle"),
 Text("Nosiri Khusraw and his guide"),
 Text("The shrine Sumbi Duldul"),
 Text("A young bear thief"),
 Text("White mountain goat"),
 Text("Interview with Lidush Habib (Part 1)"),
 Text("Gospel of Luke, Chapter 10: 25–37"),
 Text("Gospel of Luke, Chapter 11: 1–10"),
 Text("Gospel of Luke, Chapter 14: 15–24"),
 Text("Gospel of Luke, Chapter 15: 11–32"),
 Text("Gospel of Luke, Chapter 18: 35–43"),
 Text("Gospel of Luke, Chapter 2: 1–52"),
 Text("Gospel of Luke, Chapter 23: 26–49"),
 Text("Gospel of Luke, Chapter 24: 1–12, 36–49"),
 Text("Gospel of Luke, Chapter 5: 1–11"),
 Text("Gospel of Luke, Chapter 7: 1–17"),
 Text("Gospel of Luke, Chapter 8: 22–25"),
 Text("Gospel of Luke, Chapter 9: 10–17"),
 Text("Pear Film (AN04)"),
 Text("Pear Film (AN99)"),
 Text("Pear Film (MA91)"),
 Text("Pear Film (N02)"),
 Text("Pear Film (NR75)"),
 Text("Pear Film (OO04)"),
 Text("Pear Film (RES99)"),
 Text("Simple verbs from abêx̌tow to andīdow (Karamshoev 1988)"),
 Text("About Dodkhudo Karamshoev"),
 Text("Tale (AMG)"),
 Text("Peri (AND)"),
 Text("Before UCA"),
 Text("Corn"),
 Text("Biography (DG38)"),
 Text("Biography (DMO) №2"),
 Text("Biography (DMO) №3"),
 Text("Mom"),
 Text("Nawruz"),
 Text("Interview experiment (SN72 & NR75)"),
 Text("Childhood snow story"),
 Text("Road to Kharagh"),
 Text("Prophets"),
 Text("Peri (OQD)"),
 Text("Donkey"),
 Text("Life before Soviets"),
 Text("Shodi and me"),
 Text("Milk"),
 Text("Mystic fire"),
 Text("Old parties"),
 Text("Snow leopard"),
 Text("Stealing"),
 Text("Language"),
 Text("World Religion"),
 Text("Mystic vision"),
 Text("Peri (SDA)"),
 Text("Peri in a summer camp (SDA)"),
 Text("Life story (SIKh & ShSN, Part 2)"),
 Text("Life story (SIKh & ShSN, Part 5)"),
 Text("Three brothers (Audio)"),
 Text("Yusufbekov’s grandfather"),
 Text("Bio (ZSh)"),
 Text("A man and a snake")]

### Loading a single file

Load a single file:

In [4]:
text = cx.Text(filename="sgh_txt_Three_brothers.eaf", folderpath="corpus new", metadata_path="sgh_corpus_metadata.csv")

In [5]:
text

Text("Three brothers (Audio)")

## Objects: basics

A corpus is of class `cx.Corpus`. It contains a collection of texts, which are of class `cx.Text`:

In [6]:
print(type(corpus))
print(corpus)

<class 'cortex.Corpus'>
[Text("Idioms (Alamshoev 1994)"),
 Text("Imam"),
 Text("Rivoyati рīri bomāfili yāxsūz"),
 Text("Poyi Xoǰā"),
 Text("Sokhcharv"),
 Text("Sumbi Duldul"),
 Text("The Anjin dragon"),
 Text("The king of Khwarazm"),
 Text("Two people in green"),
 Text("Song lyrics (Alamshoev 1994)"),
 Text("Proverbs (Alamshoev 1994)"),
 Text("Riddles (Alamshoev 1994)"),
 Text("Sentences (Alamshoev 1994)"),
 Text("Azizkhon №1"),
 Text("Azizkhon №2"),
 Text("First resettlement"),
 Text("Gulasanjon"),
 Text("Hero Odilsho"),
 Text("Karamāli"),
 Text("Khan’s hunt"),
 Text("Luknitskiy"),
 Text("Mangits, Bukhara khans"),
 Text("Second resettlement"),
 Text("Story"),
 Text("The Dirum lake"),
 Text("The quarrel of Sayīd Māmūdšo and Sayīd Yusfališo"),
 Text("Voydak"),
 Text("A black-skinned servant"),
 Text("A king, his sons and his wife"),
 Text("Buor and Nuqra"),
 Text("Owl, gyrfalcon, nightingale and hawk"),
 Text("The king’s son and the vizier’s son"),
 Text("The king of the east and the west"),
 Text("White camel"),
 Text("Who to eat, who to eat, we will eat our little sister"),
 Text("A boy and his grandmother’s corpse"),
 Text("Game of makak"),
 Text("Hairy dev"),
 Text("Snuffbox with a female voice"),
 Text("The Jawshangoz fortress"),
 Text("Wedding"),
 Text("Codebreaker (NG06 & SK06) №1"),
 Text("Codebreaker (NG06 & SK06) №2"),
 Text("Alexander the Golden-horned"),
 Text("A man’s namaz"),
 Text("Giving away eyes"),
 Text("How birds took colors"),
 Text("Man and wolf"),
 Text("Nasir Khusraw, snake and eagle"),
 Text("Nosiri Khusraw and his guide"),
 Text("The shrine Sumbi Duldul"),
 Text("A young bear thief"),
 Text("White mountain goat"),
 Text("Interview with Lidush Habib (Part 1)"),
 Text("Gospel of Luke, Chapter 10: 25–37"),
 Text("Gospel of Luke, Chapter 11: 1–10"),
 Text("Gospel of Luke, Chapter 14: 15–24"),
 Text("Gospel of Luke, Chapter 15: 11–32"),
 Text("Gospel of Luke, Chapter 18: 35–43"),
 Text("Gospel of Luke, Chapter 2: 1–52"),
 Text("Gospel of Luke, Chapter 23: 26–49"),
 Text("Gospel of Luke, Chapter 24: 1–12, 36–49"),
 Text("Gospel of Luke, Chapter 5: 1–11"),
 Text("Gospel of Luke, Chapter 7: 1–17"),
 Text("Gospel of Luke, Chapter 8: 22–25"),
 Text("Gospel of Luke, Chapter 9: 10–17"),
 Text("Pear Film (AN04)"),
 Text("Pear Film (AN99)"),
 Text("Pear Film (MA91)"),
 Text("Pear Film (N02)"),
 Text("Pear Film (NR75)"),
 Text("Pear Film (OO04)"),
 Text("Pear Film (RES99)"),
 Text("Simple verbs from abêx̌tow to andīdow (Karamshoev 1988)"),
 Text("About Dodkhudo Karamshoev"),
 Text("Tale (AMG)"),
 Text("Peri (AND)"),
 Text("Before UCA"),
 Text("Corn"),
 Text("Biography (DG38)"),
 Text("Biography (DMO) №2"),
 Text("Biography (DMO) №3"),
 Text("Mom"),
 Text("Nawruz"),
 Text("Interview experiment (SN72 & NR75)"),
 Text("Childhood snow story"),
 Text("Road to Kharagh"),
 Text("Prophets"),
 Text("Peri (OQD)"),
 Text("Donkey"),
 Text("Life before Soviets"),
 Text("Shodi and me"),
 Text("Milk"),
 Text("Mystic fire"),
 Text("Old parties"),
 Text("Snow leopard"),
 Text("Stealing"),
 Text("Language"),
 Text("World Religion"),
 Text("Mystic vision"),
 Text("Peri (SDA)"),
 Text("Peri in a summer camp (SDA)"),
 Text("Life story (SIKh & ShSN, Part 2)"),
 Text("Life story (SIKh & ShSN, Part 5)"),
 Text("Three brothers (Audio)"),
 Text("Yusufbekov’s grandfather"),
 Text("Bio (ZSh)"),
 Text("A man and a snake")]

In [7]:
text = corpus[84]   # alternatively: text = corpus.texts[84]
print(type(text))
print(text)

<class 'cortex.Text'>
Text("Interview experiment (SN72 & NR75)")

A `cx.Text` contains a list of sentences, which are of class `cx.Sentence`:

In [8]:
sentence = text[17]   # alternatively: sentence = text.sentences[17]
print(type(sentence))
print(sentence)

<class 'cortex.Sentence'>
Sentence("Tu=t as dev sozindāyen=and sar lap či žīwǰ?")

Each `cx.Sentence` is made up of tokens (`cx.Token`). Each `cx.Token` may have zero or more analyses (`cx.Analysis`). Finally, analyses consist of morphemes (`cx.Morpheme`).

In [9]:
token = sentence[3]   # alternatively: token = sentence.tokens[3]
print(type(token))
print(token)

<class 'cortex.Token'>
Token("sozindāyen=and")

In [10]:
analysis = token[0]   # alternatively: analysis = token.ana[0]
print(type(analysis))
print(analysis)

<class 'cortex.Analysis'>
Analysis("musician{sozindā}{N}-PL{-yen}{N.AFF}-LOC{=and}{POST}")

In [11]:
morpheme = analysis[2]   # alternatively: morpheme = analysis.morphemes[3]
print(type(morpheme))
print(morpheme)

<class 'cortex.Morpheme'>
Morpheme("LOC{=and}{POST}")

All the “inner” items of an object (e.g. all tokens in a sentence) are stored in a `list` (except for `cx.Morpheme`). Therefore, it is possible to:
- iterate over an object with a loop
- get to a specific item using an index (alternatively, use the method `.get_id()`)
- get the number of items with `len()`

In [12]:
print("Iterate over tokens of a sentence:")
for t in sentence:
    print(t.id, t)

Iterate over tokens of a sentence:
1 Token("Tu=t")
2 Token("as")
3 Token("dev")
4 Token("sozindāyen=and")
5 Token("sar")
6 Token("lap")
7 Token("či")
8 Token("žīwǰ?")

In [13]:
print("Get an item using the object’s id:")
print(sentence[3])
print(sentence.get_id(4))   # Note that ids start at 1, not 0!

Get an item using the object’s id:
Token("sozindāyen=and")
Token("sozindāyen=and")

In [14]:
print("Get the number of items:")
print(len(sentence))

Get the number of items:
8

If a text or a corpus is correctly imported, “inner” items will contain information about what “outer” objects they belong to:

In [15]:
print(morpheme)
print("->", morpheme.back_ana)
print("->", morpheme.back_token)
print("->", morpheme.back_sent)
print("->", morpheme.back_text)

Morpheme("LOC{=and}{POST}")
-> Analysis("musician{sozindā}{N}-PL{-yen}{N.AFF}-LOC{=and}{POST}")
-> Token("sozindāyen=and")
-> Sentence("Tu=t as dev sozindāyen=and sar lap či žīwǰ?")
-> Text("Interview experiment (SN72 & NR75)")

## Object attributes

All objects have their own attributes. For instance, if you have a `cx.Morpheme`, you can easily extract its morph (phonological form), its gloss and its POS tag. The object also contains information on how it is written in the glossing in the form of “prefix” and “suffix” (i.e. punctuation that precedes and follows the morpheme itself).

In [16]:
print(morpheme)

print("morph:", morpheme.morph)
print("gloss:", morpheme.gloss)
print("_prefix:", morpheme._prefix)
print("_suffix:", morpheme._suffix)
print("morph_full:", morpheme.morph_full)
print("gloss_full:", morpheme.gloss_full)
print("pos:", morpheme.pos)

Morpheme("LOC{=and}{POST}")
morph: and
gloss: LOC
_prefix: =
_suffix:
morph_full: =and
gloss_full: =LOC
pos: POST

An `cx.Analysis` can use these attributes of each morpheme to give a glossing-like representation of the morphological structure:

In [17]:
print(analysis)
print("morph_string:", analysis.morph_string)
print("gloss_string:", analysis.gloss_string)
print("view():", analysis.view())

Analysis("musician{sozindā}{N}-PL{-yen}{N.AFF}-LOC{=and}{POST}")
morph_string: sozindā-yen=and
gloss_string: musician-PL=LOC
view(): musician{sozindā}{N}-PL{-yen}{N.AFF}-LOC{=and}{POST}

Similarly, `cx.Token`, `cx.Sentence`, `cx.Text` and `cx.Corpus` also have useful attributes (these are just a few examples):

In [18]:
print(token)
print("token:", token.token)
print("wtype:", token.wtype)

Token("sozindāyen=and")
token: sozindāyen=and
wtype: word

In [19]:
print(sentence)
print("text:", sentence.text)
print("translation:", sentence.translation)
print("comment:", sentence.comment)
print("meta:", sentence.meta)
print("timestamps:", sentence.timestamps)

Sentence("Tu=t as dev sozindāyen=and sar lap či žīwǰ?")
text: Tu=t as dev sozindāyen=and sar lap či žīwǰ?
translation: {'ru': 'Кого из музыкантов ты любишь больше всего?'}
comment: None
meta: {'speaker': 'A'}
timestamps: (104769, 108772)

In [20]:
print(text)
print("title:", text.title)
print("filename:", text.filename)
print("filetype:", text.filetype)
print("meta:", text.meta)
print("audio:", text.audio)

Text("Interview experiment (SN72 & NR75)")
title: Interview experiment (SN72 & NR75)
filename: sgh_txt_interview_SN72_NR75.eaf
filetype: eaf
meta: {'glossing': 'yes', 'translation': 'yes', 'media type': 'audio', 'type': 'oral conversation', 'genre': 'planned interview', 'subcorpus': 'Dialogues (interview experiment)', 'duration': '0:04:39', 'year': 2024, 'dialect': 'Хорог, Хорог', 'author': 'SN72, NR75', 'gender': 'F, F', 'birth year': '1972, 1975', 'source': 'recorded in the 2024 field trip', 'recorded by': 'Sofia Sedunova', 'translated by': 'MT05', 'glossed by': 'Timofey Lugovskoy', 'speakers': ['A', 'B']}
audio: {'filename': './sgh_txt_interview_SN72_NR75.wav', 'MEDIA_URL': 'file:///D:/Учёба/Шугнанский/Шугнанский текст разбор/in progress/sgh_txt_interview_SN72_NR75.wav'}

## Search

### Search morpheme

To search for a morpheme with certain properties, use the method `.search_morpheme()`. This method can be called from a `cx.Corpus`, a `cx.Text`, a `cx.Sentence` or a `cx.Token`.

Provide either of these conditions as arguments: `morph` (phonological form), `gloss` (gloss or lemma), `pos` (POS tag). If several conditions are provided, all apply simultaneously. All three arguments may contain regular expressions, and `gloss` is case-sensitive.

In [21]:
results = corpus.search_morpheme(morph="atā")
results

[Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("TIME2{atā}{POST}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("TIME2{=atā}{POST}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("TIME2{=atā}{POST}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("TIME2{=atā}{POST}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("TIME2{=atā}{POST}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("TIME2{=atā}{POST}"),
 Morpheme("TIME2{=atā}{POST}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("TIME2{=atā}{POST}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("TIME2{=atā}{POST}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{Atā}{CONJ}"),
 Morpheme("COORD3{Atā}{CONJ}"),
 Morpheme("COORD3{Atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{Atā}{CONJ}"),
 Morpheme("COORD3{Atā}{CONJ}"),
 Morpheme("COORD3{Atā}{CONJ}"),
 Morpheme("COORD3{Atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{Atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{Atā}{CONJ}"),
 Morpheme("COORD3{Atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{Atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{Atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{Atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{Atā}{CONJ}"),
 Morpheme("COORD3{Atā}{CONJ}"),
 Morpheme("COORD3{Atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{Atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{Atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{Atā}{CONJ}"),
 Morpheme("COORD3{Atā}{CONJ}"),
 Morpheme("COORD3{Atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{Atā}{CONJ}"),
 Morpheme("COORD3{Atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{Atā}{CONJ}"),
 Morpheme("COORD3{Atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{Atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{Atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{Atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{Atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{Atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{Atā}{CONJ}"),
 Morpheme("COORD3{Atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{Atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{Atā}{CONJ}"),
 Morpheme("COORD3{Atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{Atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{Atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{Atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("TIME2{=atā}{POST}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("TIME2{=atā}{POST}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("TIME2{=atā}{POST}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("TIME2{=atā}{POST}"),
 Morpheme("TIME2{=atā}{POST}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("TIME2{=atā}{POST}"),
 Morpheme("TIME2{=atā}{POST}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("TIME2{=atā}{POST}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("TIME2{=atā}{POST}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{=atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}"),
 Morpheme("COORD3{atā}{CONJ}")]

In [22]:
results = corpus.search_morpheme(gloss="father")
results

[Morpheme("father{padar}"),
 Morpheme("father{tāt}{N}"),
 Morpheme("father{dod}{N}"),
 Morpheme("father{tāt}{N}"),
 Morpheme("father{padar}"),
 Morpheme("father{dod}{N}"),
 Morpheme("father{tāt}{N}"),
 Morpheme("father{tāt}{N}"),
 Morpheme("father{tā}"),
 Morpheme("father{pid}"),
 Morpheme("father{tāt}{N}"),
 Morpheme("father{tāt}{N}"),
 Morpheme("father{tāt}{N}"),
 Morpheme("father{dod}{N}"),
 Morpheme("father{dod}{N}"),
 Morpheme("father{tāt}{N}"),
 Morpheme("father{dod}{N}"),
 Morpheme("father{padar}"),
 Morpheme("father{tāt}{N}"),
 Morpheme("father{tāt}{N}"),
 Morpheme("father{tāt}{N}"),
 Morpheme("father{tāt}{N}"),
 Morpheme("father{tāt}{N}"),
 Morpheme("father{tāt}{N}"),
 Morpheme("father{tāt}{N}"),
 Morpheme("father{tāt}{N}"),
 Morpheme("father{tāt}{N}"),
 Morpheme("father{pid}"),
 Morpheme("father{tāt}{N}"),
 Morpheme("father{tāt}{N}"),
 Morpheme("father{tāt}{N}"),
 Morpheme("father{tāt}{N}"),
 Morpheme("father{tāt}{N}"),
 Morpheme("father{tāt}{N}"),
 Morpheme("father{tāt}{N}"),
 Morpheme("father{dod}{N}"),
 Morpheme("father{pid}"),
 Morpheme("father{tāt}{N}"),
 Morpheme("father{tāt}{N}"),
 Morpheme("father{tāt}{N}"),
 Morpheme("father{tāt}{N}"),
 Morpheme("father{tāt}{N}"),
 Morpheme("father{tāt}{N}"),
 Morpheme("father{tāt}{N}"),
 Morpheme("father{tāt}{N}"),
 Morpheme("father{tāt}{N}"),
 Morpheme("father{tāt}{N}"),
 Morpheme("father{tāt}{N}"),
 Morpheme("father{tāt}{N}"),
 Morpheme("father{tāt}{N}"),
 Morpheme("father{dod}{N}"),
 Morpheme("father{dod}{N}"),
 Morpheme("father{dod}{N}"),
 Morpheme("father{dod}{N}"),
 Morpheme("father{dod}{N}"),
 Morpheme("father{dod}{N}"),
 Morpheme("father{dod}{N}"),
 Morpheme("father{dod}{N}"),
 Morpheme("father{dod}{N}"),
 Morpheme("father{dod}{N}"),
 Morpheme("father{dod}{N}"),
 Morpheme("father{tāt}{N}"),
 Morpheme("father{padar}{N}"),
 Morpheme("father{dod}{N}"),
 Morpheme("father{dod}{N}"),
 Morpheme("father{dod}{N}"),
 Morpheme("father{dod}{N}"),
 Morpheme("father{dod}{N}"),
 Morpheme("father{dod}{N}"),
 Morpheme("father{dod}{N}"),
 Morpheme("father{dod}{N}"),
 Morpheme("father{dod}{N}"),
 Morpheme("father{dod}{N}"),
 Morpheme("father{dod}{N}"),
 Morpheme("father{dod}{N}"),
 Morpheme("father{dod}{N}"),
 Morpheme("father{dod}{N}"),
 Morpheme("father{dod}{N}"),
 Morpheme("father{dod}{N}"),
 Morpheme("father{dod}{N}"),
 Morpheme("father{dod}{N}"),
 Morpheme("father{dod}{N}"),
 Morpheme("father{dod}{N}"),
 Morpheme("father{padar}{N}"),
 Morpheme("father{dod}{N}"),
 Morpheme("father{dod}{N}"),
 Morpheme("father{pid}"),
 Morpheme("father{dod}{N}"),
 Morpheme("father{dod}{N}"),
 Morpheme("father{dod}{N}"),
 Morpheme("father{dod}{N}"),
 Morpheme("father{dod}{N}"),
 Morpheme("father{dod}{N}"),
 Morpheme("father{tat}{N}"),
 Morpheme("father{tāt}{N}"),
 Morpheme("father{tāt}{N}"),
 Morpheme("father{tāt}{N}"),
 Morpheme("father{tāt}{N}"),
 Morpheme("father{tāt}{N}"),
 Morpheme("father{tāt}{N}"),
 Morpheme("father{tāt}{N}"),
 Morpheme("father{tāt}{N}"),
 Morpheme("father{tāt}{N}"),
 Morpheme("father{tāt}{N}"),
 Morpheme("father{tāt}{N}"),
 Morpheme("father{tāt}{N}"),
 Morpheme("father{tāt}{N}"),
 Morpheme("father{tāt}{N}"),
 Morpheme("father{padār}{N}"),
 Morpheme("father{dod}{N}"),
 Morpheme("father{tāt}{N}"),
 Morpheme("father{tāt}{N}"),
 Morpheme("father{tāt}{N}"),
 Morpheme("father{tāt}{N}"),
 Morpheme("father{tāt}{N}"),
 Morpheme("father{tāt}{N}"),
 Morpheme("father{tāt}{N}"),
 Morpheme("father{tāt}{N}"),
 Morpheme("father{tāt}{N}"),
 Morpheme("father{tāt}{N}"),
 Morpheme("father{tāt}{N}"),
 Morpheme("father{tāt}{N}"),
 Morpheme("father{tāt}{N}"),
 Morpheme("father{tāt}{N}"),
 Morpheme("father{tāt}{N}"),
 Morpheme("father{tāt}{N}"),
 Morpheme("father{tāt}{N}"),
 Morpheme("father{tāt}{N}"),
 Morpheme("father{tāt}{N}"),
 Morpheme("father{tāt}{N}"),
 Morpheme("father{tāt}{N}"),
 Morpheme("father{tāt}{N}"),
 Morpheme("father{tāt}{N}"),
 Morpheme("father{tāt}{N}")]

In [23]:
results = corpus.search_morpheme(morph="atā", gloss="TIME2")
results

[Morpheme("TIME2{atā}{POST}"),
 Morpheme("TIME2{=atā}{POST}"),
 Morpheme("TIME2{=atā}{POST}"),
 Morpheme("TIME2{=atā}{POST}"),
 Morpheme("TIME2{=atā}{POST}"),
 Morpheme("TIME2{=atā}{POST}"),
 Morpheme("TIME2{=atā}{POST}"),
 Morpheme("TIME2{=atā}{POST}"),
 Morpheme("TIME2{=atā}{POST}"),
 Morpheme("TIME2{=atā}{POST}"),
 Morpheme("TIME2{=atā}{POST}"),
 Morpheme("TIME2{=atā}{POST}"),
 Morpheme("TIME2{=atā}{POST}"),
 Morpheme("TIME2{=atā}{POST}"),
 Morpheme("TIME2{=atā}{POST}"),
 Morpheme("TIME2{=atā}{POST}"),
 Morpheme("TIME2{=atā}{POST}"),
 Morpheme("TIME2{=atā}{POST}")]

In [24]:
results = corpus.search_morpheme(gloss="CAUSE")
results

[Morpheme("CAUSE{ǰāt}{POST}"),
 Morpheme("CAUSE{ǰāt}{POST}"),
 Morpheme("CAUSE{ǰāt}{POST}"),
 Morpheme("CAUSE{ǰāt}{POST}"),
 Morpheme("CAUSE{ǰāt}{POST}"),
 Morpheme("CAUSE{ǰāt}{POST}"),
 Morpheme("CAUSE{ǰāt}{POST}"),
 Morpheme("CAUSE{=ǰāt}{POST}"),
 Morpheme("CAUSE{ǰāt}{POST}"),
 Morpheme("CAUSE{ǰāt}{POST}"),
 Morpheme("CAUSE{=ǰāt}{POST}"),
 Morpheme("CAUSE{=ǰāt}{POST}"),
 Morpheme("CAUSE{=ǰāt}{POST}"),
 Morpheme("CAUSE{=ǰāt}{POST}"),
 Morpheme("CAUSE{=ǰāt}{POST}"),
 Morpheme("CAUSE{aven}{POST}"),
 Morpheme("CAUSE{=ǰāt}{POST}"),
 Morpheme("CAUSE{aven}{POST}"),
 Morpheme("CAUSE{ǰāt}{POST}"),
 Morpheme("CAUSE{ǰāt}{POST}"),
 Morpheme("CAUSE{ǰāt}{POST}"),
 Morpheme("CAUSE{ǰāt}{POST}"),
 Morpheme("CAUSE{ǰāt}{POST}"),
 Morpheme("CAUSE{=ǰāt}{POST}"),
 Morpheme("CAUSE{=ǰāt}{POST}"),
 Morpheme("CAUSE{ǰāt}{POST}"),
 Morpheme("CAUSE{=ǰāt}{POST}"),
 Morpheme("CAUSE{=ǰāt}{POST}"),
 Morpheme("CAUSE{=ǰāt}{POST}"),
 Morpheme("CAUSE{=ǰāt}{POST}"),
 Morpheme("CAUSE{=ǰāt}{POST}"),
 Morpheme("CAUSE{=ǰāt}{POST}"),
 Morpheme("CAUSE{=ǰāt}{POST}"),
 Morpheme("CAUSE{=ǰāt}{POST}"),
 Morpheme("CAUSE{=ǰāt}{POST}"),
 Morpheme("CAUSE{ǰāt}{POST}"),
 Morpheme("CAUSE{ǰāt}{POST}"),
 Morpheme("CAUSE{ǰat}{POST}"),
 Morpheme("CAUSE{=aven}{POST}"),
 Morpheme("CAUSE{=aven}{POST}"),
 Morpheme("CAUSE{ǰāt}{POST}"),
 Morpheme("CAUSE{aven}{POST}"),
 Morpheme("CAUSE{aven}{POST}"),
 Morpheme("CAUSE{aven}{POST}"),
 Morpheme("CAUSE{ǰāt}{POST}"),
 Morpheme("CAUSE{aven}{POST}"),
 Morpheme("CAUSE{ǰāt}{POST}"),
 Morpheme("CAUSE{ǰāt}{POST}"),
 Morpheme("CAUSE{ǰāt}{POST}"),
 Morpheme("CAUSE{=aven}{POST}"),
 Morpheme("CAUSE{ǰāt}{POST}"),
 Morpheme("CAUSE{aven}{POST}"),
 Morpheme("CAUSE{ǰāt}{POST}"),
 Morpheme("CAUSE{=ǰāt}{POST}"),
 Morpheme("CAUSE{=ǰāt}{POST}"),
 Morpheme("CAUSE{=ǰāt}{POST}"),
 Morpheme("CAUSE{=ǰāt}{POST}"),
 Morpheme("CAUSE{=ǰāt}{POST}"),
 Morpheme("CAUSE{=ǰat}{POST}"),
 Morpheme("CAUSE{=ǰāt}{POST}"),
 Morpheme("CAUSE{ǰat}{POST}"),
 Morpheme("CAUSE{=ǰāt}{POST}"),
 Morpheme("CAUSE{=ǰāt}{POST}"),
 Morpheme("CAUSE{=ǰāt}{POST}"),
 Morpheme("CAUSE{=ǰāt}{POST}"),
 Morpheme("CAUSE{=ǰāt}{POST}"),
 Morpheme("CAUSE{baroi}{TAJ}"),
 Morpheme("CAUSE{=ǰāt}{POST}"),
 Morpheme("CAUSE{=ǰāt}{POST}"),
 Morpheme("CAUSE{=ǰāt}{POST}"),
 Morpheme("CAUSE{=ǰāt}{POST}"),
 Morpheme("CAUSE{=ǰāt}{POST}"),
 Morpheme("CAUSE{=ǰāt}{POST}"),
 Morpheme("CAUSE{=ǰāt}{POST}"),
 Morpheme("CAUSE{=ǰāt}{POST}")]

Search results are stored not in a simple list, but in a special object `cx.MorphemeSearch`. This object can help you browse the results in different ways. For example, you can get the corresponding analyses or sentences to gain more context:

In [25]:
results.as_ana

[Analysis("CAUSE{ǰāt}{POST}"),
 Analysis("CAUSE{ǰāt}{POST}-3SG{=i}{CL.AGR}"),
 Analysis("CAUSE{ǰāt}{POST}"),
 Analysis("CAUSE{ǰāt}{POST}"),
 Analysis("CAUSE{ǰāt}{POST}"),
 Analysis("CAUSE{ǰāt}{POST}"),
 Analysis("CAUSE{ǰāt}{POST}"),
 Analysis("D2.M.SG.O{di}{DEM}-CAUSE{=ǰāt}{POST}"),
 Analysis("CAUSE{ǰāt}{POST}"),
 Analysis("CAUSE{ǰāt}{POST}"),
 Analysis("D2.M.SG.O{di}{DEM}-CAUSE{=ǰāt}{POST}-1SG{=um}{CL.AGR}"),
 Analysis("D2.M.SG.O{di}{DEM}-CAUSE{=ǰāt}{POST}"),
 Analysis("D2.M.SG.O{di}{DEM}-CAUSE{=ǰāt}{POST}"),
 Analysis("D2.M.SG.O{di}{DEM}-CAUSE{=ǰāt}{POST}"),
 Analysis("this_much{důnd}{PRO}-CAUSE{=ǰāt}{POST}"),
 Analysis("CAUSE{aven}{POST}-3SG{=i}{CL.AGR}"),
 Analysis("D2.M.SG.O{di}{DEM}-CAUSE{=ǰāt}{POST}"),
 Analysis("CAUSE{aven}{POST}"),
 Analysis("CAUSE{ǰāt}{POST}"),
 Analysis("CAUSE{ǰāt}{POST}-3PL{=en}{CL.AGR}"),
 Analysis("CAUSE{ǰāt}{POST}"),
 Analysis("CAUSE{ǰāt}{POST}"),
 Analysis("CAUSE{ǰāt}{POST}-1SG{=um}{CL.AGR}"),
 Analysis("house{čīd}{N}-CAUSE{=ǰāt}{POST}"),
 Analysis("war{δêd}-CAUSE{=ǰāt}{POST}"),
 Analysis("CAUSE{ǰāt}{POST}"),
 Analysis("D2.M.SG.O{di}{DEM}-CAUSE{=ǰāt}{POST}"),
 Analysis("D2.M.SG.O{di}{DEM}-CAUSE{=ǰāt}{POST}"),
 Analysis("this_much{důnd}{PRO}-CAUSE{=ǰāt}{POST}"),
 Analysis("D2.M.SG.O{di}{DEM}-CAUSE{=ǰāt}{POST}"),
 Analysis("this_much{důnd}{PRO}-CAUSE{=ǰāt}{POST}"),
 Analysis("this_much{důnd}{PRO}-CAUSE{=ǰāt}{POST}"),
 Analysis("this_much{důnd}{PRO}-CAUSE{=ǰāt}{POST}"),
 Analysis("EMPH{ik=}{PRT}-this_much{důnd}{PRO}-CAUSE{=ǰāt}{POST}-1SG{=um}{CL.AGR}"),
 Analysis("this_much{důnd}{PRO}-CAUSE{=ǰāt}{POST}"),
 Analysis("CAUSE{ǰāt}{POST}"),
 Analysis("CAUSE{ǰāt}{POST}-3SG{=i}{CL.AGR}"),
 Analysis("CAUSE{ǰat}{POST}-do{čūɣ̌}{V}-PF{-ǰ}{T}-PTCP1{-in}{NMLZ}"),
 Analysis("this_much{důnd}{PRO}-CAUSE{=aven}{POST}"),
 Analysis("this_much{důnd}{PRO}-CAUSE{=aven}{POST}"),
 Analysis("CAUSE{ǰāt}{POST}"),
 Analysis("CAUSE{aven}{POST}"),
 Analysis("CAUSE{aven}{POST}"),
 Analysis("CAUSE{aven}{POST}"),
 Analysis("CAUSE{ǰāt}{POST}"),
 Analysis("CAUSE{aven}{POST}"),
 Analysis("CAUSE{ǰāt}{POST}"),
 Analysis("CAUSE{ǰāt}{POST}"),
 Analysis("CAUSE{ǰāt}{POST}"),
 Analysis("this_much{důnd}{PRO}-CAUSE{=aven}{POST}"),
 Analysis("CAUSE{ǰāt}{POST}"),
 Analysis("CAUSE{aven}{POST}"),
 Analysis("CAUSE{ǰāt}{POST}"),
 Analysis("D2.M.SG.O{di}{DEM}-CAUSE{=ǰāt}{POST}"),
 Analysis("D2.M.SG.O{di}{DEM}-CAUSE{=ǰāt}{POST}"),
 Analysis("D2.M.SG.O{di}{DEM}-CAUSE{=ǰāt}{POST}"),
 Analysis("D2.M.SG.O{di}{DEM}-CAUSE{=ǰāt}{POST}-1PL{=ām}{CL.AGR}"),
 Analysis("EMPH{ik=}{PRT}-D2.M.SG.O{di}{DEM}-CAUSE{=ǰāt}{POST}"),
 Analysis("D2.M.SG.O{di}{DEM}-CAUSE{=ǰat}{POST}"),
 Analysis("thing{čīz}{PRO}-CAUSE{=ǰāt}{POST}"),
 Analysis("CAUSE{ǰat}{POST}"),
 Analysis("D2.M.SG.O{di}{DEM}-CAUSE{=ǰāt}{POST}-3PL{=en}{CL.AGR}"),
 Analysis("this_much{důnd}{PRO}-CAUSE{=ǰāt}{POST}-EZ{-i}{POST}"),
 Analysis("this_much{důnd}{PRO}-CAUSE{=ǰāt}{POST}"),
 Analysis("this_much{důnd}{PRO}-CAUSE{=ǰāt}{POST}-EZ{-i}{POST}"),
 Analysis("D2.M.SG.O{di}{DEM}-CAUSE{=ǰāt}{POST}"),
 Analysis("CAUSE{baroi}{TAJ}"),
 Analysis("SUBD2{di}{CONJ}-CAUSE{=ǰāt}{POST}"),
 Analysis("D2.M.SG.O{di}{DEM}-CAUSE{=ǰāt}{POST}-1SG{=um}{CL.AGR}"),
 Analysis("D2.M.SG.O{di}{DEM}-CAUSE{=ǰāt}{POST}"),
 Analysis("this_much{důnd}{PRO}-CAUSE{=ǰāt}{POST}"),
 Analysis("this_much{důnd}{PRO}-CAUSE{=ǰāt}{POST}"),
 Analysis("this_much{důnd}{PRO}-CAUSE{=ǰāt}{POST}"),
 Analysis("EMPH{yik=}{PRT}-D1.M.SG.O{mi}{DEM}-CAUSE{=ǰāt}{POST}"),
 Analysis("EMPH{Ik=}{PRT}-this_much{důnd}{PRO}-CAUSE{=ǰāt}{POST}")]

In [26]:
results.as_sent

[Sentence("yi či ǰāt cem sifc sitow"),
 Sentence("dam riwoyat (nawištaǰot) ǰāti Māmadnabiyi Xorůnī qīwǰ (yid nawištaǰot ɣalaθ yumand yast)."),
 Sentence("daδ az dasti dam aɣ̌dalen, mardumen naɣ̌ǰīdow ǰāt, obduzd čūɣ̌ǰ (bīrīn půnd)."),
 Sentence("důnd ǰāt wā wurusen-en vo tez-aθ toyd."),
 Sentence("dar borayi wi di ǰāt xalq bayn-and soz mis yast: "Mirzowafoyī safšikani bačayi alam...""),
 Sentence("důnd ǰāt idi, žiniǰ pi X̌ewā lap δed."),
 Sentence("di ǰāt zimistůn dāδ mardumen ač-aθ nax̌tīdow na vārδiyen."),
 Sentence("di-ǰāt idi, dā-yen xu rosti lůd."),
 Sentence("dāk-i čūɣ̌ǰ xu bačgalā-yard, wā wam qati bozi kin-en at, yā wev nān toyd pi qišloq yoɣ̌ǰ ǰāt."),
 Sentence("ik-důnd ǰāt idi, as mu bob darwā-yand-aθ-at tu xabar, mu bob-ard-at sar to sar wazīri tu čūɣ̌ǰ mu-rd-at ɣal-aθ wazīri kuansol."),
 Sentence("di-ǰāt-um wuz dam poδ-at kāl, pīlčak - mīlčak aloyid lāk čūd."),
 Sentence("at yā di wi ziv-and-i nex̌ ca δoδǰ, wi ɣêv-at nêʒ di-ǰāt kištêr-at, warami dār suδǰ."),
 Sentence("potx̌o lůd: - xêr, wāδ-en di-ǰat tar mu xez yaθč, wāδ-en andīc xu yaθč-en xex̌i tilāpt."),
 Sentence("bāden ǰamul-ǰam, yak bori digar nost-at, yu lůd, a vi-rod, ik tām-um yak moāboɣbůn-ard potx̌oyi ca tilāpt, di-ǰāt idi, sāwām ar xu watan, xu nān-at wi wazīri Lang āwol fāmām."),
 Sentence("māš-ām důnd-ǰāt yiθč."),
 Sentence("аtā yid Sulaymůn payɣumbar di aveni di ǰūk-at ǰůnwar ǰām čūd idi, dam čuɣʒ viraɣ̌en.."),
 Sentence("at pūrg lůd-i: - ye kud, i-kid nigīnā ar ǰo ca ik ar dam moyi qīč, yid di-ǰāt yoc rāng-ti θůd."),
 Sentence("di aven yid šič sic parindā xu, kū tar kū riwozd-at, ǰoy xu kix̌t."),
 Sentence("di waxt-and-at wazīr puc lůvd: - wuz-um mis tu miɣūnd mardīnā-yat, tu ɣāc ǰāt sust mā sāw."),
 Sentence("di ǰāt-en lůvǰ wi-rd: - pi māš mā rafet, māš xu yax dākām tama-rd."),
 Sentence("di ǰāt di wix̌īʒ na dāk-en."),
 Sentence("ar ǰo ca dāδ-en di fuk-aθ zox̌t, di ǰāt fuk-aθ de wazīr wev tarafdori kin-en, ar ǰo ca xazīnāyen δoδǰ."),
 Sentence("dori ǰātum fuk-a ǰoy x̌ikūd, na vūd-um, at tu mūm čīd-and-um důnd vūd."),
 Sentence("yid ɣiδā xabar sut idi, yid di xu xūni di divi-ti nix̌ůn čīd-ǰāt δoδǰ."),
 Sentence("bādi potx̌o farmůn δod idi, fānd δêd-ǰāt wam ɣ̌inik boyad ba dor tāž-en."),
 Sentence("Důnd ǰāt idi yā xató kix̌-t, yā yi=ga ɣāc wam viručāt kix̌-t."),
 Sentence("Yam mis… nāy, di=ǰāt yůdand ku yam yīw vad."),
 Sentence("O id yast yi=ga sof cvet vid, di=ǰāt…"),
 Sentence("Yu yi=ga bād čidům, ik=u ačaθ=ām wi ca nanêδǰ, důnd=ǰāt yůdand ku δuyůn?"),
 Sentence("Di=ǰāt padůd ca vuδǰat, suδǰ padůd, что ůn, māδ=en rost. At znāčit ik=māδ aray=en rost."),
 Sentence("Důnd=ǰāt dāδ=en ku aravīr disga…"),
 Sentence("Důnd=ǰāt yůdand čis…"),
 Sentence("Yabor va попробуем disga. Důnd=ǰāt dāδ arayen по_любому boyad rost viyen."),
 Sentence("Yā lůd: «A nān, wuz-um mis tarůd xuš čūd, ik-důnd-ǰāt-um tarůd yat»."),
 Sentence("Id bīdi důnd=ǰāt idi, mund yast mu soz=and idi, «Šêr=atā šoyiri qadri bed mam zamůn=and»."),
 Sentence("26 Atā Yeso as wi-yi pex̌st: «Atā Tawrot-and-en di ǰāt čīz lůvǰ?"),
 Sentence("29 Ammo yu Qonūn oxůn xu safedčīd ǰāt-i vo as Yeso pex̌st: «Atā mu-rd nazdīk odamizod čāy?»"),
 Sentence("Wuz lům tama-rd yidê yi-čāy-aθ-ta yik as wev dāwacuδǰinen tar mu dastorxůn kāl na yoδd: ǰatčūɣ̌ǰin lap atā qabulsuδǰin kām”»."),
 Sentence("16 Yu amex̌ā yik dis maɣ̌ʒůnǰ vud idê xūgen xurokā či xīd sut, důnd-aven idê wi-rd-en yi-čīz-aθ na δod."),
 Sentence("27 Atā yu ǰiwob-i δod: “Tu virod yat xu tu dod pirvor šīg-i kux̌t, důnd-aven idê tu virod zindā atā salůmat-aθ yat”."),
 Sentence("30 Atā yid tu puc, yidê tu mol at ol-i ǰalaben-ard šebt at binêst-i xu gax̌t čūd, atā tu-t di ǰāt pirvor-i šīg kux̌t!”"),
 Sentence("4 Yesuf mis tūyd as J̌alīl, as Nosirā-ndi, ar Yawūdo, ar Baytlem nům Dowūd x̌ār, důnd aven idê yu as Dowūd awlod vud."),
 Sentence("7 Wam-and sarfarzand puc sut, wix̌tak-i wi čūd xu ribūd-i ar winīr tar ɣiǰīd, důnd aven idê wev-ard ar qūšxůnā ǰoy na vud."),
 Sentence("23 důnd aven idê Xudowand Qonūn-and yaθč: «Ar narīnā sarfarzand boyad Xudowand-ard taqdīm sůd»."),
 Sentence("24 Atā āmga di ǰāt idê qurbůni kinen — «δu foxtā yo δiyůn čibůdbuc» ar rāng Xudowand Qonūn ca rimoδǰi ven."),
 Sentence("29 «Šič-ta Tu Xu bandā osoyax̌-aθ lāk-i, e Parwardigor, důnd aven idê Tu-t Xu wādā yiǰro čūd:"),
 Sentence("28 Atā Yeso tar wev gāx̌t xu lůd=i: «Mu mā nāwet, e Yerusalīm rizīnêrʒ! Xu ǰāt at xu ziryoten ǰāt nāwet!"),
 Sentence("28 Atā Yeso tar wev gāx̌t xu lůd=i: «Mu mā nāwet, e Yerusalīm rizīnêrʒ! Xu ǰāt at xu ziryoten ǰāt nāwet!"),
 Sentence("41 «Tu as Xuδoy x̌oǰ na δêri=yo? Tu=t xubaθ salīb=ard aweʒůn! Māš=and māš ǰinoyat ǰāt māš ǰazo yikam."),
 Sentence("45 důnd=aven idê xīr=en ara soat=and anǰūvd. Atā parδā mābad=and δu bāx̌ sat."),
 Sentence("48 Atā yik=id důnd mardumen=en tamošo ǰāt ǰām ca sicat,"),
 Sentence("7 Xubaθ-um mis důnd aven tar tu xez na yat idê loyiq-um nist. Tu yik-důnd rimi atā mu ɣulům-ta xub sůd."),
 Sentence("Bād wāδ… Yu sifīnt pi xu velik, užê či tīdak sůd=at, wāδ mis či tīd sen=at, viriyen wi šlyāpa ik=am=and wêx̌čin, wam zen, dāken wird abrātnê, fīčen wird, lůven: ma… mam=at binêst karočê. Wam dāken wird abrātnê=yat, yu wevard dākix̌t noken quluɣ lůvd ǰāt."),
 Sentence("Di=ǰāt uz nur rūz=and xoyix̌ kinum darborayi Dodxudo Karamšoev lůvdow idi, oxůn Dodxudo Karamšoev…"),
 Sentence("Di=ǰāt ik=di xu ziv nigā δêrtow=ard=at,"),
 Sentence("Di=ǰāt yu=yi xu zindagi bax̌xix̌ čūd"),
 Sentence("Di=ǰāt=ām māš fuk waxt=aθ az ustod Dodxudo Karamšoev"),
 Sentence("bād ikas wi tarůd māš awlodānd i lāv kasaliyenen ca nist, māšard disga lůven idi yid as čīzi ikwam pari ikwam safed ɣ̌inik idi yā māš bobi wam ik as di čīz awali wam pi xundi vīsč xu, bādi wam as kuden naǰot δoδǰ ikdiǰāt yi lāv dārδen amčun ikdi māš awlodāyand nist."),
 Sentence("fuk waxt δud čidenen bād diǰat ter wev wiδům ter vud"),
 Sentence("Mu mūm dis ayrůn sat, nāla «Yam čīz gāp yam x̌ūvd čīz=ǰāt tux̌p sůd?»"),
 Sentence("Mu yůn wi ǰat ǰaraɣas kix̌t."),
 Sentence("Oxirůn solen, cavor sol, dam yid… tar čīz naɣ̌ʒimč=en tar «Красная книга», naɣ̌ʒimč=en… kitobi surx. Dam šumora lap kam daraw sid, di=ǰāt=en damard aro čūɣ̌ǰ taškīl forum."),
 Sentence("Dam i čāy=aθ xoyix̌ nakix̌t zīdow, důnd=ǰāt=i di yid lap… čīz… qimatbaho kočor, yid vārδed yik=mi wiloyat=ard fanā daromad čīdow."),
 Sentence("Māš dam divix̌tow wevard navārδiyām, důnd=ǰāt [?] dāδ=en pi kūyen, dāδ lap δar az māš xez, amo darborayi dam yaden, māš wevard gāp δāδām."),
 Sentence("Nāla wuz=um wam lůd: «Yi čīr=aθ māk, wuz=at tu=ta ši wam lākām, důnd=ǰāti di tund bīst ǰůndor=ta bād māš turd viriyām=atā, yā=ta bīst milyůn daromad māšard vīrt. Māš wam lākām=xu, yā sůd."),
 Sentence("Šint=i yo, di=ǰāt yu=yi wi nax̌uδǰ yo, yakumin bor=i wi x̌uδǰ dis=ga xuɣ̌nůni yo, ik=u māš…"),
 Sentence("Baroi di fukaθ=ǰā iw=aθ, wi čīz=en id iw=aθ. Yu bād pex̌cč, idi ačga ikazmi masǰid yast=o nist."),
 Sentence("Di=ǰāt mev tūδ bunen pi bīr δew."),
 Sentence("di=ǰāt=um tamā x̌edow nalak čud"),
 Sentence("Xāy tar xizmat=i mis ik=di usto=yi čūɣ̌ǰ, azůd… di=ǰāt idi, di tāt usto vuδǰ."),
 Sentence("wuz taš mis mumkin ar čīz ca mu tāt čūɣ̌ǰin bidālum, důnd=ǰāt wi waxt ik=u vud, šič=ta vo dūs bidāl yu sůd aro."),
 Sentence("Xāy, mund mu zindagi lapdi mu nān=qatīr naɣ̌ǰīd, důnd=ǰāt mu tāt az ʒuliki=yaθ…"),
 Sentence("Dis=ga tobistůn vo cow čīdow=at, zimistůn žiniǰ=at, dis=ga koryůn lapdi deqůni vud, důnd=ǰāt māš=and k=id… māš čīd ǰamaāt fukaθ deqůn."),
 Sentence("Diraxt lůd-i: “Yik-mi-ǰāt wizůnum didi: wuz-um yik-mi dāx̌t-andīr yīwaθ diraxt-um, fuk mardum-ard-um soyā, atā yaden xu, mu bīr-va x̌ofcen xu, pi mu čisen, čisen xu, dāδ lůven: ‘Yik-u xêx̌ torx̌ dastā-rad bašānd’, – agar wev-and tavar ca ved, sifānen mu x̌ičix̌tow atā yi-čīz wev-ǰa nist xu, daδ tiyen."),
 Sentence("Ik-důnd-ǰāt wizůnum: odamen mazab-and, neki-rad badi”.")]

Alternatively, you can browse them as glossed examples:

In [27]:
print(*results.as_glossing, sep="\n\n")

yi či ǰāt cem sifc sitow
yi	či	ǰāt	cem	sifc	si-t-ow
one	who.O	CAUSE	eye	bead	become-INF-PURP
‘Долго ждать’ [Idioms (Alamshoev 1994), 18]

dam riwoyat (nawištaǰot) ǰāti Māmadnabiyi Xorůnī qīwǰ (yid nawištaǰot ɣalaθ yumand yast).
dam	riwoyat	nawištaǰot	ǰāt=i	Māmadnabi-yi	Xorůnī	qīw-ǰ	yid	nawištaǰot	ɣal=aθ	yum=and	yast
D2.F.SG.O	legend	inscription	CAUSE=3SG	Mamadnabi-EZ	Khoruni	call-PF	D2.SG	inscription	still=ADV	D3.LOC=LOC	there_is
‘Для написания предания (текста надписи) он пригласил Мамаднаби из Горона (эта надпись существует там до сих пор).’ [Imam, 10]

daδ az dasti dam aɣ̌dalen, mardumen naɣ̌ǰīdow ǰāt, obduzd čūɣ̌ǰ (bīrīn půnd).
daδ	az	dast-i	dam	aɣ̌dal=en	mardum-en	naɣ̌ǰīdow	ǰāt	čūɣ̌-ǰ	bīrīn	půnd
then	EL	hand-EZ	D2.F.SG.O	dragon=3PL	people-PL	pass	CAUSE	do-PF	lower	road
‘Поэтому люди сделали подземный ход (до крепости Рошткалъа).’ [The Anjin dragon, 5]

důnd ǰāt wā wurusen-en vo tez-aθ toyd.
důnd	ǰāt	wā	wurus-en=en	vo	tez=aθ	toy-d
this_much	CAUSE	D3.PL	Russian-PL=3PL	again	fast=ADV	leave.F/PL-PST
‘Потому, что те русские солдаты быстро ушли.’ [First resettlement, 20]

dar borayi wi di ǰāt xalq bayn-and soz mis yast: "Mirzowafoyī safšikani bačayi alam..."
dar.borayi	wi	di	ǰāt	xalq	bayn=and	soz	mis	yast	safšikan-i	bača-yi	alam
about	D3.M.SG.O	D2.M.SG.O	CAUSE	people	center=LOC	good	ADD2	there_is	mighty-EZ	child-EZ	world
‘Поэтому-то существует о нем песня среди народа.’ [Second resettlement, 22]

důnd ǰāt idi, žiniǰ pi X̌ewā lap δed.
důnd	ǰāt	idi	žiniǰ	pi	X̌ewā	lap	δe-d
this_much	CAUSE	COMPL	snow	UP	Khiva	much	fall_down-PRS.3SG
‘Потому что зимою в Хиве падает много снега.’ [Story, 27]

di ǰāt zimistůn dāδ mardumen ač-aθ nax̌tīdow na vārδiyen.
di	ǰāt	zimistůn	dāδ	mardum-en	ačaθ	nax̌tī-d-ow	na	vār-δi-yen
D2.M.SG.O	CAUSE	winter	D2.PL	people-PL	absolutely	go_out-INF-PURP	NEG	be_able-fall_down-PRS.3PL
‘Поэтому зимою люди никуда не могут выходить.’ [Story, 28]

di-ǰāt idi, dā-yen xu rosti lůd.
di=ǰāt	idi	dā=yen	xu	rost-i-	lů-d
D2.M.SG.O=CAUSE	COMPL	D2.PL=3PL	REFL	truth-INDEF-	say-PST
‘Сделал он так потому, что они сказали правду.’ [A black-skinned servant, 60]

dāk-i čūɣ̌ǰ xu bačgalā-yard, wā wam qati bozi kin-en at, yā wev nān toyd pi qišloq yoɣ̌ǰ ǰāt.
dāk=i	čūɣ̌-ǰ	xu	bač-galā=yard	wāδ	wam	qati	bozi	kin-en	at	yā	wev	nān	toy-d	pi	qišloq	yoɣ̌ǰ	ǰāt
give=3SG	do-PF	COORD1	child-PL=DAT	D3.PL	D3.F.SG.O	COM	game	do-PRS.3PL	COORD2	D3.F.SG	D3.PL.O	mother	leave.F/PL-PST	UP	village	flour	CAUSE
‘Отдала своим детям, они (же) с ним (начали играть) играют, а она пошла в кишлак за мукой.’ [Buor and Nuqra, 18]

ik-důnd ǰāt idi, as mu bob darwā-yand-aθ-at tu xabar, mu bob-ard-at sar to sar wazīri tu čūɣ̌ǰ mu-rd-at ɣal-aθ wazīri kuansol.
ik=důnd	ǰāt	idi	as	mu	bob	dawrā=yand=aθ=at	tu	xabar	mu	bob=ard=at	sar	to	sar	wazīri	tu	čūɣ̌-ǰ	mu=rd=at	ɣal=aθ	wazīr-i	kalůnsol
EMPH=this_much	CAUSE	COMPL	EL	PRN.1SG.O	grandfather	times=LOC=ADV=COORD2	PRN.2SG	acquainted	PRN.1SG.O	grandfather=DAT=COORD2	most	LIM1	most	minister duties	PRN.2SG	do-PF	PRN.1SG.O=DAT=COORD2	still=ADV	vizier-EZ	elderly
‘Потому что ты осведомлен со времени моего деда, моему деду с начала до конца ты был везирем, мне пока ты старый везирь".’ [Buor and Nuqra, 67]

di-ǰāt-um wuz dam poδ-at kāl, pīlčak - mīlčak aloyid lāk čūd.
di=ǰāt=um	wuz	dam	poδ=at	kāl	pīlčak-mīlčak	aloyid	lāk	čū-d
D2.M.SG.O=CAUSE=1SG	PRN.1SG	D2.F.SG.O	foot=COORD2	head	leg-REDUP	separate	let	do-PST
‘Поэтому я голову, ножки первой и другой клал по отдельности.’ [Buor and Nuqra, 106]

at yā di wi ziv-and-i nex̌ ca δoδǰ, wi ɣêv-at nêʒ di-ǰāt kištêr-at, warami dār suδǰ.
at	yā	di	wi	ziv=and=i	nex̌	ca	δoδ-ǰ	wi	ɣêv=at	nêʒ	di=ǰāt	kištêr=at	waram=i	dar	suδ-ǰ
COORD2	D3.F.SG	D2.M.SG.O	D3.M.SG.O	tongue=LOC=3SG	biting	SUBD1	fall_down-PF.M.SG	D3.M.SG.O	mouth=COORD2	nose	D2.M.SG.O=CAUSE	?=COORD2	swollen=3SG	swelling	become-PF.M.SG
‘Из-за того, что змея укусила его в (его) язык, его рот и нос опухли и почернели.’ [Buor and Nuqra, 162]

potx̌o lůd: - xêr, wāδ-en di-ǰat tar mu xez yaθč, wāδ-en andīc xu yaθč-en xex̌i tilāpt.
potx̌o	lů-d	xêr	wāδ=en	di=ǰāt	tar	mu	xez	yaθ-č	wāδ=en	andī-c	xu	yaθ-č=en	xex̌i	tilāp-t
king	say-PST	alright	D3.PL=3PL	D2.M.SG.O=CAUSE	EQ	PRN.1SG.O	APUD	come-PF	D3.PL=3PL	rise-PF.F/PL	COORD1	come-PF=3PL	match_making	ask_for-PRS.3SG
‘Падишх сказал: "Ведь они поэтому пришли ко мне. Они пришли свататься.’ [Buor and Nuqra, 274]

bāden ǰamul-ǰam, yak bori digar nost-at, yu lůd, a vi-rod, ik tām-um yak moāboɣbůn-ard potx̌oyi ca tilāpt, di-ǰāt idi, sāwām ar xu watan, xu nān-at wi wazīri Lang āwol fāmām.
bād=en	ǰamul-ǰam	yak	bor-i	digar	nos-t=at	yu	lů-d	a	virod	ik=	tām=um	yak	moāboɣbůn=ard	potx̌o=yi	ca	tilāp-t	di=ǰāt	idi	sāw-ām	ar	xu	watan	xu	nān=at	wi	wazīr-i	lang	āwol	fām=ām
then=3PL	_-_	one	time-EZ	other	sit.F/PL-PST=COORD2	D3.M.SG	say-PST	VOC	brother	EMPH=	then=1SG	one	?=DAT	king=3SG	SUBD1	ask_for-PRS.3SG	D2.M.SG.O=CAUSE	COMPL	go-PRS.1PL	DOWN	REFL	homeland	REFL	mother=COORD2	D3.M.SG.O	vizier-EZ	lame	life	understand=1PL
‘Потом все вместе еще раз посидели и тот (Нукра) сказал: "Эй, брат, тогда когда я говорил об одном месяце царствования садовника, то это было связано с тем, чтобы мы поехали в свою страну и узнали о своей маме и хромом везире".’ [Buor and Nuqra, 383]

māš-ām důnd-ǰāt yiθč.
māš=ām	důnd=ǰāt	yiθ-č
PRN.1PL=1PL	this_much=CAUSE	come-PF
‘Мы пришли по этому поводу."’ [Buor and Nuqra, 398]

аtā yid Sulaymůn payɣumbar di aveni di ǰūk-at ǰůnwar ǰām čūd idi, dam čuɣʒ viraɣ̌en..
аtā	yid	Sulaymůn	payɣumbar	di	aven=i	di	ǰūk=at	ǰůnwar	ǰām	čū-d	idi	dam	čuɣʒ	viray=en
and	D2.SG	Solomon	prophet	D2.M.SG.O	CAUSE=3SG	D2.M.SG.O	living creatures=COORD2	living creatures	gathered	do-PST	COMPL	D2.F.SG.O	owl	find=3PL
‘А (тот) пророк Сулаймон по этому поводу собрал все живое (птиц и насекомых), чтобы нашли (ту) Сову.’ [Owl, gyrfalcon, nightingale and hawk, 10]

at pūrg lůd-i: - ye kud, i-kid nigīnā ar ǰo ca ik ar dam moyi qīč, yid di-ǰāt yoc rāng-ti θůd.
at	pūrg	lů-d=i	ye	kud	ik=id	nigīnā	ar	ǰo	ca	ik=	ar	dam	moyi	qīč	yid	di=ǰāt	yoc	rāng=ti	θů-d
COORD2	mouse	say-PST=3SG	VOC	dog	EMPH=D2.SG	ring	every	place	SUBD1	EMPH=	DOWN	D2.F.SG.O	fish	stomach	D2.SG	D2.M.SG.O=CAUSE	fire	SIMIL=SUP	burn-PRS.3SG
‘И (та) Мышь обратилась к Собаке: "Наверно, то кольцо находится внутри (той) рыбы, потому она так блестит.’ [Owl, gyrfalcon, nightingale and hawk, 91]

di aven yid šič sic parindā xu, kū tar kū riwozd-at, ǰoy xu kix̌t.
di	aven	yid	šič	si-c	parindā	xu	kū	tar	kū	riwoz-d=at	ǰoy	xu	kix̌-t
D2.M.SG.O	CAUSE	D2.SG	now	become-PF.F/PL	bird	COORD1	mountain	EQ	mountain	fly-PRS.3SG=COORD2	place	COORD1	do-PRS.3SG
‘Поэтому (тот) Кречет превратился в птицу и летает с горы на гору и прячется,’ [Owl, gyrfalcon, nightingale and hawk, 108]

di waxt-and-at wazīr puc lůvd: - wuz-um mis tu miɣūnd mardīnā-yat, tu ɣāc ǰāt sust mā sāw.
di	waxt=and=at	wazīr	puc	lův-d	wuz=um	mis	tu	miɣūnd	mardīnā=yat	tu	ɣāc	ǰāt	sust	mā	sāw
D2.M.SG.O	time=LOC=COORD2	vizier	son	say-PRS.3SG	PRN.1SG=1SG	ADD2	PRN.2SG	such	man=COORD2	PRN.2SG	girl	CAUSE	feeble	NEG.IRR	go
‘При этом (а это время) сын везиря сказал: "Я тоже, как и ты, мужчина, но не падаю же в обморок.’ [The king’s son and the vizier’s son, 58]

di ǰāt-en lůvǰ wi-rd: - pi māš mā rafet, māš xu yax dākām tama-rd.
di	ǰāt=en	lův-ǰ	wi=rd	pi	māš	mā	raf=et	māš	xu	yax	dāk=ām	tama=rd
D2.M.SG.O	CAUSE=3PL	say-PF	D3.M.SG.O=DAT	UP	PRN.1PL	NEG.IRR	touch=2PL	PRN.1PL	REFL	sister	give=1PL	PRN.2PL=DAT
‘Поэтому сказали ему "Нас не трогайте, мы дадим вам свою сестру”.’ [The king’s son and the vizier’s son, 69]

di ǰāt di wix̌īʒ na dāk-en.
di	ǰāt	di	wix̌īʒ	na	dāk=en
D2.M.SG.O	CAUSE	D2.M.SG.O	key	NEG	give=3PL
‘Поэтому не дают ключа от нее.’ [The king’s son and the vizier’s son, 75]

ar ǰo ca dāδ-en di fuk-aθ zox̌t, di ǰāt fuk-aθ de wazīr wev tarafdori kin-en, ar ǰo ca xazīnāyen δoδǰ.
ar	ǰo	ca	dāδ=en	di	fukaθ	zox̌-t	di	ǰāt	fukaθ	de	wazīr	wev	tarafdori	kin-en	ar	ǰo	ca	xazīnā-yen	δoδ-ǰ
every	place	SUBD1	D2.PL=3PL	D2.M.SG.O	all	take-PST	D2.M.SG.O	CAUSE	all	D2.PL.O	vizier	D3.PL.O	support	do-PRS.3PL	every	place	SUBD1	storeroom-PL	give-PF
‘По-моему, они все взяли, поэтому все на их стороне. Наверно, обокрали казну".’ [The king of the east and the west, 138]

dori ǰātum fuk-a ǰoy x̌ikūd, na vūd-um, at tu mūm čīd-and-um důnd vūd.
dori	ǰāt=um	fukaθ	ǰoy	x̌ikū-d	na	vū-d=um	at	tu	mūm	čīd=and=um	důnd	vū-d
medicine	CAUSE=1SG	all	place	search-PST	NEG	bring-PST=1SG	COORD2	PRN.2SG	grandmother	house=LOC=1SG	this_much	bring-PST
‘Из-за лекарства я обыскала всюду, но не нашла, а нашла только в доме твоей бабушки".’ [White camel, 166]

yid ɣiδā xabar sut idi, yid di xu xūni di divi-ti nix̌ůn čīd-ǰāt δoδǰ.
yid	ɣiδā	xabar	su-t	idi	yid	di	xu	xūn=i	di	divi=ti	nix̌ůn	čīd=ǰāt	δoδ-ǰ
D2.SG	boy	acquainted	go.M.SG-PST	COMPL	D2.SG	D2.M.SG.O	COORD1	blood=3SG	D2.M.SG.O	door=SUP	mark	house=CAUSE	fall_down-PF.M.SG
‘Юноша понял, что она оставила отпечатка крови, чтобы выдать их.’ [White camel, 182]

bādi potx̌o farmůn δod idi, fānd δêd-ǰāt wam ɣ̌inik boyad ba dor tāž-en.
bād=i	potx̌o	farmůn	δo-d	idi	fānd	δêd=ǰāt	wam	ɣ̌inik	boyad	ba	dor	tāž=en
then=3SG	king	order	give-PST	COMPL	lie	war=CAUSE	D3.F.SG.O	woman	must	ALL	gallows	pull=3PL
‘(Твой) падишах приказал, чтобы ту женщину за обман казнили.’ [White camel, 196]

Důnd ǰāt idi yā xató kix̌-t, yā yi=ga ɣāc wam viručāt kix̌-t.
důnd	ǰāt	idi	yā	xató	kix̌-t	yā	yi=ga	ɣāc	wam	viručāt	kix̌-t
this_much	CAUSE	COMPL	D3.F.SG	mistake	do-PRS.3SG	D3.F.SG	INDEF=ADD1	girl	D3.F.SG.O	rescue	do-PRS.3SG
‘Потому, что она ошибается, ее и выручает другая девочка.’ [Game of makak, 3]

Yam mis… nāy, di=ǰāt yůdand ku yam yīw vad.
yam	mis	nāy	di=ǰāt	yůd=and	ku	yam	yīw	va-d
D1.SG	ADD2	no	D2.M.SG.O=CAUSE	D1.LOC=LOC	PTCL	D1.SG	one	be.F/PL-PST
‘Эта тоже… нет, потому что здесь же была только одна.’ [Codebreaker (NG06 & SK06) №1, 23]

O id yast yi=ga sof cvet vid, di=ǰāt…
o	id	yast	yi=ga	sof	cvet	vi-d	di=ǰāt
OR	D2.SG	maybe	INDEF=ADD1	clear	colour	be-PRS.3SG	D2.M.SG.O=CAUSE
‘Или эта может быть совсем другим цветом, поэтому…’ [Codebreaker (NG06 & SK06) №1, 26]

Yu yi=ga bād čidům, ik=u ačaθ=ām wi ca nanêδǰ, důnd=ǰāt yůdand ku δuyůn?
yu	yi=ga	bād	čidům	ik=u	ačaθ=ām	wi	ca	na-nêδ-ǰ	důnd=ǰāt	yůd=and	ku	δuyůn
D3.M.SG	INDEF=ADD1	then	which	EMPH=D3.M.SG	at_all=1PL	D3.M.SG.O	SUBD1	NEG-seat-PF	this_much=CAUSE	D1.LOC=LOC	PTCL	two
‘Этот другой какой тогда, которого мы вообще ещё не ставили, здесь же два?’ [Codebreaker (NG06 & SK06) №2, 10]

Di=ǰāt padůd ca vuδǰat, suδǰ padůd, что ůn, māδ=en rost. At znāčit ik=māδ aray=en rost.
di=ǰāt	pad-ůd	ca	vuδ-ǰ-at	suδ-ǰ	pad-ůd	что	ůn	māδ=en	rost	at	znāčit	ik=māδ	aray=en	rost
D2.M.SG.O=CAUSE	UP-D1.LOC	SUBD1	be-PF.M.SG-PQP	become-PF.M.SG	UP-D1.LOC	that	yes	D1.PL=3PL	right	COORD2	this_means	EMPH=D1.PL	three=3PL	right
‘Потому что если они были бы здесь, здесь было бы так, что да, эти правильные. Но значит, эти три правильные.’ [Codebreaker (NG06 & SK06) №2, 38]

Důnd=ǰāt dāδ=en ku aravīr disga…
důnd=ǰāt	dāδ=en	ku	ara-vīr	disga
this_much=CAUSE	D2.PL=3PL	PTCL	three-all	such
‘Потому что они все три же так…’ [Codebreaker (NG06 & SK06) №2, 91]

Důnd=ǰāt yůdand čis…
důnd=ǰāt	yůd=and	čis
this_much=CAUSE	D1.LOC=LOC	look
‘Помому что сюда посмотри…’ [Codebreaker (NG06 & SK06) №2, 98]

Yabor va попробуем disga. Důnd=ǰāt dāδ arayen по_любому boyad rost viyen.
yabor	va	попробуем	disga	důnd=ǰāt	dāδ	aray-en	по_любому	boyad	rost	vi-yen
once	PTCL	we’ll_try	such	this_much=CAUSE	D2.PL	three-PL	anyway	must	right	be-PRS.3PL
‘Давай попробуем так. Потому что эти три по-любому должны быть правильные.’ [Codebreaker (NG06 & SK06) №2, 131]

Yā lůd: «A nān, wuz-um mis tarůd xuš čūd, ik-důnd-ǰāt-um tarůd yat».
yā	lů-d	a	nān	wuz=um	mis	tar-ůd	xuš	čū-d	ik=důnd=ǰāt=um	tar-ůd	ya-t
D3.F.SG	say-PRS.3SG	VOC	mother	PRN.1SG=1SG	ADD2	EQ-D1.LOC	happy	do-PST	EMPH=this_much=CAUSE=1SG	EQ-D1.LOC	come-PST
‘Она говорит: «Мама, мне тут тоже нравится, поэтому я и пришла сюда».’ [White mountain goat, 45]

Id bīdi důnd=ǰāt idi, mund yast mu soz=and idi, «Šêr=atā šoyiri qadri bed mam zamůn=and».
id	bīdi	důnd=ǰāt	idi	mu=nd	yast	mu	soz=and	idi	šêr=atā	šoyiri	qadri	be-d	mam	zamůn=and
D2.SG	better	this_much=CAUSE	COMPL	PRN.1SG.O=LOC	there_is	PRN.1SG.O	song=LOC	COMPL	poem=COORD3	poetry	authority	disappear-PST	D1.F.SG.O	time=LOC
‘Это настолько лучше, как вот в моей песне: «Ценность поэзии и песни потеряна в наше время».’ [Interview with Lidush Habib (Part 1), 22]

26 Atā Yeso as wi-yi pex̌st: «Atā Tawrot-and-en di ǰāt čīz lůvǰ?
Atā	Yeso	as	wi=yi	pêx̌s-t	Atā	tawrot=and=en	di	ǰāt	čīz	lův-ǰ
COORD3	Jesus	EL	D3.M.SG.O=3SG	ask-PST	COORD3	Torah=LOC=3PL	D2.M.SG.O	CAUSE	thing	say-PF
‘Иисус ответил ему: «Что записано в Законе?’ [Gospel of Luke, Chapter 10: 25–37, 2]

29 Ammo yu Qonūn oxůn xu safedčīd ǰāt-i vo as Yeso pex̌st: «Atā mu-rd nazdīk odamizod čāy?»
ammo	yu	qonūn	oxůn	xu	safed-čī-d	ǰāt=i	vo	as	Yeso	pêx̌s-t	Atā	mu=rd	nazdīk	odamizod	čāy
but	D3.M.SG	law	teacher	REFL	white-do-INF	CAUSE=3SG	again	EL	Jesus	ask-PST	COORD3	PRN.1SG.O=DAT	close	human-born	who
‘Но законник, желая оправдаться, спросил Иисуса: «А кто мой ближний?»’ [Gospel of Luke, Chapter 10: 25–37, 6]

Wuz lům tama-rd yidê yi-čāy-aθ-ta yik as wev dāwacuδǰinen tar mu dastorxůn kāl na yoδd: ǰatčūɣ̌ǰin lap atā qabulsuδǰin kām”».
wuz	lů-m	tama=rd	yidê	yi-čāy=aθ=ta	yik=	as	wev	dāwat-suδ-ǰ-in-en	tar	mu	dastorxůn	kāl	na	yoδ-d	ǰat-čūɣ̌-ǰ-in	lap	atā	qabul-suδ-ǰ-in	kām
PRN.1SG	say-PRS.1SG	PRN.2PL=DAT	COMPL	INDEF-who=INT=FUT	EMPH=	EL	D3.PL.O	invitation-become-PF.M.SG-PTCP1-PL	EQ	PRN.1SG.O	dastarkhan	head	NEG	memory-PRS.3SG	CAUSE-do-PF-PTCP1	much	COORD3	reception-become-PF.M.SG-PTCP1	a_little
‘Ибо сказываю вам, что никто из тех званых не вкусит моего ужина, ибо много званых, но мало избранных.’ [Gospel of Luke, Chapter 14: 15–24, 12]

16 Yu amex̌ā yik dis maɣ̌ʒůnǰ vud idê xūgen xurokā či xīd sut, důnd-aven idê wi-rd-en yi-čīz-aθ na δod.
Yu	amex̌ā	yik=	dis	maɣ̌ʒůnǰ	vu-d	idê	xūg-en	xurokā	či	xī-d	su-t	důnd=aven	idê	wi=rd=en	yi-čīz=aθ	na	δo-d
D3.M.SG	always	EMPH=	such	hungry	be.M.SG-PST	COMPL	pig-PL	food	PROSP	eat-INF	become.M.SG-PST	this_much=CAUSE	COMPL	D3.M.SG.O=DAT=3PL	INDEF-thing=INT	NEG	give-PST
‘Он был так голоден, что рад бы был поесть корм для свиней, но даже этого ему никто не давал.’ [Gospel of Luke, Chapter 15: 11–32, 7]

27 Atā yu ǰiwob-i δod: “Tu virod yat xu tu dod pirvor šīg-i kux̌t, důnd-aven idê tu virod zindā atā salůmat-aθ yat”.
Atā	yu	ǰiwob=i	δo-d	tu	virod	ya-t	xu	tu	dod	pirvor	šīg=i	kux̌-t	důnd=aven	idê	tu	virod	zindā	atā	salůmat=aθ	ya-t
COORD3	D3.M.SG	answer=3SG	give-PST	PRN.2SG	brother	come-PST	COORD1	PRN.2SG	father	fattened	calf=3SG	cut-PST	this_much=CAUSE	COMPL	PRN.2SG	brother	alive	COORD3	healthy=INT	come-PST
‘Слуга сказал ему: “Твой брат вернулся, и отец твой заколол откормленного телёнка, потому что вновь обрёл сына, живым и невредимым”.’ [Gospel of Luke, Chapter 15: 11–32, 19]

30 Atā yid tu puc, yidê tu mol at ol-i ǰalaben-ard šebt at binêst-i xu gax̌t čūd, atā tu-t di ǰāt pirvor-i šīg kux̌t!”
Atā	yid	tu	puc	yidê	tu	mol	at	ol=i	ǰalab-en=ard	šeb-t	at	binês-t=i	xu	gax̌t	čū-d	atā	tu=t	di	ǰāt	pirvor-i	šīg	kux̌-t
COORD3	D2.SG	PRN.2SG	son	COMPL	PRN.2SG	property	COORD2	state=3SG	wanton-PL=DAT	spend-PST	COORD2	lose-PST=3SG	COORD1	coming_back	do-PST	COORD3	PRN.2SG=2SG	D2.M.SG.O	CAUSE	fattened-ADJ	calf	cut-PST
‘Когда же пришёл твой сын, расточивший всё твоё состояние с блудницами, ты заколол для него откормленного телёнка”.’ [Gospel of Luke, Chapter 15: 11–32, 23]

4 Yesuf mis tūyd as J̌alīl, as Nosirā-ndi, ar Yawūdo, ar Baytlem nům Dowūd x̌ār, důnd aven idê yu as Dowūd awlod vud.
Yesuf	mis	tūy-d	as	J̌alīl	as	Nosirā=ndi	ar	Yawūdo	ar	Baytlem	nům	Dowūd	x̌ār	důnd	aven	idê	yu	as	Dowūd	awlod	vu-d
Joseph	ADD2	leave.M.SG-PST	EL	Galilee	EL	Nazareth=LOC	DOWN	Judea	DOWN	Bethlehem	name	David	city	this_much	CAUSE	COMPL	D3.M.SG	EL	David	family	be.M.SG-PST
‘Пошел также и Иосиф из Галилеи, из города Назарета, в Иудею, в город Давидов, называемый Вифлеем, потому что он был из дома и рода Давидова’ [Gospel of Luke, Chapter 2: 1–52, 4]

7 Wam-and sarfarzand puc sut, wix̌tak-i wi čūd xu ribūd-i ar winīr tar ɣiǰīd, důnd aven idê wev-ard ar qūšxůnā ǰoy na vud.
Wam=and	sarfarzand	puc	su-t	wix̌tak=i	wi	čū-d	xu	ribū-d=i	ar	winīr	tar	ɣiǰīd	důnd	aven	idê	wev=ard	ar	qūšxůnā	ǰoy	na	vu-d
D3.F.SG.O=LOC	firstborn	son	go.M.SG-PST	swaddle=3SG	D3.M.SG.O	do-PST	COORD1	put-PST=3SG	DOWN	manger	EQ	stable	this_much	CAUSE	COMPL	D3.PL.O=DAT	DOWN	inn	place	NEG	be.M.SG-PST
‘и родила Сына своего Первенца, и спеленала Его, и положила Его в ясли, потому что не было им места в гостинице.’ [Gospel of Luke, Chapter 2: 1–52, 7]

23 důnd aven idê Xudowand Qonūn-and yaθč: «Ar narīnā sarfarzand boyad Xudowand-ard taqdīm sůd».
důnd	aven	idê	xudowand	qonūn=and	yaθ-č	ar	narīnā	sarfarzand	boyad	xudowand=ard	taqdīm	sů-d
this_much	CAUSE	COMPL	God	law=LOC	come-PF	every	male	firstborn	must	God=DAT	presenting	become-PRS.3SG
‘как предписано в законе Господнем, чтобы всякий младенец мужеского пола, разверзающий ложесна, был посвящен Господу,’ [Gospel of Luke, Chapter 2: 1–52, 23]

24 Atā āmga di ǰāt idê qurbůni kinen — «δu foxtā yo δiyůn čibůdbuc» ar rāng Xudowand Qonūn ca rimoδǰi ven.
Atā	ām-ga	di	ǰāt	idê	qurbůni	kin-en	δu	foxtā	yo	δiyůn	čibůd-buc	ar	rāng	xudowand	qonūn	ca	rimoδ-ǰ=i	v-en
COORD3	COORD5-ADD1	D2.M.SG.O	CAUSE	COMPL	sacrifice	do-PRS.3PL	two	pigeon	OR	two	dove-child.M	every	SIMIL	God	law	SUBD1	order-PF=3SG	bring-PRS.3PL
‘и чтобы принести в жертву, по реченному в законе Господнем, две горлицы или двух птенцов голубиных.’ [Gospel of Luke, Chapter 2: 1–52, 24]

29 «Šič-ta Tu Xu bandā osoyax̌-aθ lāk-i, e Parwardigor, důnd aven idê Tu-t Xu wādā yiǰro čūd:
šič=ta	tu	xu	bandā	osoyax̌=aθ	lāk-i	e	parwardigor	důnd	aven	idê	Tu=t	xu	wādā	yiǰro	čū-d
now=FUT	PRN.2SG	REFL	servant	peace=ADV	let-PRS.2SG	VOC	creator	this_much	CAUSE	COMPL	PRN.2SG=2SG	REFL	time	implementation	do-PST
‘Ныне отпускаешь раба Твоего, Владыко, по слову Твоему, с миром,’ [Gospel of Luke, Chapter 2: 1–52, 29]

28 Atā Yeso tar wev gāx̌t xu lůd=i: «Mu mā nāwet, e Yerusalīm rizīnêrʒ! Xu ǰāt at xu ziryoten ǰāt nāwet!
atā	Yeso	tar	wev	gāx̌-t	xu	lů-d=i	mu	mā	nāw-et	e	Yerusalīm	rizīn-êrʒ	xu	ǰāt	at	xu	ziryot-en	ǰāt	nāw-et
COORD3	Jesus	EQ	D3.PL.O	turn-PST	COORD1	say-PST=3SG	PRN.1SG.O	NEG.IRR	cry-PRS.2PL	VOC	Jerusalem	daughter-PL	REFL	CAUSE	COORD2	REFL	child-PL	CAUSE	cry-PRS.2PL
‘Но, обернувшись, Иисус сказал им: «Дочери иерусалимские, не плачьте обо Мне. Оплакивайте себя и детей своих,’ [Gospel of Luke, Chapter 23: 26–49, 3]

28 Atā Yeso tar wev gāx̌t xu lůd=i: «Mu mā nāwet, e Yerusalīm rizīnêrʒ! Xu ǰāt at xu ziryoten ǰāt nāwet!
atā	Yeso	tar	wev	gāx̌-t	xu	lů-d=i	mu	mā	nāw-et	e	Yerusalīm	rizīn-êrʒ	xu	ǰāt	at	xu	ziryot-en	ǰāt	nāw-et
COORD3	Jesus	EQ	D3.PL.O	turn-PST	COORD1	say-PST=3SG	PRN.1SG.O	NEG.IRR	cry-PRS.2PL	VOC	Jerusalem	daughter-PL	REFL	CAUSE	COORD2	REFL	child-PL	CAUSE	cry-PRS.2PL
‘Но, обернувшись, Иисус сказал им: «Дочери иерусалимские, не плачьте обо Мне. Оплакивайте себя и детей своих,’ [Gospel of Luke, Chapter 23: 26–49, 3]

41 «Tu as Xuδoy x̌oǰ na δêri=yo? Tu=t xubaθ salīb=ard aweʒůn! Māš=and māš ǰinoyat ǰāt māš ǰazo yikam.
tu	as	xuδoy	x̌oǰ	na	δêr-i=yo	tu=t	xubaθ	salīb=ard	aweʒůn	māš=and	māš	ǰinoyat	ǰāt	māš	ǰazo	yikam
PRN.2SG	EL	God	fear	NEG	have-PRS.2SG=Q	PRN.2SG=2SG	SELF	cross=DAT	hanging	PRN.1PL=LOC	PRN.1PL	crime	CAUSE	PRN.1PL	punishment	???
‘«Побойся Бога. Мы все трое скоро умрём. Мы-то с тобой виновны, и нас следует убить за то зло, что мы совершили.’ [Gospel of Luke, Chapter 23: 26–49, 19]

45 důnd=aven idê xīr=en ara soat=and anǰūvd. Atā parδā mābad=and δu bāx̌ sat.
důnd=aven	idê	xīr=en	ara	soat=and	anǰūv-d	atā	parδā	mābad=and	δu	bāx̌	sa-t
this_much=CAUSE	COMPL	sun=3PL	three	hour=LOC	keep-PST	COORD3	curtain	temple=LOC	two	part	become.F/PL-PST
‘и солнце не светило, и завеса храма разорвалась надвое.’ [Gospel of Luke, Chapter 23: 26–49, 24]

48 Atā yik=id důnd mardumen=en tamošo ǰāt ǰām ca sicat,
atā	yik=id	důnd	mardum-en=en	tamošo	ǰāt	ǰām	ca	si-c-at
COORD3	EMPH=D2.SG	this_much	people-PL=3PL	watching	CAUSE	gathered	SUBD1	become-PF.F/PL-PQP

You can get all unique morph-gloss combinations to get a generalized idea of the result:

In [28]:
results.morphemes

[(('=ǰāt', 'CAUSE'), 36),
 (('ǰāt', 'CAUSE'), 24),
 (('aven', 'CAUSE'), 7),
 (('=aven', 'CAUSE'), 3),
 (('ǰat', 'CAUSE'), 2),
 (('=ǰāt', 'CAUSE'), 1),
 (('=ǰat', 'CAUSE'), 1),
 (('baroi', 'CAUSE'), 1)]

Finally, it is possible to export the results into a `pandas` dataframe:

In [29]:
results.to_df()

,token_id,token,sent_id,sentence,morphs,glosses,pos,translation,subcorpus,text.title,text.filename,text.author,text.year
0,3,ǰāt,18,yi či ǰāt cem sifc sitow,yi či ǰāt cem sifc si-t-ow,one who.O CAUSE eye bead become-INF-PURP,NUM PRO POST N V-NMLZ-NMLZ,Долго ждать,Idioms (Alamshoev 1994),Idioms (Alamshoev 1994),sgh_alamshoev_Idioms.eaf,,
1,4,ǰāti,10,dam riwoyat (nawištaǰot) ǰāti Māmadnabiyi Xo...,dam riwoyat nawištaǰot ǰāt=i Māmadnabi-yi Xo...,D2.F.SG.O legend inscription CAUSE=3SG Mamadna...,DEM POST=CL.AGR -POST V-T DEM PRT=PRT DEM....,Для написания предания (текста надписи) он при...,Legends (Alamshoev 1994),Imam,sgh_alamshoev_legend_Imam.eaf,"Аловатов Азизбек, 1915 г.р.",1988
2,8,"ǰāt,",5,"daδ az dasti dam aɣ̌dalen, mardumen naɣ̌ǰīdow...",daδ az dast-i dam aɣ̌dal=en mardum-en naɣ̌ǰīd...,then EL hand-EZ D2.F.SG.O dragon=3PL people-PL...,PRT PREP N-POST DEM N=CL.AGR N-N.AFF POST _ V...,Поэтому люди сделали подземный ход (до крепост...,Legends (Alamshoev 1994),The Anjin dragon,sgh_alamshoev_legend_The_Anjin_dragon.eaf,"Мирзовафоев Зафар, 90 лет",1987
3,2,ǰāt,20,důnd ǰāt wā wurusen-en vo tez-aθ toyd.,důnd ǰāt wā wurus-en=en vo tez=aθ toy-d,this_much CAUSE D3.PL Russian-PL=3PL again fas...,PRO POST DEM N-N.AFF=CL.AGR PRT N=PRT V-T,"Потому, что те русские солдаты быстро ушли.",Stories (Alamshoev 1994),First resettlement,sgh_alamshoev_story_First_resettlement.eaf,"Мирзовафоев Зафар, 90 лет",1987
4,4,ǰāt,22,dar borayi wi di ǰāt xalq bayn-and soz mis ya...,dar.borayi wi di ǰāt xalq bayn=and soz mis ya...,about D3.M.SG.O D2.M.SG.O CAUSE people center=...,DEM DEM POST N N=POST N PRT V -POST N-POST,Поэтому-то существует о нем песня среди народа.,Stories (Alamshoev 1994),Second resettlement,sgh_alamshoev_story_Second_resettlement.eaf,"Мирзовафоев Зафар, 90 лет",1987
...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,12,důnd=ǰāt,58,wuz taš mis mumkin ar čīz ca mu tāt čūɣ̌ǰin b...,wuz taš mis mumkin ar čīz ca mu tāt čūɣ̌-ǰ-in...,PRN.1SG PROSP ADD2 maybe every thing SUBD1 PRN...,PERS PRT PRT PRT PRO PRO CONJ PERS N V-T-NMLZ ...,"я вот тоже может поменяю что-то, сделанное мои...",Oral texts (modern recordings),Yusufbekov’s grandfather,sgh_txt_YFS_Yusufbekovs_grandfather.eaf,YFS,2019
71,9,důnd=ǰāt,3,"Xāy, mund mu zindagi lapdi mu nān=qatīr naɣ̌ǰ...",xāy mu=nd mu zindagi lap-di mu nān=qatīr naɣ̌j...,HEZ PRN.1SG.O=LOC PRN.1SG.O life much-COMP PRN...,PRT PERS=POST PERS N PRT-N.AFF PERS N=POST V-T...,"Итак, большая часть моей жизни с детства прошл...",Oral texts (modern recordings),Bio (ZSh),sgh_txt_ZSh_Bio.eaf,ZSh,2022
72,13,důnd=ǰāt,9,"Dis=ga tobistůn vo cow čīdow=at, zimistůn žini...",disga tobistůn vo cow čī-d-ow=at zimistůn žini...,such summer again harvest do-INF-PURP=COORD2 w...,PRO N PRT N V-NMLZ-NMLZ=CONJ N N=CONJ PRO N-N....,"Таким образом, летом жатва, а зимой снег, тако...",Oral texts (modern recordings),Bio (ZSh),sgh_txt_ZSh_Bio.eaf,ZSh,2022
73,3,“Yik-mi-ǰāt,18,Diraxt lůd-i: “Yik-mi-ǰāt wizůnum didi: wuz-u...,diraxt lů-d=i yik=mi=ǰāt wizůn=um didi wuz=um...,tree say-PST=3SG EMPH=D1.M.SG.O=CAUSE know=1SG...,N V-T=CL.AGR PRT=DEM=POST V=CL.AGR CONJ PERS=C...,"Дерево сказало: ""Вот почему я знаю: в этой сте...",Texts (Zarubin 1960),A man and a snake,sgh_zarubin_A_man_and_a_snake.eaf,Шо-Фозил,1915
74,1,Ik-důnd-ǰāt,19,"Ik-důnd-ǰāt wizůnum: odamen mazab-and, neki-r...",Ik=důnd=ǰāt wizůn=um odam-en mazab=and neki=r...,EMPH=this_much=CAUSE know=1SG person-PL religi...,PRT=PRO=POST V=CL.AGR N-N.AFF N=POST N=POST N,"Вот потому-то я и знаю, что, по человеческой в...",Texts (Zarubin 1960),A man and a snake,sgh_zarubin_A_man_and_a_snake.eaf,Шо-Фозил,1915

### Search morpheme chain

If you need to look for specific combinations of morphemes, use the method `.search_morphemechain()`. It will find all cases, where the required morphemes are consecutive in a token’s analysis.

Provide an argument `gloss_index_string`, which is a glossed string in the Tsakorpus format. It has all glosses and morphs for each morpheme, separated by a hyphen: `"go{sit}-INF{t}-PURP{ow}"`). All glosses and morphs may contain regular expressions, and glosses are case-sensitive. You don’t need to specify hyphens and equal signs for affixes and clitics.

In [30]:
stroka = "PURP{ow}-DAT{ard}"
results = corpus.search_morphemechain(gloss_index_string=stroka)
results

[[Morpheme("PURP{-ow}{NMLZ}"), Morpheme("DAT{=ard}{POST}")],
 [Morpheme("PURP{-ow}{NMLZ}"), Morpheme("DAT{=ard}{POST}")],
 [Morpheme("PURP{-ow}{NMLZ}"), Morpheme("DAT{=ard}{POST}")],
 [Morpheme("PURP{-ow}{NMLZ}"), Morpheme("DAT{=ard}{POST}")],
 [Morpheme("PURP{-ow}{NMLZ}"), Morpheme("DAT{=ard}{POST}")],
 [Morpheme("PURP{-ow}{NMLZ}"), Morpheme("DAT{=ard}{POST}")],
 [Morpheme("PURP{-ow}{NMLZ}"), Morpheme("DAT{=ard}{POST}")],
 [Morpheme("PURP{-ow}{NMLZ}"), Morpheme("DAT{=ard}{POST}")],
 [Morpheme("PURP{-ow}{NMLZ}"), Morpheme("DAT{=ard}{POST}")]]

In [31]:
results = corpus.search_morphemechain(gloss_index_string=".+{carāng}-PRS..+{.+}")
results

[[Morpheme("how{carāng}{PRO}"), Morpheme("PRS.1SG{-um}{V.AGR}")],
 [Morpheme("how{carāng}{PRO}"), Morpheme("PRS.1PL{-ām}{V.AGR}")],
 [Morpheme("how{carāng}{PRO}"), Morpheme("PRS.1PL{-ām}{V.AGR}")]]

Results of morpheme chain search are stored in an object of the type `cx.MorphemeChainSearch`, so you can view the results in the similar neat ways as `cx.MorphemeSearch` (see above):

In [32]:
results.as_ana

[Analysis("how{carāng}{PRO}-PRS.1SG{-um}{V.AGR}"),
 Analysis("how{carāng}{PRO}-PRS.1PL{-ām}{V.AGR}"),
 Analysis("how{carāng}{PRO}-PRS.1PL{-ām}{V.AGR}")]

In [33]:
print(*results.as_glossing, sep="\n\n")

Xêr, yilāv bozi-en čūd xu, yā gāx̌t tar wi žindūrvak xu lůd-i: «A ǰůn, mund mu yičand bačā suδǰ, yāni duǰůn-um sic, ca meθ-ga wuz baɣer vārum, tām-ta mi bačā carāng-um?»
xêr	yi-lāv	bozi=en	čū-d	xu	yā	gāx̌-t	tar	wi	žindūrv-ak	xu	lů-d=i	a	ǰůn	mu=nd	mu	yi-čand	bačā	suδ-ǰ	yāni	duǰůn=um	si-c	ca	meθ=ga	wuz	baɣer	vār-um	tām=ta	mi	bačā	carāng-um
alright	INDEF-some	game=3PL	do-PST	COORD1	D3.F.SG	turn-PST	EQ	D3.M.SG.O	werewolf-DIM	COORD1	say-PST=3SG	VOC	soul	PRN.1SG.O=LOC	PRN.1SG.O	INDEF-few	child	become-PF.M.SG	that_is	pregnant=1SG	become-PF.F/PL	what	day=ADD1	PRN.1SG	maybe	bring-PRS.1SG	then=FUT	D1.M.SG.O	child	how-PRS.1SG
‘Вот они немного пошалили, и она сказала оборотню: «Душа моя, у меня теперь будет больше детей, я в положении и, наверное, мне скоро рожать, что мне с этим ребёнком делать?»’ [White mountain goat, 81]

Yu gāx̌t tar wam xu lůd-i: «Di bačā kor osůn-atā, tu ik-di lův idi, tu puc māš carāng-ām, cůnd-aθ-ta uz tarůd xu ǰoy-um?
yu	gāx̌-t	tar	wam	xu	lů-d=i	di	bačā	kor	osůn=atā	tu	ik=di	lův	idi	tu	puc	māš	carāng-ām	cůnd=aθ=ta	uz	tar-ůd	xu	ǰoy-um
D3.M.SG	turn-PST	EQ	D3.F.SG.O	COORD1	say-PST=3SG	D2.M.SG.O	child	work	easy=COORD3	PRN.2SG	EMPH=D2.M.SG.O	say.IMP	COMPL	PRN.2SG	son	PRN.1PL	how-PRS.1PL	how_much=INT=FUT	PRN.1SG	EQ-D1.LOC	REFL	place-PRS.1SG
‘Он ей ответил: «С ребёнком дело простое, а вот ты лучше скажи, что с твоим [старшим] сыном будем делать, сколько ещё мне тут прятаться?’ [White mountain goat, 82]

Xêr, yu ɣiδabuc xu naqli tayor čūd-atā, yam wi virod daδ-i wi pex̌st: «Carāng-ām?
xêr	yu	ɣiδa-buc	xu	naqli	tayor	čū-d=atā	yam	wi	virod	daδ=i	wi	pex̌s-t	carāng-ām
alright	D3.M.SG	boy-child.M	REFL	story	finished	do-PST=COORD3	D1.SG	D3.M.SG.O	brother	then=3SG	D3.M.SG.O	ask-PST	how-PRS.1PL
‘Вот мальчик свой рассказ закончил, и тогда брат его спросил: «Как же нам теперь быть?’ [White mountain goat, 161]

### Search token

You can search for individual tokens with the method `.search_token()`. This method can be called from a `cx.Corpus`, a `cx.Text` or a `cx.Sentence`.

Provide an argument `token` (the full phonological form of the token). It may contain regular expressions. The search will ignore case and punctuation marks on the sides of the token:

In [34]:
results = corpus.search_token(token="uz=um")
results

[Token("uz=um"),
 Token("Uz=um"),
 Token("Uz=um"),
 Token("uz=um"),
 Token("uz=um…"),
 Token("uz=um"),
 Token("uz=um"),
 Token("«Uz=um"),
 Token("uz=um"),
 Token("uz=um"),
 Token("uz=um"),
 Token("Uz=um"),
 Token("uz=um"),
 Token("uz=um"),
 Token("uz=um"),
 Token("uz=um"),
 Token("uz=um"),
 Token("uz=um"),
 Token("uz=um"),
 Token("uz=um"),
 Token("Uz=um"),
 Token("uz=um"),
 Token("Uz=um"),
 Token("uz=um"),
 Token("Uz=um"),
 Token("uz=um"),
 Token("uz=um"),
 Token("Uz=um"),
 Token("uz=um"),
 Token("Uz=um"),
 Token("Uz=um"),
 Token("Uz=um"),
 Token("Uz=um"),
 Token("Uz=um"),
 Token("uz=um"),
 Token("uz=um"),
 Token("uz=um"),
 Token("Uz=um"),
 Token("uz=um"),
 Token("uz=um"),
 Token("uz=um"),
 Token("uz=um"),
 Token("Uz=um"),
 Token("Uz=um"),
 Token("uz=um"),
 Token("uz=um"),
 Token("Uz=um"),
 Token("Uz=um"),
 Token("Uz=um"),
 Token("Uz=um"),
 Token("uz=um"),
 Token("uz=um"),
 Token("«uz=um"),
 Token("Uz=um"),
 Token("Uz=um"),
 Token("uz=um"),
 Token("uz=um"),
 Token("uz=um…"),
 Token("Uz=um"),
 Token("Uz=um"),
 Token("uz=um???"),
 Token("uz=um"),
 Token("uz=um"),
 Token("uz=um,"),
 Token("uz=um"),
 Token("Uz=um…"),
 Token("Uz=um"),
 Token("Uz=um…"),
 Token("uz=um"),
 Token("uz=um"),
 Token("uz=um"),
 Token("uz=um"),
 Token("uz=um"),
 Token("uz=um")]

If you want a search that is sensitive to case or punctuation, you can specify this in additional arguments:

In [35]:
results = corpus.search_token(token="Uz=um…", ignore_case=False, ignore_punct=False)
results

[Token("Uz=um…"),
 Token("Uz=um…")]

Alternatively, if you want an even more flexible search, you can specify that punctuation marks that denote morpheme boundaries should also be ignored. In that case, you can use a query with no morpheme boundaries and get results:

In [36]:
results = corpus.search_token(token="sutum", ignore_morphemes=True)
results

[Token("sut-um"),
 Token("Sut=um"),
 Token("sut=um"),
 Token("Su-t=um,"),
 Token("sut=um"),
 Token("Sut=um"),
 Token("sut=um")]

Results of token search are stored in an object of the type `cx.TokenSearch`, so you can view the results in the similar neat ways as `cx.MorphemeSearch` (see above):

In [37]:
results.as_sent

[Sentence("sut-um ark-ti-yum wīnt wam potx̌o rizīn."),
 Sentence("aro, sinf=i dāum tayor čūd, id mu amrogůn=en fukaθ toyd tar maktaben=i oli=at, mu=yen qāp δod xu, ārmiya askari. Sut=um askari ida ara solatā xoɣ̌ mêstum Toškand=and vedūši saldāt vud."),
 Sentence("aro, sut=um pi Škošum kanāl, yid... půnzdā rūz=um xu ɣ̌in xez=and nanūst xu, čila=yi zimistůn=and=um tūyd pi Šlošum kanāl"),
 Sentence("Su-t=um, se-yum imtiůn=ti=yum wêx̌-t."),
 Sentence("bād aro ik dis=ga sut=um sinfi ašt=atā mu yax maktab, mund mu yax padůd=i maktab x̌êyd nū=yat dā"),
 Sentence("Mi=ti wi=ti nay Xurram vo viručāt mu ču, box̌t=en mu padam. Sut=um padam, padam=um sut yak rūz=um sut tar masǰit, wev=qati=yum namoz xêyd."),
 Sentence("Bād=um uz wi namoz zox̌t māš, namoz rūsi=ti zox̌t=um wi xu sut=um tar cerkuv.")]

You can also get all unique analyses to get a generalized idea of the result:

In [38]:
results = corpus.search_token(token="čūɣ̌ǰat", ignore_morphemes=True)
results.analyses

[('do{čūɣ̌}{V}-PF{-ǰ}{T}-COORD2{=at}{CONJ}', 4),
 ('do{čūɣ̌}{V}-PF{-ǰ}{T}-PQP{-at}{T}', 2)]

### Search in a subcorpus

You can look for morphemes, morpheme chains or tokens in specific parts of the corpus. To do this, use the argument `text_filter` in a search to specify metadata values of texts. For each metadata category, you can specify one or several values that need to be included in the search:

In [39]:
results = corpus.search_token(token="nok.+", text_filter={
    "subcorpus": "Pear Film retellings"
})
results.as_sent

[Sentence("Čorik sifīnt pi daraxt xu, sar kix̌t ar xu futbolka noken ǰām čīdow."),
 Sentence("Yā=yi ik=disga lůd, nāla, aro… Sar yak sar ca sůd, yi čorik, ɣulā čorik pi daraxt noken ǰām kix̌t,"),
 Sentence("noken=ta ar xu… bīst ribīzd, disga ǰām=ta kix̌t=at, xāfct, ar sabad=ta wev garδent."),
 Sentence("dāδ ɣulādiyen wird kinen yordam, dev wi mūnen… dev noken ar wam sabadak ribiyen, senen=ta, bar ǰoy fuk kinen."),
 Sentence("Wi šilāp mis, ca wêx̌t, yā red. Wam=ga wird dāken, yu «qulluɣ» lůvd=xu, bād dākix̌t wevard noken=ga."),
 Sentence("Bād wāδ ɣal wev noken xen=atā, yaden ik=e=va, yu čorik ca xāvd,"),
 Sentence("noken xurd zex̌tow sabad=and xurd xīdow=ra."),
 Sentence("Bād azam=ti xāfct idi, daraxten… pi daraxt ca sifīnt, wev noken xurd ca zêzd, sabaden wi=ǰa, ara důnā."),
 Sentence("Disga yu ǰām kix̌t=at, ar yi sabad pur kix̌t, noken wam dākix̌t wird=atā, ar duyum xu, ar seyum xu, dākix̌t wird."),
 Sentence("At ar wam daraxt bun=en aro, cavor sabad, ɣulā sabaden ribūyǰin, yu ta az daraxt=ti xāfct, wev noken ta ar wev sabaden garδent=atā, wev ta… δuyůn=en yam=and pur=atā, yu=yi wam iga i lāv aram čūd xu, bād sifīd vo, vo sifīd pi wam daraxt."),
 Sentence("id bād ɣal ikam=and wi kāl=ti nūsč=atā arayga ɣiδābuc yaden, bād wāδ yi čīz=aθ napex̌cen xu sar=en wev noken ǰām čīd. Wev azam=and fuk δůven as wi sit=ti xu garδenen ar wam sabad xu aro ribiyen di...(background sound).. Wāδ disga rū pa rū yaden. wāδ as tagovaθ wāδ mis yaden anǰa yid azůd tīzd=at wāδ di rū pa rū yaden"),
 Sentence("Wam di=rd dākix̌t xu bād id ikdi=ec bād wev=ard nadākčūd nok=atā, idi wi šlyāpa yod xu bād yu ara důnā nok zêzd yu ɣulā ɣiδā xu, yoδd ta... ɣuladi, sof ɣulā nayat ɣuladi as wev xu amroen. Yoδd tar dev baǰgalā bucen xez xu sari dev dākix̌t dev=ard nok xu bād tiyen"),
 Sentence("Az daraxt=aθ divesen, yam=ti čorik ɣal pi narvůnd sifīδǰ xu, ɣal noken ǰām kix̌t. Yu noken ǰām kix̌t=at yīw az wi noken=and wox̌t. Yu bād xāfct, ar xu fārtukak kix̌t fanā noken ǰām xu, xāfct xu, ribīzd wev ar sabad, fāmt=at=o?"),
 Sentence("Az daraxt=aθ divesen, yam=ti čorik ɣal pi narvůnd sifīδǰ xu, ɣal noken ǰām kix̌t. Yu noken ǰām kix̌t=at yīw az wi noken=and wox̌t. Yu bād xāfct, ar xu fārtukak kix̌t fanā noken ǰām xu, xāfct xu, ribīzd wev ar sabad, fāmt=at=o?"),
 Sentence("Az daraxt=aθ divesen, yam=ti čorik ɣal pi narvůnd sifīδǰ xu, ɣal noken ǰām kix̌t. Yu noken ǰām kix̌t=at yīw az wi noken=and wox̌t. Yu bād xāfct, ar xu fārtukak kix̌t fanā noken ǰām xu, xāfct xu, ribīzd wev ar sabad, fāmt=at=o?"),
 Sentence("Az daraxt=aθ divesen, yam=ti čorik ɣal pi narvůnd sifīδǰ xu, ɣal noken ǰām kix̌t. Yu noken ǰām kix̌t=at yīw az wi noken=and wox̌t. Yu bād xāfct, ar xu fārtukak kix̌t fanā noken ǰām xu, xāfct xu, ribīzd wev ar sabad, fāmt=at=o?"),
 Sentence("Yu bād čost yamand=en noken xu, čost, yu čorik tar wi načost, xu velik lāk kix̌t xu, sůd, wev noken yi δu důnā zêzd. Bād čost, yu tar wi načost xu, wam celi sabad=qati zêzd. Ribīzd xu velik=ti xu, bād tīzd."),
 Sentence("Yu bād čost yamand=en noken xu, čost, yu čorik tar wi načost, xu velik lāk kix̌t xu, sůd, wev noken yi δu důnā zêzd. Bād čost, yu tar wi načost xu, wam celi sabad=qati zêzd. Ribīzd xu velik=ti xu, bād tīzd."),
 Sentence("Wind bād wi wux̌ sůd tar wam xu xu… Ůn, wi ɣiδabuc=and sůd wi wux̌ tar wam. Xu pīc garδent=atā, aro kix̌t pi čī… pi žīr=and xu, ǰukt xu, wind azed wi šlyāpa riwozd=atā, azed=ga xubaθ wox̌t az xu velik=ti, wāδ noken fukaθ sen yamard tis."),
 Sentence("Ik=di moment=and bād wi čorikak divesen. Yu xāfct az narvůnd=ti, čost, wi noken=en nist. Yu bād az wam… karočê pi wam žīr=and xu, ǰukt xu, wox̌t, wi noken fukaθ yamard sen tixīrm=atā, yamand sen peδo aray=ga ɣiδabuc."),
 Sentence("Ik=di moment=and bād wi čorikak divesen. Yu xāfct az narvůnd=ti, čost, wi noken=en nist. Yu bād az wam… karočê pi wam žīr=and xu, ǰukt xu, wox̌t, wi noken fukaθ yamard sen tixīrm=atā, yamand sen peδo aray=ga ɣiδabuc."),
 Sentence("Wāδ kinen wird yordam wev noken fukaθ ǰām čīdow, ī… poka waδ δuyůn az wevand yordam wird kinen abrātnê wam sabad pi wi velik sifent, yu yiga yak ɣal bozingārak=qati karočê bozi yamand kix̌t."),
 Sentence("Bād wāδ… Yu sifīnt pi xu velik, užê či tīdak sůd=at, wāδ mis či tīd sen=at, viriyen wi šlyāpa ik=am=and wêx̌čin, wam zen, dāken wird abrātnê, fīčen wird, lůven: ma… mam=at binêst karočê. Wam dāken wird abrātnê=yat, yu wevard dākix̌t noken quluɣ lůvd ǰāt."),
 Sentence("Yu bād kix̌t… Yu tīzd tar xu půnd=aǰ=atā, wāδ aray, wāδ aray nafar, yu kix̌t wevard noken bāx̌ xu, wāδ vo tiyen taram=aǰ. Wi čorik bād divesen, yu čost, wi yi sabad nist, xu sabaden isob kix̌t, yā yīw nist yamand. Yīw xoli=yat, yīw pur=at, yiga vabše nist."),
 Sentence("Yu bād xu yilāv noken kix̌t tis=atā, yu ɣal ik=am=and xu sabaden isob kix̌t=at, daδ aray ɣiδā wi piro wa naɣ̌ǰīsen, noken xen=at, naɣ̌ǰīsen. Yu bād sůd ayrůn=aθ karočê, dis=ga dakancā yak tar wev čost=at, wāδ rostow prosta wi piro wa naɣ̌ǰīsen xu, tiyen."),
 Sentence("Yu bād xu yilāv noken kix̌t tis=atā, yu ɣal ik=am=and xu sabaden isob kix̌t=at, daδ aray ɣiδā wi piro wa naɣ̌ǰīsen, noken xen=at, naɣ̌ǰīsen. Yu bād sůd ayrůn=aθ karočê, dis=ga dakancā yak tar wev čost=at, wāδ rostow prosta wi piro wa naɣ̌ǰīsen xu, tiyen."),
 Sentence("Dev mūnen=i fuk ar sabad lāk čūd xu, bād sifīd=o? …Nu ik=dāδ noken."),
 Sentence("Nāy, yam=and ik=dis=ga ačaθ navud, aro yu mi=ti qarorikaθ, spakoynikaθ xāvd, wi noken nist.")]

In [40]:
results = corpus.search_morpheme(gloss="brother.*", text_filter={
    "subcorpus": ["Oral texts (old recordings)", "Texts (Zarubin 1960)"]
})
results.as_ana

[Analysis("brother{virod}{N}-3PL{=en}{CL.AGR}"),
 Analysis("brother{virod}{N}-3PL{=en}{CL.AGR}"),
 Analysis("brother.PL{virodār}{N}-3PL{=en}{CL.AGR}"),
 Analysis("brother{viro}{N}"),
 Analysis("brother{viro}{N}"),
 Analysis("brother{viro}{N}"),
 Analysis("brother.PL{virodār}{N}-PL{=en}{N.AFF}"),
 Analysis("brother{viro}{N}"),
 Analysis("brother.PL{virodār}{N}-3PL{=en}{CL.AGR}")]

You can look up metadata values using a `cx.Corpus` method `.meta_values()`:

In [41]:
corpus.meta_values(key="subcorpus")

Counter({'Oral texts (modern recordings)': 31,
         'Stories (Alamshoev 1994)': 14,
         'Gospel of Luke': 12,
         'Folklore texts (Folklori Pomir)': 10,
         'Legends (Alamshoev 1994)': 8,
         'Tales (Alamshoev 1994)': 8,
         'Pear Film retellings': 7,
         'Archive of handwritten texts of the Institute of Humanities, Kharagh': 6,
         'Sentences': 2,
         'Dialogues (Codebreaker)': 2,
         'Idioms (Alamshoev 1994)': 1,
         'Song lyrics (Alamshoev 1994)': 1,
         'Proverbs (Alamshoev 1994)': 1,
         'Riddles (Alamshoev 1994)': 1,
         'Interviews (Lidush Habib)': 1,
         'Dialogues (interview experiment)': 1,
         'Oral texts (old recordings)': 1,
         'Texts (Zarubin 1960)': 1})

For example, let us compare the frequency of the Russian word *što* ‘what’ in texts of different periods (unfortunately, only for texts for which the exact year of creation is known):

In [42]:
corpus.meta_values(key="year")

Counter({1987: 18,
         2001: 12,
         2019: 12,
         2021: 9,
         1989: 6,
         2023: 6,
         2018: 5,
         1980: 3,
         2024: 3,
         '1960–1992': 3,
         1988: 2,
         2022: 2,
         '1980–1990': 1,
         1993: 1,
         1991: 1,
         1985: 1,
         1958: 1,
         2012: 1,
         '2018–2021': 1,
         '2021–2023': 1,
         2017: 1,
         '1950–1980 (?)': 1,
         1915: 1})

In [43]:
results = corpus.search_morpheme(morph="što", text_filter={
    "year": list(range(1910, 1960))
})
results.as_sent

[]

In [44]:
results = corpus.search_morpheme(morph="što", text_filter={
    "year": list(range(2010, 2026))
})
results.as_sent

[Sentence("At abor šič čis yůdand ca, yůdand tīpa go yīw, at māδ=en ar varθ yůdand, māš ši di kinām fikri, što māδ=en ar varθ rost."),
 Sentence("Čis ši māš yůdand=o… mi=ti=yen māδ ca, ar varθ. Māš fikri kinām… yůdand nêδǰin, što yůdand yīw az dev=and rost."),
 Sentence("Зато fāmām taš, što dāδ=en yi cvet nêδǰin nist=o…"),
 Sentence("ī… yed=and bād tayor sut; prosto uz čurt δām, što aro,"),
 Sentence("yu… yu ɣiδā=yi, ik=u… čorik=i az mev bačgala wīnt, što dāδ=en wi kayůn cift."),
 Sentence("yid vud ponzdā sol tar piro, yāyi ɣ̌iniki bād xūδmand wīnt što arčiz ar dek ǰoyak ca"),
 Sentence("yu bād beδǰ, bāden fuk lůvǰ što yu pi arčidům ca qišloq"),
 Sentence("bād xubaθ at yāyi xubaθ ožidat' naču što yā tāš dis-ga lůvd, yāyi nafāmt, yā taš dis-ga lůvdat yāyi wam tar cem yat"),
 Sentence("yāyi bād fāmt što yid pari"),
 Sentence("yā pari bād wamard lůvd, što čiz tipa tuat disga mu ca čux̌t")]

## Export

### Export search results to `csv`

To export search results to a new `csv` file, first export them into a `pandas` dataframe and then call method `.to_csv()` from this dataframe:

In [45]:
df = results.to_df()
df.to_csv("name_for_new_table.csv", index=False)

### Export corpus to `csv`

You can export the full corpus into a (quite large!) `csv` file. It will contain all texts, sentences, tokens and morphemes. To do it, call the method `.to_df()` from your `cx.Corpus` and then export the resulting dataframe into `csv`:

In [46]:
full_df = corpus.to_df()
# full_df.to_csv("name_for_full_corpus_table.csv", index=False)

In [47]:
full_df.head()

,sent_id,sentence,morphs,glosses,pos,translation,subcorpus,text.title,text.filename,text.author,text.year
0,1,"ar cem ca deδi, na x̌êθi",ar cem ca deδ-i na x̌êθ-i,DOWN eye SUBD1 enter-PRS.2SG NEG spare-PRS.2SG,PREP N CONJ V-V.AGR V.AFF -V.AGR,"He мешаешь, любимчик",Idioms (Alamshoev 1994),Idioms (Alamshoev 1994),sgh_alamshoev_Idioms.eaf,,
1,2,"tu-t mu xez dis noziyůn yast idi, ar cem ca de...",tu=t mu xez dis noziyůn yast idi ar cem ca deδ...,PRN.2SG=2SG PRN.1SG.O APUD such darling there_...,PERS=CL.AGR PERS POST PRO V CONJ PREP N CONJ ...,"Ты мне являешься таким любимым, что никогда мн...",Idioms (Alamshoev 1994),Idioms (Alamshoev 1994),sgh_alamshoev_Idioms.eaf,,
2,3,as xu taramaki čīdow,as xu tar-am-aki čī-d-ow,EL REFL EQ-D3.LOC-ADV do-INF-PURP,PREP PRO PREP-DEM.LOC- V-NMLZ-NMLZ,"Спустя рукава, выполнять кое-как",Idioms (Alamshoev 1994),Idioms (Alamshoev 1994),sgh_alamshoev_Idioms.eaf,,
3,4,"Xotūn lap arůmkor, yā as xu taramaki kor kix̌t",Xotūn lap arůmkor yā as xu tar-am-aki kor kix̌-t,Khotun much dishonestly working D3.F.SG EL REF...,PRT DEM PREP PRO PREP-DEM.LOC- N V-V.AGR,"Хотун очень плохо работает, она выполняет рабо...",Idioms (Alamshoev 1994),Idioms (Alamshoev 1994),sgh_alamshoev_Idioms.eaf,,
4,5,as mu karak xato,as mu _ xato,EL PRN.1SG.O _ wrong,PREP PERS _ N,"Поздно, конец, всё",Idioms (Alamshoev 1994),Idioms (Alamshoev 1994),sgh_alamshoev_Idioms.eaf,,

### Export subcorpus or individual text to `csv`

You can export a certain subcorpus easily if you create a dataframe with all texts (see above) and then use `pandas` to filter out certain values of metadata categories:

In [48]:
legends_df = full_df[full_df.subcorpus == "Legends (Alamshoev 1994)"]
legends_df

,sent_id,sentence,morphs,glosses,pos,translation,subcorpus,text.title,text.filename,text.author,text.year
45,1,awal yůdand yiθč Xūǰayi Xizr.,awal yůd=and yiθ-č Xūǰayi Xizr,beginning D1.LOC=LOC come-PF Khujayi Khizr,DEM.LOC=POST V-T,Сначала сюда прибыл Ходжи Хизр.,Legends (Alamshoev 1994),Imam,sgh_alamshoev_legend_Imam.eaf,"Аловатов Азизбек, 1915 г.р.",1988
46,2,yedand nūsč ba namoz.,yed=and nūs-č ba namoz,D2.LOC=LOC sit.M.SG-PF ALL namaz,DEM.LOC=POST V-T PREP N,Здесь он совершил намаз.,Legends (Alamshoev 1994),Imam,sgh_alamshoev_legend_Imam.eaf,"Аловатов Азизбек, 1915 г.р.",1988
47,3,bād as di yatow yid isob sut qadamgo.,bād as di ya-t-ow yid isob su-t _,after EL D2.M.SG.O come-PST-PURP D2.SG account...,N PREP DEM V-T-NMLZ DEM N V-T _,После этого оно считалось священным местом.,Legends (Alamshoev 1994),Imam,sgh_alamshoev_legend_Imam.eaf,"Аловатов Азизбек, 1915 г.р.",1988
48,4,"čandīn waxt-ga naɣ̌ǰīd-at, yīw as yulůmeni po...",čandīn waxt-ga naɣ̌ǰī-d=at yīw as ɣulům-en=i ...,several time-ADD1 pass-PST=COORD2 one EL serva...,N-PRT V-T=CONJ NUM PREP N-N.AFF=CL.AGR N-POST...,Прошло несколько времени и один из рабов Бухар...,Legends (Alamshoev 1994),Imam,sgh_alamshoev_legend_Imam.eaf,"Аловатов Азизбек, 1915 г.р.",1988
49,5,"xūδm-and ukmat wi-rd sut idi, sāw kūyistůn-and...",xūδm=and ukm=at wi=rd su-t idi sāw kūyistůn=an...,sleep=LOC order=COORD2 D3.M.SG.O=DAT go.M.SG-P...,N=POST N=CONJ DEM=POST V-T CONJ V =POST N V,"Во сне ему было приказано, чтобы он поехал в с...",Legends (Alamshoev 1994),Imam,sgh_alamshoev_legend_Imam.eaf,"Аловатов Азизбек, 1915 г.р.",1988
...,...,...,...,...,...,...,...,...,...,...,...
162,5,wi čīd-and-en δu sāvʒpūx̌ barǰoy vic.,wi čīd=and=en δu sāvʒ-pūx̌ bar-ǰoy vi-c,D3.M.SG.O house=LOC=3PL two green-dressed ALL-...,DEM N=POST=CL.AGR NUM - PREP-N V-T,В его доме жили двое одетых в зеленом.,Legends (Alamshoev 1994),Two people in green,sgh_alamshoev_legend_Two_people_in_green.eaf,"Мирзовафоев Бекдавлат, 1914 г.р.",1993
163,6,yi meθ-i yu Qozi Rustam yi yulům xu-nd xax̌ az...,yi meθ=i yu Qozi Rustam yi ɣulům xu=nd xax̌ az...,one day=3SG D3.M.SG Qozi Rustam one servant RE...,NUM N=CL.AGR DEM NUM N PRO=POST N V-T,Однажды тот Кози Рустам сильно избивает одного...,Legends (Alamshoev 1994),Two people in green,sgh_alamshoev_legend_Two_people_in_green.eaf,"Мирзовафоев Бекдавлат, 1914 г.р.",1993
164,7,daδ wi xūn ikumard sůd.,daδ wi xūn ik=um=ard sů-d,then D3.M.SG.O blood EMPH=D3.LOC=DAT become-PR...,PRT DEM N PRT=DEM.LOC=POST V-V.AGR,Там пролилась его кровь.,Legends (Alamshoev 1994),Two people in green,sgh_alamshoev_legend_Two_people_in_green.eaf,"Мирзовафоев Бекдавлат, 1914 г.р.",1993
165,8,daδ dāδ sāvʒpūx̌en sen malol xu as wi čīd-and ...,daδ dāδ sāvʒ-pūx̌-en s-en malol xu as wi čīd=a...,then D2.PL green-dressed-PL become-PRS.3PL emb...,PRT DEM -N-N.AFF V-V.AGR CONJ PREP DEM N=POST...,Потом те одетые в зеленом огорчаются и ушли из...,Legends (Alamshoev 1994),Two people in green,sgh_alamshoev_legend_Two_people_in_green.eaf,"Мирзовафоев Бекдавлат, 1914 г.р.",1993
166,9,xu tīdow-and zůɣ kin-en: - nogin as yi xůnā xu...,xu tī-d-ow=and zůɣ kin-en _ nogin as yi xůnā x...,COORD1 leave-INF-PURP=LOC spell do-PRS.3PL _ h...,CONJ V-NMLZ-NMLZ=POST V-V.AGR _ PRT PREP NUM ...,"Перед тем как уйти, проклинали: - Чтобы Бог ва...",Legends (Alamshoev 1994),Two people in green,sgh_alamshoev_legend_Two_people_in_green.eaf,"Мирзовафоев Бекдавлат, 1914 г.р.",1993

Similarly, to export one text, you can call `.to_df()` from a `cx.Text` object.

In [49]:
three_brothers_df = text.to_df()
three_brothers_df.head()

,sent_id,sentence,morphs,glosses,pos,translation,subcorpus,text.title,text.filename,text.author,text.year
0,1,Tu nům čāy?,tu nům čāy,PRN.2SG name who,PERS N PRO,Как тебя зовут?,Dialogues (interview experiment),Interview experiment (SN72 & NR75),sgh_txt_interview_SN72_NR75.eaf,"SN72, NR75",2024
1,2,"Xob, Šālo, tu Xaraɣ=and zindagi kini=yo?",xob Šālo tu Xaraɣ=and zindagi kin-i=yo,well Shahlo PRN.2SG Kharagh=LOC life do-PRS.2SG=Q,N NPROP PERS NPROP=POST N V-V.AGR=PRT,"Хорошо, Шахло, ты живёшь в Хороге?",Dialogues (interview experiment),Interview experiment (SN72 & NR75),sgh_txt_interview_SN72_NR75.eaf,"SN72, NR75",2024
2,3,Turd… sar xuš čīz? Turd čīz lapdi xuš?,tu-rd sar xuš čīz tu-rd čīz lap-di xuš,PRN.2SG-DAT most happy thing PRN.2SG-DAT thing...,PERS-POST N N PRO PERS-POST PRO N-N.AFF N,Тебе… что больше всего нравится? Тебе что боль...,Dialogues (interview experiment),Interview experiment (SN72 & NR75),sgh_txt_interview_SN72_NR75.eaf,"SN72, NR75",2024
3,4,Zimistůn=o tobistůn?,zimistůn=o tobistůn,winter=OR summer,N=CONJ N,Зима или лето?,Dialogues (interview experiment),Interview experiment (SN72 & NR75),sgh_txt_interview_SN72_NR75.eaf,"SN72, NR75",2024
4,5,Tu=t ca waxt as nān sic?,tu=t ca waxt as nān si-c,PRN.2SG=2SG what time EL mother become-PF.F/PL,PERS=CL.AGR PRO N PREP N V-T,Когда ты родилась?,Dialogues (interview experiment),Interview experiment (SN72 & NR75),sgh_txt_interview_SN72_NR75.eaf,"SN72, NR75",2024

### Export text to other formats

You can export a `cx.Text` to other formats. Crucially, it is possible to export them to Tsakorpus-formatted `json` or to the standard `eaf` for ELAN:

In [50]:
text.to_json()
text.to_eaf()

Method `.to_print()` will print the text sentence by sentence, with translations if there are any.

In [51]:
print(text.to_print())

Tu nům čāy?
‘Как тебя зовут?’

Mund nům Šālo.
‘Меня зовут Шахло.’

Xob, Šālo, tu Xaraɣ=and zindagi kini=yo?
‘Хорошо, Шахло, ты живёшь в Хороге?’

Ůn, uz Xaraɣ=and zindagi kinum.
‘Да, я живу в Хороге.’

Turd… sar xuš čīz? Turd čīz lapdi xuš?
‘Тебе… что больше всего нравится? Тебе что больше нравится?’

Zimistůn=o tobistůn?
‘Зима или лето?’

Uz=um ām zimistůn žīwǰ=at, ām tobistůn=atā, baɣer tobistůn, lap xax̌ gārm māvid=atā, tobistůn murd xuš.
‘Мне нравятся и зима, и лето, но, вероятно, [больше] лето, [когда] не слишком жарко, мне нравится лето.’

Tu=t ca waxt as nān sic?
‘Когда ты родилась?’

Uz=um māy=and. Sar xušrūy fasli sol=and.
‘Я [родилась] в мае. В самое прекрасное время года.’

Sar xušrūy fasli sol=and.
‘В самое прекрасное время года.’

Xob…
‘Хорошо…’

Yůd=and sol darkor idi, tu=t ca waxt as nān sic.
‘Здесь нужен год, когда ты родилась.’

Tu=t ca waxt as nān siс?
‘Когда ты родилась?’

Uz=um bīstumi māy azor=u nowsad=u aftod=u duyum sol=and as nān sat.
‘Я родилась двадцатого мая 1972 года.’

Tu=t pas… māšand šič panǰo=wu du solā=yo?
‘Значит, тебе сейчас пятьдесят два года?’

Panǰo=wu du solā.
‘Пятьдесят два года.’

Panǰo=wu du solā=yat. Uz=um aǰab rost isob čūɣ̌ǰ.
‘Тебе пятьдесят два года. Я подсчитала удивительно точно.’

Tu=t nur sāraki čīz xūd?
‘Что ты ела сегодня утром?’

Uz=um nur sāraki… šīrčoy birox̌t.
‘Я сегодня утром … пила ширчай.’

Maskā=yat garδā=qati.
‘С маслом и хлебом.’

Xob. Šič ku tared borůn δed=o?
‘Понятно. Ну-ка, а сейчас идёт дождь?’

Borůn δed, ůn.
‘Дождь идёт, да.’

Sāraki dūsik δod=atā…
‘Утром [дождь] немного покапал, и …’

Šič x̌o mis ɣal δed.
‘Сейчас, наверное, он всё ещё идёт.’

E modar, uz=um rinux̌t tu nům čāy.
‘Ой, матушка, я забыла твоё имя.’

Šālo mu nům, yāxik.
‘Меня зовут Шахло, сестра.’

Tund aro… Sar bašānd ox̌no yast=o?
‘У тебя… Есть лучший друг?’

Mund=en yast ox̌nogůn, но māš lap yakdigar=qati nawinām=atā, ну disga yast=en ox̌noyen.
‘У меня есть друзья, но мы нечасто видимся, ну a так друзья есть.’

Ox̌noyen=en… dāδ=en mardīnā=yo ɣ̌inik?
‘[Эти] друзья… они мужчины или женщины?’

Kaxoyen, yu mardīnā kāy?
‘[Это] женщины, где эти мужчины?’

Tu…
‘Ты…’

Tu=t as dev sozindāyen=and sar lap či žīwǰ?
‘Кого из музыкантов ты любишь больше всего?’

Uz=um Āmad Zoir lаp žīwǰ.
‘Я очень люблю Ахмада Зохира.’

Āmad Zoir=at lap žīwǰ.
‘Очень любишь Ахмада Зохира.’

As cůnd solagi=yand Āmad Zoir niɣůɣ̌i?
‘С какого возраста ты слушаешь Ахмада Зохира?’

Āmad Zoir uz mumkin az di aždāsolagi=ndi niɣůɣ̌um, doyim=um lapdi niɣux̌t=at, dūs=ga šič kamdi vo waxt nist.
‘Ахмада Зохира я слушаю, наверное, с восемнадцати лет, раньше больше слушала, а сейчас уже меньше, нет времени.’

At as mev… mi ǰoyi mardum=and čāy turd sar xuš?
‘А из местных тебе кто нравится больше всего?’

Az mi ǰoyi mardum=and, az mi ǰoyi mardum=and…
‘Из местных, из местных…’

Qīn lůvdow=atā… Mumkin Liduš murd xuš.
‘Сложно сказать, но… Наверное, мне нравится Лидуш.’

Vud когда_то lap=aθ xuš=atā, šič mis niɣůɣ̌um, yakbori.
‘Очень нравился когда-то, но сейчас тоже иногда слушаю.’

At Saši Zaifi?
‘А Саши Заифи?’

Nay, Saši Zaifi=yum nažīwǰ.
‘Нет, не люблю Саши Заифи.’

Čīzard=at nažīwǰ?
‘Почему не любишь?’

Saši Zaifi xoyix̌ kix̌t Liduš=ard… taqlīd čīdow.
‘Саши Заифи хочет… подражать Лидушу.’

Ammo wind důnd xax̌… bašānd yu nasůd.
‘Но у него это так… он не [так] хорош [в этом].’

Bašānd navārδed taqlīd wird čīdow.
‘Не очень хорошо умеет подражать ему.’

Tu fikri=qati čīzard?
‘По-твоему, почему?’

Mu fikri=qati, taqlīd boyad mākix̌t=at, boyad ar čīz wind ca yast, ik=wi nix̌ůn δīd.
‘По-моему, он должен не подражать [Лидушу], а показывать, что есть у него самого.’

At wi xuɣ̌nůni ziv cůndik bašānd?
‘А его шугнанский насколько хорош?’

Wi xuɣ̌nůni ziv… bašānd=o gandā, lůvdow navārδīm.
‘Его шугнанский язык… Хороший или плохой — не могу сказать.’

Ammo wi sozen māno, důnd xax̌ bašānd nist.
‘Но значение его песен не очень хорошее.’

Qulluɣi bisyor.
‘Спасибо большое.’

Method `.to_latex()` will export the text into glossed examples for the LaTeX library `expex`:

In [52]:
print(text.to_latex())

\pex<ex1>
\begingl
\gla Tu nům čāy? //
\glb tu nům čāy //
\glc PRN.2SG name who //
\glft ‘Как тебя зовут?’ //
\endgl \xe

\pex<ex2>
\begingl
\gla Xob, Šālo, tu Xaraɣ=and zindagi kini=yo? //
\glb xob Šālo tu Xaraɣ=and zindagi kin-i=yo //
\glc well Shahlo PRN.2SG Kharagh=LOC life do-PRS.2SG=Q //
\glft ‘Хорошо, Шахло, ты живёшь в Хороге?’ //
\endgl \xe

\pex<ex3>
\begingl
\gla Turd… sar xuš čīz? Turd čīz lapdi xuš? //
\glb tu-rd sar xuš čīz tu-rd čīz lap-di xuš //
\glc PRN.2SG-DAT most happy thing PRN.2SG-DAT thing much-COMP happy //
\glft ‘Тебе… что больше всего нравится? Тебе что больше нравится?’ //
\endgl \xe

\pex<ex4>
\begingl
\gla Zimistůn=o tobistůn? //
\glb zimistůn=o tobistůn //
\glc winter=OR summer //
\glft ‘Зима или лето?’ //
\endgl \xe

\pex<ex5>
\begingl
\gla Tu=t ca waxt as nān sic? //
\glb tu=t ca waxt as nān si-c //
\glc PRN.2SG=2SG what time EL mother become-PF.F/PL //
\glft ‘Когда ты родилась?’ //
\endgl \xe

\pex<ex6>
\begingl
\gla Sar xušrūy fasli sol=and. //
\glb sar xušrūy fasli sol=and //
\glc most beautiful season year=LOC //
\glft ‘В самое прекрасное время года.’ //
\endgl \xe

\pex<ex7>
\begingl
\gla Xob… //
\glb xob //
\glc well //
\glft ‘Хорошо…’ //
\endgl \xe

\pex<ex8>
\begingl
\gla Yůd=and sol darkor idi, tu=t ca waxt as nān sic. //
\glb yůd=and sol darkor idi tu=t ca waxt as nān si-c //
\glc D1.LOC=LOC year necessary COMPL PRN.2SG=2SG what time EL mother become-PF.F/PL //
\glft ‘Здесь нужен год, когда ты родилась.’ //
\endgl \xe

\pex<ex9>
\begingl
\gla Tu=t ca waxt as nān siс? //
\glb tu=t ca waxt as nān si-с //
\glc PRN.2SG=2SG what time EL mother become-PF.F/PL //
\glft ‘Когда ты родилась?’ //
\endgl \xe

\pex<ex10>
\begingl
\gla Tu=t pas… māšand šič panǰo=wu du solā=yo? //
\glb tu=t pas māš-and šič panǰo=wu du sol-ā=yo //
\glc PRN.2SG=2SG therefore PRN.1PL-LOC now fifty=COORD3 two year-HB=Q //
\glft ‘Значит, тебе сейчас пятьдесят два года?’ //
\endgl \xe

\pex<ex11>
\begingl
\gla Panǰo=wu du solā=yat. Uz=um aǰab rost isob čūɣ̌ǰ. //
\glb panǰo=wu du sol-ā=yat uz=um aǰab rost isob čūɣ̌-ǰ //
\glc fifty=COORD3 two year-HB=2SG PRN.1SG=1SG astonishing right account do-PF //
\glft ‘Тебе пятьдесят два года. Я подсчитала удивительно точно.’ //
\endgl \xe

\pex<ex12>
\begingl
\gla Tu=t nur sāraki čīz xūd? //
\glb tu=t nur sāraki čīz xū-d //
\glc PRN.2SG=2SG today morning thing eat-PST //
\glft ‘Что ты ела сегодня утром?’ //
\endgl \xe

\pex<ex13>
\begingl
\gla Xob. Šič ku tared borůn δed=o? //
\glb xob šič ku tar-ed borůn δe-d=o //
\glc well now PTCL EQ-D2.LOC rain fall-PRS.3SG=Q //
\glft ‘Понятно. Ну-ка, а сейчас идёт дождь?’ //
\endgl \xe

\pex<ex14>
\begingl
\gla E modar, uz=um rinux̌t tu nům čāy. //
\glb e modar uz=um rinux̌-t tu nům čāy //
\glc VOC mother PRN.1SG=1SG forget-PST PRN.2SG name who //
\glft ‘Ой, матушка, я забыла твоё имя.’ //
\endgl \xe

\pex<ex15>
\begingl
\gla Tund aro… Sar bašānd ox̌no yast=o? //
\glb tu-nd aro sar bašānd ox̌no yast=o //
\glc PRN.2SG-LOC ADR most good friend there\_is=Q //
\glft ‘У тебя… Есть лучший друг?’ //
\endgl \xe

\pex<ex16>
\begingl
\gla Ox̌noyen=en… dāδ=en mardīnā=yo ɣ̌inik? //
\glb ox̌no-yen=en dāδ=en mardīnā=yo ɣ̌inik //
\glc friend-PL=3PL D2.PL=3PL man=OR woman //
\glft ‘[Эти] друзья… они мужчины или женщины?’ //
\endgl \xe

\pex<ex17>
\begingl
\gla Tu… //
\glb tu //
\glc PRN.2SG //
\glft ‘Ты…’ //
\endgl \xe

\pex<ex18>
\begingl
\gla Tu=t as dev sozindāyen=and sar lap či žīwǰ? //
\glb tu=t as dev sozindā-yen=and sar lap či žīwǰ //
\glc PRN.2SG=2SG EL D2.PL.O musician-PL=LOC most much who.O love.PF //
\glft ‘Кого из музыкантов ты любишь больше всего?’ //
\endgl \xe

\pex<ex19>
\begingl
\gla Āmad Zoir=at lap žīwǰ. //
\glb Āmad Zoir=at lap žīwǰ //
\glc Ahmad Zohir=2SG much love.PF //
\glft ‘Очень любишь Ахмада Зохира.’ //
\endgl \xe

\pex<ex20>
\begingl
\gla As cůnd solagi=yand Āmad Zoir niɣůɣ̌i? //
\glb as cůnd sol-agi=yand Āmad Zoir niɣůɣ̌-i //
\glc EL how\_much year-ABSTR=LOC Ahmad Zohir listen-PRS.2SG //
\glft ‘С какого возраста ты слушаешь Ахмада Зохира?’ //
\endgl \xe

\pex<ex21>
\begingl
\gla At as mev… mi ǰoyi mardum=and čāy turd sar xuš? //
\glb at as mev mi ǰoy-i mardum=and čāy tu-rd sar xuš //
\glc COORD2 EL D1.PL.O D1.M.SG.O place-ADJ people=LOC who PRN.2SG-DAT most happy //
\glft ‘А из местных тебе кто нравится больше всего?’ //
\endgl \xe

\pex<ex22>
\begingl
\gla At Saši Zaifi? //
\glb at Saši Zaifi //
\glc COORD2 Sashi Zaifi //
\glft ‘А Саши Заифи?’ //
\endgl \xe

\pex<ex23>
\begingl
\gla Čīzard=at nažīwǰ? //
\glb čīzard=at na-žīwǰ //
\glc why=2SG NEG-love.PF //
\glft ‘Почему не любишь?’ //
\endgl \xe

\pex<ex24>
\begingl
\gla Tu fikri=qati čīzard? //
\glb tu fikri=qati čīzard //
\glc PRN.2SG thought=COM why //
\glft ‘По-твоему, почему?’ //
\endgl \xe

\pex<ex25>
\begingl
\gla At wi xuɣ̌nůni ziv cůndik bašānd? //
\glb at wi xuɣ̌nůn-i ziv cůnd-ik bašānd //
\glc COORD2 D3.M.SG.O Shughnan-ADJ language how\_much-DIM good //
\glft ‘А его шугнанский насколько хорош?’ //
\endgl \xe

\pex<ex26>
\begingl
\gla Qulluɣi bisyor. //
\glb qulluɣ-i bisyor //
\glc thanks-EZ much //
\glft ‘Спасибо большое.’ //
\endgl \xe

\pex<ex27>
\begingl
\gla Mund nům Šālo. //
\glb mu-nd nům Šālo //
\glc PRN.1SG.O-LOC name Shahlo //
\glft ‘Меня зовут Шахло.’ //
\endgl \xe

\pex<ex28>
\begingl
\gla Ůn, uz Xaraɣ=and zindagi kinum. //
\glb ůn uz Xaraɣ=and zindagi kin-um //
\glc yes PRN.1SG Kharagh=LOC life do-PRS.1SG //
\glft ‘Да, я живу в Хороге.’ //
\endgl \xe

\pex<ex29>
\begingl
\gla Uz=um ām zimistůn žīwǰ=at, ām tobistůn=atā, baɣer tobistůn, lap xax̌ gārm māvid=atā, tobistůn murd xuš. //
\glb uz=um ām zimistůn žīwǰ=at ām tobistůn=atā baɣer tobistůn lap xax̌ gārm mā-vi-d=atā tobistůn mu-rd xuš //
\glc PRN.1SG=1SG COORD5 winter love.PF=COORD2 COORD5 summer=COORD3 maybe summer much very hot NEG.IRR-be-PRS.3SG=COORD3 summer PRN.1SG.O-DAT happy //
\glft ‘Мне нравятся и зима, и лето, но, вероятно, [больше] лето, [когда] не слишком жарко, мне нравится лето.’ //
\endgl \xe

\pex<ex30>
\begingl
\gla Uz=um māy=and. Sar xušrūy fasli sol=and. //
\glb uz=um māy=and sar xušrūy fasli sol=and //
\glc PRN.1SG=1SG May=LOC most beautiful season year=LOC //
\glft ‘Я [родилась] в мае. В самое прекрасное время года.’ //
\endgl \xe

\pex<ex31>
\begingl
\gla Uz=um bīstumi māy azor=u nowsad=u aftod=u duyum sol=and as nān sat. //
\glb uz=um bīst-um-i māy azor=u now-sad=u aftod=u du-yum sol=and as nān sa-t //
\glc PRN.1SG=1SG twenty-ORD-EZ May thousand=COORD3 nine-hundred=COORD3 seventy=COORD3 two-ORD year=LOC EL mother become.F/PL-PST //
\glft ‘Я родилась двадцатого мая 1972 года.’ //
\endgl \xe

\pex<ex32>
\begingl
\gla Panǰo=wu du solā. //
\glb panǰo=wu du sol-ā //
\glc fifty=COORD3 two year-HB //
\glft ‘Пятьдесят два года.’ //
\endgl \xe

\pex<ex33>
\begingl
\gla Uz=um nur sāraki… šīrčoy birox̌t. //
\glb uz=um nur sāraki šīrčoy birox̌-t //
\glc PRN.1SG=1SG today morning shirchoy drink-PST //
\glft ‘Я сегодня утром … пила ширчай.’ //
\endgl \xe

\pex<ex34>
\begingl
\gla Maskā=yat garδā=qati. //
\glb maskā=yat garδā=qati //
\glc butter=COORD2 bread=COM //
\glft ‘С маслом и хлебом.’ //
\endgl \xe

\pex<ex35>
\begingl
\gla Borůn δed, ůn. //
\glb borůn δe-d ůn //
\glc rain fall-PRS.3SG yes //
\glft ‘Дождь идёт, да.’ //
\endgl \xe

\pex<ex36>
\begingl
\gla Sāraki dūsik δod=atā… //
\glb sāraki dūs-ik δo-d=atā //
\glc morning a\_little-DIM fall-PST=COORD3 //
\glft ‘Утром [дождь] немного покапал, и …’ //
\endgl \xe

\pex<ex37>
\begingl
\gla Šič x̌o mis ɣal δed. //
\glb šič x̌o mis ɣal δe-d //
\glc now turns\_out ADD2 still fall-PRS.3SG //
\glft ‘Сейчас, наверное, он всё ещё идёт.’ //
\endgl \xe

\pex<ex38>
\begingl
\gla Šālo mu nům, yāxik. //
\glb Šālo mu nům yāx-ik //
\glc Shahlo PRN.1SG.O name sister-DIM //
\glft ‘Меня зовут Шахло, сестра.’ //
\endgl \xe

\pex<ex39>
\begingl
\gla Mund=en yast ox̌nogůn, но māš lap yakdigar=qati nawinām=atā, ну disga yast=en ox̌noyen. //
\glb mu-nd=en yast ox̌no-gůn но māš lap yakdigar=qati na-win-ām=atā ну disga yast=en ox̌no-yen //
\glc PRN.1SG.O-LOC=3PL there\_is friend-PL but PRN.1PL much RECP=COM NEG-see-PRS.1PL=COORD3 well such there\_is=3PL friend-PL //
\glft ‘У меня есть друзья, но мы нечасто видимся, ну a так друзья есть.’ //
\endgl \xe

\pex<ex40>
\begingl
\gla Kaxoyen, yu mardīnā kāy? //
\glb kaxoy-en yu mardīnā kāy //
\glc woman-PL D3.M.SG man where //
\glft ‘[Это] женщины, где эти мужчины?’ //
\endgl \xe

\pex<ex41>
\begingl
\gla Uz=um Āmad Zoir lаp žīwǰ. //
\glb uz=um Āmad Zoir lаp žīwǰ //
\glc PRN.1SG=1SG Ahmad Zohir much love.PF //
\glft ‘Я очень люблю Ахмада Зохира.’ //
\endgl \xe

\pex<ex42>
\begingl
\gla Āmad Zoir uz mumkin az di aždāsolagi=ndi niɣůɣ̌um, doyim=um lapdi niɣux̌t=at, dūs=ga šič kamdi vo waxt nist. //
\glb Āmad Zoir uz mumkin az di aždā-sol-agi=ndi niɣůɣ̌-um doyim=um lap-di niɣux̌-t=at dūs=ga šič kam-di vo waxt nist //
\glc Ahmad Zohir PRN.1SG maybe EL D2.M.SG.O eighteen-year-ABSTR=LOC listen-PRS.1SG previously=1SG much-COMP listen-PST=COORD2 a\_little=ADD1 now a\_little-COMP again time be.NEG //
\glft ‘Ахмада Зохира я слушаю, наверное, с восемнадцати лет, раньше больше слушала, а сейчас уже меньше, нет времени.’ //
\endgl \xe

\pex<ex43>
\begingl
\gla Az mi ǰoyi mardum=and, az mi ǰoyi mardum=and… //
\glb az mi ǰoy-i mardum=and az mi ǰoy-i mardum=and //
\glc EL D1.M.SG.O place-ADJ people=LOC EL D1.M.SG.O place-ADJ people=LOC //
\glft ‘Из местных, из местных…’ //
\endgl \xe

\pex<ex44>
\begingl
\gla Qīn lůvdow=atā… Mumkin Liduš murd xuš. //
\glb qīn lův-d-ow=atā mumkin Liduš mu-rd xuš //
\glc hard say-INF-PURP=COORD3 maybe Lidush PRN.1SG.O-DAT happy //
\glft ‘Сложно сказать, но… Наверное, мне нравится Лидуш.’ //
\endgl \xe

\pex<ex45>
\begingl
\gla Vud когда\_то lap=aθ xuš=atā, šič mis niɣůɣ̌um, yakbori. //
\glb vu-d когда\_то lap=aθ xuš=atā šič mis niɣůɣ̌-um yakbori //
\glc be.M.SG-PST some\_time\_ago much=INT happy=COORD3 now ADD2 listen-PRS.1SG once //
\glft ‘Очень нравился когда-то, но сейчас тоже иногда слушаю.’ //
\endgl \xe

\pex<ex46>
\begingl
\gla Nay, Saši Zaifi=yum nažīwǰ. //
\glb nay Saši Zaifi=yum na-žīwǰ //
\glc no Sashi Zaifi=1SG NEG-love.PF //
\glft ‘Нет, не люблю Саши Заифи.’ //
\endgl \xe

\pex<ex47>
\begingl
\gla Saši Zaifi xoyix̌ kix̌t Liduš=ard… taqlīd čīdow. //
\glb Saši Zaifi xoyix̌ kix̌-t Liduš=ard taqlīd čī-d-ow //
\glc Sashi Zaifi wish do-PRS.3SG Lidush=DAT imitation do-INF-PURP //
\glft ‘Саши Заифи хочет… подражать Лидушу.’ //
\endgl \xe

\pex<ex48>
\begingl
\gla Ammo wind důnd xax̌… bašānd yu nasůd. //
\glb ammo wi-nd důnd xax̌ bašānd yu na-sů-d //
\glc but D3.M.SG.O-LOC this\_much very good D3.M.SG NEG-become-PRS.3SG //
\glft ‘Но у него это так… он не [так] хорош [в этом].’ //
\endgl \xe

\pex<ex49>
\begingl
\gla Bašānd navārδed taqlīd wird čīdow. //
\glb bašānd na-vārδe-d taqlīd wi-rd čī-d-ow //
\glc good NEG-be\_able-PRS.3SG imitation D3.M.SG.O-DAT do-INF-PURP //
\glft ‘Не очень хорошо умеет подражать ему.’ //
\endgl \xe

\pex<ex50>
\begingl
\gla Mu fikri=qati, taqlīd boyad mākix̌t=at, boyad ar čīz wind ca yast, ik=wi nix̌ůn δīd. //
\glb mu fikri=qati taqlīd boyad mā-kix̌t=at boyad ar čīz wi-nd ca yast ik=wi nix̌ůn δī-d //
\glc PRN.1SG.O thought=COM taqlīd must NEG.IRR-be=COORD2 must every thing D3.M.SG.O-LOC SUBD1 there\_is EMPH=D3.M.SG.O symbol give-PRS.3SG //
\glft ‘По-моему, он должен не подражать [Лидушу], а показывать, что есть у него самого.’ //
\endgl \xe

\pex<ex51>
\begingl
\gla Wi xuɣ̌nůni ziv… bašānd=o gandā, lůvdow navārδīm. //
\glb wi xuɣ̌nůn-i ziv bašānd=o gandā lův-d-ow na-vārδī-m //
\glc D3.M.SG.O Shughnan-ADJ language good=OR bad say-INF-PURP NEG-be\_able-PRS.1SG //
\glft ‘Его шугнанский язык… Хороший или плохой — не могу сказать.’ //
\endgl \xe

\pex<ex52>
\begingl
\gla Ammo wi sozen māno, důnd xax̌ bašānd nist. //
\glb ammo wi soz-en māno důnd xax̌ bašānd nist //
\glc but D3.M.SG.O song-PL meaning this\_much very good be.NEG //
\glft ‘Но значение его песен не очень хорошее.’ //
\endgl \xe

These two methods can also be called from a `cx.Sentence`:

In [53]:
print(sentence.to_print())
print(sentence.to_latex())

Tu=t as dev sozindāyen=and sar lap či žīwǰ?
‘Кого из музыкантов ты любишь больше всего?’
\pex<ex18>
\begingl
\gla Tu=t as dev sozindāyen=and sar lap či žīwǰ? //
\glb tu=t as dev sozindā-yen=and sar lap či žīwǰ //
\glc PRN.2SG=2SG EL D2.PL.O musician-PL=LOC most much who.O love.PF //
\glft ‘Кого из музыкантов ты любишь больше всего?’ //
\endgl \xe

## Some other tools

There are a few other useful tools for corpus work. For instance, you can get a `collections.Counter` object with all morph-gloss pairs and their frequencies in the corpus:

In [54]:
corpus.morph_vocab()

Counter({('-d', 'PST'): 2701,
         ('-t', 'PST'): 1502,
         ('wi', 'D3.M.SG.O'): 1351,
         ('xu', 'COORD1'): 1305,
         ('=i', '3SG'): 1270,
         ('=en', '3PL'): 1203,
         ('yu', 'D3.M.SG'): 923,
         ('=and', 'LOC'): 894,
         ('-d', 'PRS.3SG'): 880,
         ('=at', 'COORD2'): 832,
         ('xu', 'REFL'): 718,
         ('-t', 'PRS.3SG'): 665,
         ('bād', 'then'): 659,
         ('tar', 'EQ'): 656,
         ('mu', 'PRN.1SG.O'): 644,
         ('di', 'D2.M.SG.O'): 636,
         ('ik=', 'EMPH'): 630,
         ('-en', 'PL'): 592,
         ('wam', 'D3.F.SG.O'): 581,
         ('lů', 'say'): 534,
         ('=um', '1SG'): 528,
         ('tu', 'PRN.2SG'): 493,
         ('=ti', 'SUP'): 483,
         ('čū', 'do'): 468,
         ('as', 'EL'): 461,
         ('-ǰ', 'PF'): 445,
         ('ca', 'SUBD1'): 439,
         ('yi', 'one'): 438,
         ('=rd', 'DAT'): 434,
         ('=ard', 'DAT'): 425,
         ('=ta', 'FUT'): 424,
         ('yā', 'D3.F.SG'): 422,
         ('māš', 'PRN.1PL'): 397,
         ('čīz', 'thing'): 368,
         ('at', 'COORD2'): 348,
         ('-en', 'PRS.3PL'): 325,
         ('ar', 'DOWN'): 318,
         ('pi', 'UP'): 313,
         ('yid', 'D2.SG'): 312,
         ('aro', 'ADR'): 307,
         ('na', 'NEG'): 302,
         ('lův', 'say'): 297,
         ('=yi', '3SG'): 296,
         ('idi', 'COMPL'): 294,
         ('-i', 'EZ'): 288,
         ('vu', 'be.M.SG'): 285,
         ('wuz', 'PRN.1SG'): 274,
         ('wev', 'D3.PL.O'): 273,
         ('ya', 'come'): 267,
         ('kin', 'do'): 266,
         ('mis', 'ADD2'): 262,
         ('na-', 'NEG'): 247,
         ('kix̌', 'do'): 237,
         ('-ǰ', 'PF.M.SG'): 224,
         ('su', 'go.M.SG'): 223,
         ('am', 'D3.LOC'): 221,
         ('vo', 'again'): 221,
         ('-d', 'INF'): 220,
         ('-ow', 'PURP'): 220,
         ('potx̌o', 'king'): 218,
         ('δo', 'give'): 218,
         ('=nd', 'LOC'): 215,
         ('=ām', '1PL'): 212,
         ('mi', 'D1.M.SG.O'): 208,
         ('yi', 'INDEF'): 208,
         ('atā', 'COORD3'): 195,
         ('=aθ', 'ADV'): 193,
         ('wāδ', 'D3.PL'): 192,
         ('ga', 'ADD1'): 184,
         ('az', 'EL'): 181,
         ('yam', 'D1.SG'): 178,
         ('dam', 'D2.F.SG.O'): 178,
         ('disga', 'such'): 178,
         ('-č', 'PF'): 175,
         ('=atā', 'COORD3'): 174,
         ('uz', 'PRN.1SG'): 165,
         ('ǰoy', 'place'): 164,
         ('=yen', '3PL'): 161,
         ('sů', 'become'): 159,
         ('xez', 'APUD'): 157,
         ('nist', 'be.NEG'): 156,
         ('id', 'D2.SG'): 153,
         ('tar-', 'EQ'): 152,
         ('qati', 'COM'): 151,
         ('nān', 'mother'): 150,
         ('-ām', 'PRS.1PL'): 148,
         ('=ga', 'ADD1'): 147,
         ('puc', 'son'): 142,
         ('=aθ', 'INT'): 137,
         ('-ak', 'DIM'): 137,
         ('vi', 'be'): 133,
         ('lāk', 'let'): 133,
         ('-c', 'PF.F/PL'): 133,
         ('-i', 'PRS.2SG'): 131,
         ('ar', 'every'): 131,
         ('sa', 'go.F/PL'): 130,
         ('lap', 'much'): 128,
         ('va', 'be.F/PL'): 128,
         ('-um', 'PRS.1SG'): 124,
         ('důnd', 'this_much'): 123,
         ('čūɣ̌', 'do'): 119,
         ('ba', 'ALL'): 117,
         ('daδ', 'then'): 117,
         ('-m', 'PRS.1SG'): 117,
         ('čīd', 'house'): 114,
         ('fukaθ', 'all'): 112,
         ('=xu', 'COORD1'): 112,
         ('dis', 'such'): 111,
         ('odam', 'person'): 111,
         ('=yat', 'COORD2'): 111,
         ('šič', 'now'): 110,
         ('mardum', 'people'): 110,
         ('sol', 'year'): 110,
         ('zox̌', 'take'): 109,
         ('-yen', 'PL'): 109,
         ('meθ', 'day'): 108,
         ('fuk', 'all'): 107,
         ('vuδ', 'be'): 107,
         ('ed', 'D2.LOC'): 106,
         ('az-', 'EL'): 105,
         ('ɣal', 'still'): 104,
         ('waxt', 'time'): 103,
         ('wīn', 'see'): 103,
         ('su', 'become.M.SG'): 101,
         ('yīw', 'one'): 98,
         ('ůd', 'D1.LOC'): 98,
         ('yast', 'there_is'): 96,
         ('=et', '2PL'): 95,
         ('-t', 'INF'): 91,
         ('čorik', 'man'): 91,
         ('fām', 'understand'): 89,
         ('tama', 'PRN.2PL'): 88,
         ('nay', 'no'): 88,
         ('čāy', 'who'): 86,
         ('=qati', 'COM'): 86,
         ('dev', 'D2.PL.O'): 85,
         ('δu', 'two'): 85,
         ('dāk', 'give'): 85,
         ('=o', 'Q'): 85,
         ('gāp', 'word'): 83,
         ('x̌ac', 'water'): 83,
         ('yoδ', 'memory'): 83,
         ('-et', 'PRS.2PL'): 82,
         ('virod', 'brother'): 82,
         ('dāδ', 'D2.PL'): 81,
         ('toy', 'leave.F/PL'): 80,
         ('-ik', 'DIM'): 79,
         ('kor', 'work'): 78,
         ('a', 'VOC'): 78,
         ('cůnd', 'how_much'): 77,
         ('=yand', 'LOC'): 76,
         ('vū', 'bring'): 76,
         ('naqli', 'story'): 76,
         ('pad-', 'UP'): 76,
         ('tāt', 'father'): 76,
         ('wef', 'D3.PL.O'): 76,
         ('yam', 'D3.LOC'): 76,
         ('ɣiδā', 'boy'): 76,
         ('ar-', 'DOWN'): 74,
         ('ɣ̌in', 'wife'): 74,
         ('=t', '2SG'): 73,
         ('δī', 'give'): 73,
         ('Yeso', 'Jesus'): 73,
         ('bašānd', 'good'): 71,
         ('bob', 'grandfather'): 71,
         ('nêδ', 'seat'): 69,
         ('čī', 'do'): 68,
         ('daraw', 'INC'): 68,
         ('aray', 'three'): 68,
         ('sa', 'become.F/PL'): 67,
         ('nům', 'name'): 67,
         ('bačā', 'child'): 67,
         ('tām', 'then'): 67,
         ('čū', 'do.PST'): 67,
         ('-in', 'PTCP1'): 66,
         ('ida', 'D2.PTCL'): 66,
         ('yo', 'OR'): 65,
         ('di', 'COMP'): 65,
         ('ɣulā', 'big'): 64,
         ('ku', 'PTCL'): 64,
         ('čis', 'look'): 64,
         ('=m', '1SG'): 64,
         ('mam', 'D1.F.SG.O'): 64,
         ('i', 'INDEF'): 64,
         ('-i', 'ABSTR'): 63,
         ('qišloq', 'village'): 63,
         ('čūx̌', 'look'): 63,
         ('tūy', 'leave.M.SG'): 62,
         ('=at', '2SG'): 62,
         ('ču', 'do.PST'): 61,
         ('bād', 'after'): 60,
         ('kāl', 'head'): 60,
         ('yak', 'one'): 60,
         ('sabad', 'basket'): 60,
         ('zêz', 'take'): 59,
         ('tīz', 'leave'): 59,
         ('xuš', 'happy'): 59,
         ('nāla', 'QUOT'): 59,
         ('sů', 'go'): 58,
         ('kampīr', 'old_woman'): 58,
         ('-yi', 'EZ'): 57,
         ('yik=', 'EMPH'): 57,
         ('δust', 'hand'): 56,
         ('=u', 'COORD4'): 56,
         ('=yum', '1SG'): 55,
         ('de', 'enter'): 55,
         ('rizīn', 'daughter'): 55,
         ('wazīr', 'vizier'): 55,
         ('rost', 'right'): 55,
         ('idê', 'COMPL'): 55,
         ('vār', 'be_able'): 54,
         ('mā-', 'NEG.IRR'): 54,
         ('piro', 'front'): 54,
         ('pis', 'GOAL'): 53,
         ('ǰām', 'gathered'): 53,
         ('yůd', 'D1.LOC'): 52,
         ('aga', 'if'): 52,
         ('s', 'go'): 52,
         ('sar', 'most'): 52,
         ('weδ', 'lay'): 51,
         ('yi-', 'INDEF'): 51,
         ('to', 'LIM1'): 51,
         ('půnd', 'road'): 51,
         ('i-', 'INDEF'): 51,
         ('wā', 'D3.PL'): 51,
         ('deδ', 'enter'): 50,
         ('zindagi', 'life'): 50,
         ('-yen', 'PRS.3PL'): 50,
         ('yo', 'oh'): 50,
         ('ǰůn', 'soul'): 49,
         ('pari', 'peri'): 49,
         ('čidům', 'which'): 48,
         ('ši', 'now'): 48,
         ('xêr', 'alright'): 48,
         ('buc', 'child.M'): 47,
         ('vorǰ', 'horse'): 47,
         ('nok', 'pear'): 47,
         ('dod', 'father'): 46,
         ('anǰūv', 'keep'): 45,
         ('yad', 'come'): 45,
         ('=ndi', 'LOC'): 45,
         ('ǰo', 'place'): 44,
         ('lāv', 'some'): 44,
         ('re', 'stay'): 44,
         ('x̌êy', 'read'): 44,
         ('kud', 'dog'): 43,
         ('xubaθ', 'SELF'): 43,
         ('yo', 'carry'): 42,
         ('qīw', 'call'): 42,
         ('x̌ār', 'city'): 42,
         ('suδ', 'become'): 42,
         ('ɣāc', 'girl'): 42,
         ('tayor', 'finished'): 41,
         ('poδ', 'foot'): 41,
         ('pex̌c', 'ask'): 41,
         ('mā', 'NEG.IRR'): 40,
         ('diga', 'other'): 40,
         ('=yaθ', 'ADV'): 40,
         ('be-', 'CARIT'): 40,
         ('boyad', 'must'): 39,
         ('ɣ̌inik', 'woman'): 39,
         ('dām', 'back'): 39,
         ('cem', 'eye'): 38,
         ('=yām', '1PL'): 38,
         ('mūm', 'grandmother'): 38,
         ('maktab', 'school'): 38,
         ('am', 'D1.SG'): 38,
         ('didi', 'COMPL'): 38,
         ('Atā', 'COORD3'): 38,
         ('δo', 'fall_down'): 37,
         ('def', 'D2.PL.O'): 37,
         ('carāng', 'how'): 37,
         ('di', 'SUBD2'): 37,
         ('xuδoy', 'God'): 36,
         ('=ǰāt', 'CAUSE'): 36,
         ('ůn', 'yes'): 36,
         ('xū', 'eat'): 35,
         ('azrat', 'majesty'): 35,
         ('-i', 'ADJ'): 35,
         ('ziryot', 'child'): 35,
         ('ačaθ', 'absolutely'): 35,
         ('du', 'two'): 35,
         ('yakdigar', 'RECP'): 35,
         ('=am', '1PL'): 34,
         ('tīr', 'SUP'): 34,
         ('xalq', 'people'): 34,
         ('s', 'become'): 34,
         ('=ec', 'LIM2'): 34,
         ('gāx̌', 'turn'): 34,
         ('um', 'ORD'): 34,
         ('xudowand', 'God'): 34,
         ('čos', 'look'): 34,
         ('či', 'who.O'): 33,
         ('si', 'become'): 33,
         ('pêx̌c', 'ask'): 33,
         ('andūy', 'rise.M.SG'): 33,
         ('ti', 'leave'): 33,
         ('-ā', 'HB'): 33,
         ('x̌itur', 'camel'): 33,
         ('=yard', 'DAT'): 33,
         ('qāp', 'palm'): 33,
         ('yida', 'D2.PTCL'): 33,
         ('ču', 'do'): 33,
         ('=yaθ', 'INT'): 32,
         ('firīp', 'reach'): 32,
         ('kā', 'where'): 32,
         ('sā', 'go'): 32,
         ('x̌āb', 'night'): 32,
         ('dar', 'in'): 32,
         ('ām', 'COORD5'): 32,
         ('xušrūy', 'beautiful'): 32,
         ('ɣaδā', 'boy'): 32,
         ('δe', 'fall_down'): 31,
         ('xīr', 'eat'): 31,
         ('u', 'D3.M.SG'): 31,
         ('=at', 'TIME2'): 31,
         ('=tīr', 'SUP'): 31,
         ('payɣumbar', 'prophet'): 31,
         ('daraxt', 'tree'): 31,
         ('žindūrv', 'werewolf'): 31,
         ('pīc', 'face'): 30,
         ('nūs', 'sit.M.SG'): 30,
         ('taraf', 'side'): 30,
         ('yaθ', 'come'): 30,
         ('tī', 'leave'): 30,
         ('δ', 'give'): 30,
         ('naɣ̌ǰīs', 'pass'): 30,
         ('divi', 'door'): 30,
         ('e', 'VOC'): 30,
         ('dā', 'give'): 29,
         ('sāraki', 'morning'): 29,
         ('sāw', 'go'): 29,
         ('yum', 'D3.LOC'): 29,
         ('darūn', 'inside'): 29,
         ('rāng', 'SIMIL'): 29,
         ('x̌oǰ', 'fear'): 29,
         ('xub', 'good'): 29,
         ('xurok', 'food'): 29,
         ('δoδ', 'give'): 28,
         ('wox̌', 'fall'): 28,
         ('māδ', 'D1.PL'): 28,
         ('nos', 'sit.F/PL'): 28,
         ('de', 'D2.PL.O'): 28,
         ('rūz', 'day'): 28,
         ('nur', 'today'): 28,
         ('mev', 'D1.PL.O'): 28,
         ('va', 'PTCL'): 28,
         ('Wi', 'D3.M.SG.O'): 28,
         ('kayůn', 'pear'): 28,
         ('zindā', 'alive'): 27,
         ('ɣ̌ew', 'hunting'): 27,
         ('andoy', 'rise.F/PL'): 27,
         ('=ird', 'DAT'): 27,
         ('bozi', 'game'): 27,
         ('safed', 'white'): 27,
         ('cvet', 'colour'): 27,
         ('znāčit', 'this_means'): 27,
         ('naɣ̌ǰī', 'pass'): 26,
         ('mīz', 'build'): 26,
         ('misol', 'example'): 26,
         ('či', 'PROSP'): 26,
         ('ɣêv', 'mouth'): 26,
         ('zibo', 'back'): 26,
         ('x̌ov', 'sleep'): 26,
         ('nax̌tūy', 'go_out.M.SG'): 26,
         ('zī', 'kill'): 26,
         ('-at', 'PQP'): 26,
         ('dawrā', 'times'): 25,
         ('wūrǰ', 'wolf'): 25,
         ('bač', 'child'): 25,
         ('čor', 'four'): 25,
         ('х̌āb', 'night'): 25,
         ('δo', 'hit'): 25,
         ('ammo', 'but'): 25,
         ('ǰāt', 'CAUSE'): 24,
         ('δum', 'tail'): 24,
         ('ɣulům', 'servant'): 24,
         ('niviš', 'write'): 24,
         ('rost', 'truth'): 24,
         ('=va', 'PROL'): 24,
         ('daryo', 'river'): 24,
         ('yet', 'open'): 24,
         ('ara', 'three'): 24,
         ('sawor', 'astride'): 24,
         ('bar', 'ALL'): 24,
         ('soz', 'song'): 24,
         ('gūx̌t', 'meat'): 24,
         ('čiz', 'thing'): 24,
         ('nax̌toy', 'go_out.F/PL'): 24,
         ('dūs', 'a_little'): 24,
         ('ǰawob', 'answer'): 24,
         ('x̌ūvd', 'milk'): 24,
         ('bidāl', 'swap'): 24,
         ('cif', 'steal'): 23,
         ('namoz', 'namaz'): 23,
         ('čand', 'few'): 23,
         ('faqat', 'only'): 23,
         ('yos', 'carry'): 23,
         ('x̌īǰ', 'bull'): 23,
         ('yoc', 'fire'): 23,
         ('=ra', 'DAT'): 23,
         ('amčun', 'alike'): 23,
         ('moyi', 'fish'): 23,
         ('nāy', 'no'): 23,
         ('yed', 'D2.LOC'): 22,
         ('suδ', 'go'): 22,
         ('δoδ', 'fall_down'): 22,
         ('sof', 'clear'): 22,
         ('um', 'D3.LOC'): 22,
         ('boɣ', 'garden'): 22,
         ('yum', 'ORD'): 22,
         ('xāfc', 'get_down'): 22,
         ('sa', 'go'): 22,
         ('dūkůn', 'shop'): 22,
         ('wix̌tak', 'swaddled_baby'): 22,
         ('markab', 'donkey'): 22,
         ('xāy', 'HEZ'): 22,
         ('nafar', 'person'): 21,
         ('ʒulik', 'small.F'): 21,
         ('awqot', 'food'): 21,
         ('pūrg', 'mouse'): 21,
         ('šīg', 'calf'): 21,
         ('tīr', 'top'): 21,
         ('bīst', 'twenty'): 21,
         ('sār', 'morning'): 21,
         ('xabar', 'acquainted'): 21,
         ('gīr', 'fixed'): 21,
         ('δi', 'fall_down'): 21,
         ('bof', 'can'): 20,
         ('ris', 'stay'): 20,
         ('xax̌', 'strong'): 20,
         ('žīr', 'stone'): 20,
         ('x̌oy', 'read'): 20,
         ('-galā', 'PL'): 20,
         ('awɣůn', 'Afghan'): 20,
         ('fikri', 'thought'): 20,
         ('vegā', 'evening'): 20,
         ('pūx̌ok', 'clothes'): 20,
         ('čor', 'husband'): 20,
         ('sūr', 'wedding'): 20,
         ('abor', 'once'): 20,
         ('kitob', 'book'): 19,
         ('rawůn', 'going'): 19,
         ('rāng', 'colour'): 19,
         ('kū', 'mountain'): 19,
         ('wūvd', 'seven'): 19,
         ('cimūd', 'basket'): 19,
         ('patêw', 'throw'): 19,
         ('cavor', 'four'): 19,
         ('yel', 'letovka'): 19,
         ('rūšt', 'red'): 19,
         ('pīnʒ', 'five'): 19,
         ('divūsk', 'snake'): 19,
         ('Sulaymůn', 'Solomon'): 19,
         ('pas', 'therefore'): 19,
         ('yax', 'sister'): 19,
         ('čid', 'house'): 19,
         ('ačaθ', 'at_all'): 19,
         ('Iso', 'Jesus'): 19,
         ('xūδm', 'sleep'): 18,
         ('mêst', 'month'): 18,
         ('yoδ', 'carry'): 18,
         ('reδ', 'stay'): 18,
         ('ǰůndor', 'mountain_goat'): 18,
         ('salům', 'hello'): 18,
         ('vīr', 'bring'): 18,
         ('carang', 'how'): 18,
         ('garδen', 'overturn'): 18,
         ('wêx̌', 'fall'): 18,
         ('amo', 'but'): 18,
         ('zīn', 'kill'): 18,
         ('Buor', 'Bahor'): 18,
         ('podx̌o', 'king'): 18,
         ('yidê', 'COMPL'): 18,
         ('azor', 'thousand'): 18,
         ('ostā', 'slow'): 18,
         ('bīr', 'bottom'): 17,
         ('darkor', 'necessary'): 17,
         ('qīn', 'hard'): 17,
         ('peδo', 'apparent'): 17,
         ('dast', 'hand'): 17,
         ('va', 'PROL'): 17,
         ('win', 'see'): 17,
         ('δāδ', 'give'): 17,
         ('tez', 'fast'): 17,
         ('naxčīr', 'mountain_goat'): 17,
         ('ti', 'SUP'): 17,
         ('δar', 'far'): 17,
         ('varθ', 'both'): 17,
         ('sifī', 'climb_up'): 17,
         ('=atā', 'TIME2'): 17,
         ('pex̌s', 'ask'): 17,
         ('zīrd', 'yellow'): 17,
         ('sifīn', 'climb_up'): 17,
         ('yordam', 'help'): 16,
         ('qaror', 'calm'): 16,
         ('amro', 'companion'): 16,
         ('nīs', 'sit'): 16,
         ('xoli', 'empty'): 16,
         ('dāx̌t', 'steppe'): 16,
         ('pêx', 'cook'): 16,
         ('kin', 'do.IMP'): 16,
         ('zorδ', 'heart'): 16,
         ('žêx̌', 'run'): 16,
         ('rimo', 'send'): 16,
         ('tīž', 'pull'): 16,
         ('we', 'D3.PL.O'): 16,
         ('=ǰa', 'P.LOC'): 16,
         ('raf', 'touch'): 16,
         ('dawlat', 'state'): 16,
         ('ʒul', 'small.F'): 16,
         ('ayrůn', 'shocked'): 16,
         ('tozā', 'clean'): 16,
         ('nigīnā', 'ring'): 16,
         ('pur', 'full'): 16,
         ('diraxt', 'tree'): 16,
         ('sinf', 'class'): 16,
         ('bāx̌', 'part'): 15,
         ('darā', 'canyon'): 15,
         ('pīδ', 'time'): 15,
         ('tilāp', 'ask_for'): 15,
         ('-in', 'ADJ'): 15,
         ('markāb', 'donkey'): 15,
         ('či', 'CONT1'): 15,
         ('murδā', 'dead'): 15,
         ('ki', 'do'): 15,
         ('vār', 'bring'): 15,
         ('niθ', 'sit'): 15,
         ('-gi', 'ABSTR'): 15,
         ('mumkin', 'maybe'): 15,
         ('taš', 'PROSP'): 15,
         ('xuɣ̌nůn', 'Shughnan'): 15,
         ('-rd', 'DAT'): 15,
         ('bayn', 'center'): 14,
         ('dil', 'heart'): 14,
         ('v', 'bring'): 14,
         ('si', 'go'): 14,
         ('gax̌t', 'coming_back'): 14,
         ('xůnā', 'house'): 14,
         ('dargo', 'yard'): 14,
         ('čīr', 'why'): 14,
         ('ziv', 'tongue'): 14,
         ('sado', 'voice'): 14,
         ('δī', 'fall_down'): 14,
         ('xarč', 'food'): 14,
         ('nazdīk', 'close'): 14,
         ('ǰinow', 'like'): 14,
         ('taxt', 'throne'): 14,
         ('nīw', 'cry'): 14,
         ('=andīr', 'LOC'): 14,
         ('bozor', 'market'): 14,
         ('sůg', 'tale'): 14,
         ('čuɣʒ', 'owl'): 14,
         ('x', 'eat'): 14,
         ('-či', 'ORIG'): 14,
         ('-gůn', 'PL'): 14,
         ('δuyůn', 'two'): 14,
         ('ma', 'NEG.IRR'): 14,
         ('agā', 'awake'): 13,
         ('tāx', 'mountain'): 13,
         ('tam', 'PRN.2PL'): 13,
         ('andīz', 'get_up'): 13,
         ('xāv', 'get_down'): 13,
         ('yāni', 'that_is'): 13,
         ('yor', 'friend'): 13,
         ('anǰīv', 'keep'): 13,
         ('daroz', 'long'): 13,
         ('osmůn', 'heaven'): 13,
         ('sāw', 'become'): 13,
         ('yima', 'D1.PTCL'): 13,
         ('ay', 'away'): 13,
         ('xabar', 'news'): 13,
         ('panǰ', 'five'): 13,
         ('piš', 'cat'): 13,
         ('firāp', 'reach'): 13,
         ('ziwos', 'take_out'): 13,
         ('xoyix̌', 'wish'): 13,
         ('qalā', 'fortress'): 13,
         ('nax̌tī', 'go_out'): 13,
         ('yês', 'carry'): 13,
         ('ox̌no', 'friend'): 13,
         ('bīr', 'SUP'): 13,
         ('naw', 'new'): 13,
         ('sā', 'become'): 13,
         ('x̌ikar', 'search'): 13,
         ('yakbor', 'once'): 13,
         ('ye', 'VOC'): 13,
         ('δê', 'give'): 13,
         ('duzd', 'thief'): 13,
         ('se', 'three'): 13,
         ('Yu', 'D3.M.SG'): 13,
         ('xatto', 'wrong'): 13,
         ('-di', 'COMP'): 13,
         ('Šimůn', 'Simon'): 13,
         ('k', 'do.IMP'): 12,
         ('isob', 'account'): 12,
         ('pūl', 'money'): 12,
         ('vūɣ̌', 'bring'): 12,
         ('sifīδ', 'climb_up'): 12,
         ('nax̌tīz', 'go_out'): 12,
         ('qabūl', 'acceptance'): 12,
         ('mūysafed', 'old_man'): 12,
         ('=andi', 'LOC'): 12,
         ('alqissā', 'thus'): 12,
         ('bīdi', 'better'): 12,
         ('δêr', 'have'): 12,
         ('memůn', 'guest'): 12,
         ('rux', 'dawn'): 12,
         ('šaš', 'six'): 12,
         ('rūzo', 'one_day'): 12,
         ('can', 'gun'): 12,
         ('potx̌oyi', 'kingdom'): 12,
         ('ruxsat', 'release'): 12,
         ('sandūq', 'chest'): 12,
         ('šart', 'condition'): 12,
         ('rimo', 'order'): 12,
         ('Nuqrā', 'Nukra'): 12,
         ('be', 'disappear'): 12,
         ('kux̌', 'cut'): 12,
         ('δew', 'div'): 12,
         ('kolā', 'material'): 12,
         ('yeso', 'Jesus'): 12,
         ('mevā', 'fruit'): 12,
         ('yiθ', 'come'): 11,
         ('x̌u', 'hear'): 11,
         ('zê', 'take'): 11,
         ('dek', 'pot'): 11,
         ('ač', 'at_all'): 11,
         ('zūr', 'strong'): 11,
         ('ve', 'be'): 11,

You can also get a dictionary with all morphs which have more than one gloss in the corpus. Some of them are true homophones, but most of them are probably annotation mistakes:

In [55]:
corpus.homophones()

{'-a': ['DAT', 'PL'],
 '-ak': ['?', 'DIM', 'PTCP2'],
 '-d': ['INF', 'PRS.3SG', 'PST'],
 '-en': ['PL', 'PRS.3PL'],
 '-i': ['ABSTR', 'ADJ', 'EZ', 'PRS.2SG'],
 '-in': ['ADJ', 'PTCP1'],
 '-ǰ': ['PF', 'PF.M.SG', 'PST'],
 '-m': ['ORD', 'PRS.1SG'],
 '-t': ['INF', 'PRS.3SG', 'PST'],
 '-um': ['D3.LOC', 'ORD', 'PRS.1SG'],
 '-yen': ['PL', 'PRS.3PL'],
 '-yi': ['ABSTR', 'ADJ', 'EZ', 'PRS.2SG'],
 '-ā': ['HB', 'PL'],
 '-č': ['PF', 'PF.M.SG'],
 '0': ['IMP', '_'],
 '=at': ['2SG', 'COORD2', 'TIME2'],
 '=ata': ['COORD3', 'FUT', 'TIME2'],
 '=atā': ['COORD3', 'TIME2'],
 '=aθ': ['ADV', 'INT'],
 '=en': ['3PL', 'PL'],
 '=o': ['COORD4', 'DISJ', 'OR', 'Q'],
 '=t': ['2SG', 'COORD2'],
 '=ta': ['COORD3', 'FUT', 'TIME2'],
 '=tā': ['?', 'COORD3', 'FUT', 'TIME2'],
 '=u': ['COORD3', 'COORD4'],
 '=um': ['1SG', 'D3.LOC'],
 '=wu': ['COORD3', 'COORD4'],
 '=yat': ['2SG', 'COORD2', 'TIME2'],
 '=yaθ': ['ADV', 'INT'],
 '=yo': ['OR', 'Q'],
 '=θ': ['ADV', 'INT'],
 'Bād': ['after', 'then'],
 'Dušanbi': ['Dušanbe', 'Dušanbi'],
 'Dušānbi': ['Dushanbe', 'Dušānbi'],
 'Esenin': ['Esenin', 'Yesenin'],
 'Maryam': ['Maria', 'Mary'],
 'Muhammad': ['Mohammed', 'Muhamed'],
 'Xox̌darā': ['Shahdara', 'Shokhdara'],
 'Xuɣ̌nůn': ['Shughnan', 'Shughni'],
 'Yoqūb': ['Jacob', 'James'],
 'a': ['?',
  'AFF',
  'D3.F.SG',
  'HEZ',
  'INTER',
  'VOC',
  '_',
  'a',
  'ah',
  'and',
  'so',
  'yes'],
 'afsūs': ['alas', 'pity'],
 'afsůna': ['tale', 'tale (taj)'],
 'aft': ['seven', 'seven (taj)'],
 'aftod': ['eighty', 'seventy'],
 'aha': ['uh-huh', 'uhuh'],
 'aǰab': ['astonishing', 'surprising'],
 'alalaš': ['mix', 'mixing'],
 'aloyid': ['individual', 'separate'],
 'alqā': ['circle', 'drawing a bow'],
 'am': ['COORD5', 'D1.SG', 'D3', 'D3.LOC', 'DEM1.SG'],
 'amo': ['ADVS', 'but'],
 'amro': ['companion', 'friend'],
 'amsoyā': ['neighbor', 'neighbour'],
 'an': ['?', 'yes'],
 'anafc': ['get.soaked', 'soften', 'steam.out'],
 'andak': ['a little', 'little'],
 'andiʒ': ['rise', 'rise.IMP'],
 'andoy': ['get_up.F/PL', 'rise.F/PL'],
 'ang': ['cry', 'cry.IMP'],
 'angax': ['get.into', 'touch'],
 'angaxc': ['encounter.difficulty', 'hit', 'stammer'],
 'angix': ['get caught', 'get.caught'],
 'aqli': ['consciousness', 'intellect', 'intelligence', 'mind'],
 'aqůni': ['fairly', 'indeed'],
 'ar': ['DOWN', 'every', 'so'],
 'ark': ['ark', 'castle'],
 'arodi_man': ['ADR', 'my_brother', 'my_dear'],
 'arčiz': ['some', 'something'],
 'asbob': ['instrument', 'saddle'],
 'askar': ['soldier', 'warrior'],
 'asos': ['foundation', 'main'],
 'asīd': ['this.year', 'this_year'],
 'at': ['2SG/', '?', 'COORD2', '_'],
 'ata': ['EM', '_'],
 'atman': ['for_sure', 'necessarily'],
 'atā': ['COORD3', 'TIME2'],
 'awal': ['Mavla', 'beginning', 'first'],
 'awalůn': ['first', 'initially'],
 'awli': ['estate', 'yard'],
 'awlod': ['family', 'kin', 'relative'],
 'awlodā': ['family', 'relative'],
 'awqotwori': ['food', 'provisions'],
 'ay': ['_', 'ah', 'away', 'set off'],
 'ayb': ['fault', 'sin'],
 'aywůn': ['animal', 'catter', 'scatter'],
 'ayům': ['celebration', 'holiday'],
 'azob': ['counting', 'suffering', 'torment', 'waste'],
 'ačaθ': ['absolutely', 'at all', 'at all (?)', 'at_all', 'hardly', 'nothing'],
 'ažêr': ['moisten', 'moisten.IMP', 'wet'],
 'aδa': ['ADR', 'boy'],
 'aθêr': ['give_away',
  'pass',
  'pass.IMP',
  'reach.out',
  'stretch',
  'stretch.IMP'],
 'babarakat': ['blessed', 'blessing'],
 'bad': ['bad', 'then'],
 'badaraw': ['away', 'immediately'],
 'badbaxt': ['unhappy', 'unlucky'],
 'balad': ['acquaintance', 'familiar'],
 'band': ['binding', 'bound', 'locked'],
 'barakat': ['blessing', 'well_being'],
 'barakatbāx̌': ['blessing', 'gratitude'],
 'barobar': ['equal', 'half', 'horizontal', 'towards'],
 'baromad': ['expense', 'performance'],
 'barost': ['opposite', 'towards'],
 'bat': ['arms', 'chest'],
 'bazūr': ['forced', 'with.effort'],
 'bačamard': ['young man', 'young_man'],
 'bed': ['disappear', 'missing'],
 'beδ': ['disappear', 'lost', 'vanish'],
 'biland': ['high', 'tall'],
 'biyābůn': ['desert', 'steppe'],
 'bod': ['let_it_be', 'wind'],
 'boǰ': ['cooked.peas', 'tribute'],
 'boǰak': ['nut', 'walnut'],
 'bor': ['at_least', 'just', 'time'],
 'boy': ['rich', 'rich man', 'rich_man'],
 'boz': ['falcon', 'sell', 'send'],
 'bozi': ['game', 'play'],
 'boδ': ['drop', 'sore'],
 'bun': ['bottom', 'tree'],
 'but': ['boot', 'idol'],
 'buzurg': ['big', 'great'],
 'bā': ['kiss', 'then', 'with'],
 'bād': ['after', 'then'],
 'bānd': ['blocked', 'consist', 'rope'],
 'bānā': ['cause', 'pretext'],
 'bār': ['chest', 'part of the pallet near the hearth', 'push'],
 'bās': ['coping', 'enough'],
 'bāx̌': ['part', 'portion', 'share'],
 'bīr': ['SUP', 'bed', 'bottom'],
 'bīreǰ': ['bed', 'bedding'],
 'bīst': ['20', 'bosom', 'twenty'],
 'ca': ['SUBD1', 'what'],
 'cemak': ['cemak', 'eyeglasses'],
 'cirow': ['candle', 'lamp'],
 'cow': ['harvest', 'mowing'],
 'cuɣ': ['REDUP', 'lacerated', 'ragged'],
 'da': ['D2.PL', 'give', 'yes'],
 'dam': ['D2.F.SG.O', 'a little', 'moment'],
 'dar': ['INC', '_', 'about', 'far', 'gift (rus)', 'in', 'swelling'],
 'daraw': ['INC', 'immediately'],
 'daryov': ['capture', 'catch'],
 'darā': ['abyss', 'canyon', 'gorge'],
 'dastorxůn': ['dastarkhan', 'table cloth'],
 'dastūr': ['like', 'manner'],
 'daw': ['reach', 'run', 'running'],
 'dawrā': ['time', 'times'],
 'dax̌t': ['Dasht', 'steppe'],
 'daδ': ['D2.PL', 'then'],
 'de': ['D2.PL.O', 'enter'],
 'dek': ['cattle', 'pot'],
 'di': ['?',
  '? D2.M.SG.O / when / hit',
  'COMP',
  'D2.M.SG.O',
  'SUBD2',
  'beat',
  'hit',
  'kill',
  'like',
  'so'],
 'dimoɣ': ['mood', 'nose'],
 'dives': ['seem', 'show'],
 'diwen': ['chase', 'drive'],
 'diyor': ['valley', 'village'],
 'dičor': ['meeting', 'towards'],
 'doyim': ['always', 'previously'],
 'doδ': ['complaint', 'measure', 'size'],
 'dučor': ['encountered', 'towards'],
 'dušanbi': ['Dushanbe', 'dushanbe'],
 'dê': ['?', 'chase', 'enter', 'hit'],
 'dā': ['D2.PL', 'give', 'ten'],
 'dālšê': ['since then', 'then'],
 'dām': ['D2.F.SG.O', 'back', 'breath', 'breathing'],
 'dārδ': ['disease', 'hurt', 'illness', 'pain'],
 'dāwat': ['call', 'draft', 'invitation'],
 'dāwo': ['anger', 'scolding'],
 'dāδ': ['D2.PL', 'then'],
 'dī': ['at.time', 'flog', 'hit'],
 'dīn': ['belief', 'religion'],
 'důmod': ['son.in.law', 'son_in_law'],
 'důmān': ['hem', 'lap'],
 'e': ['ADDR', 'ADR', 'D2.LOC', 'VOC', 'hey'],
 'en': ['3SG', '?', '? PL', '? PL/3PL/PRS.3PL', '_', '∅'],
 'ey': ['ADR', 'hey'],
 'far': ['REDUP', 'lesson'],
 'faryod': ['call', 'cry'],
 'firêp': ['bring', 'deliver'],
 'foks': ['Foks', 'Fox'],
 'fā': ['know', 'understand'],
 'fānd': ['deceit', 'deception', 'lie'],
 'gadoyi': ['beggary', 'begging', 'go begging'],
 'garδā': ['bread', 'flatbread'],
 'gināgor': ['guilty', 'sinful'],
 'gird': ['around', 'round'],
 'go': ['HEZ', 'PTCL', 'like', 'more', 'sometimes'],
 'guftā': ['said', 'word'],
 'guǰ': ['goat', 'goatling'],
 'gul': ['flower', 'pattern'],
 'gumůn': ['apparently', 'seemingly', 'suspicion'],
 'guzar': ['living', 'passage'],
 'guzaštā': ['dead', 'past'],
 'gā': ['ADD1', 'sometimes'],
 'gārm': ['hot', 'warm'],
 'i': ['?',
  '??',
  '???',
  'D1.LOC',
  'D1.SG',
  'DISTR',
  'INDEF',
  '_',
  'one',
  'so'],
 'id': ['COMPL', 'D2.SG'],
 'ida': ['D2.PTCL', 'well'],
 'indīz': ['detach', 'rise'],
 'indūy': ['advance', 'grow', 'increase', 'rise', 'start'],
 'ingaxc': ['get.stuck', 'touch'],
 'ingix': ['get.caught', 'get.into'],
 'istifodā': ['usage', 'use'],
 'ǰam': ['_', 'collect'],
 'ǰinow': ['as_if', 'like', 'similar'],
 'ǰuft': ['even', 'pair'],
 'ǰuk': ['crush', 'hit'],
 'ǰul': ['piece of cloth', 'scrap'],
 'ǰux̌': ['boil', 'boiling'],
 'ǰāl': ['anger', 'quick'],
 'ǰūr': ['established', 'good'],
 'k': ['_', 'do', 'do.IMP', 'make'],
 'kal': ['bald.F', 'head'],
 'kalapoy': ['DOWN', 'downward'],
 'kaltak': ['?', 'stick'],
 'kaltā': ['big', 'great', 'lover'],
 'kalxoz': ['collective farm', 'kolkhoz'],
 'kanīʒ': ['bondmaid', 'maid'],
 'karočê': ['in short', 'shortly'],
 'kasal': ['ill', 'sick'],
 'kasali': ['disease', 'illness', 'болезнь'],
 'kasp': ['occupation', 'profession'],
 'katanak': ['D3.PL', 'great'],
 'katā': ['big', 'many'],
 'kax̌t': ['crops', 'grain', 'grain.bread'],
 'kax̌tīn': ['boat', 'ship'],
 'kaɣ̌': ['cut', 'slaughter'],
 'ki': ['?', 'EM', 'do', 'do.IMP', 'that'],
 'kicor': ['fireplace', 'furnace', 'hearth', 'kitsor'],
 'kili': ['branch', 'trunk'],
 'kin': ['do', 'do.IMP'],
 'kočor': ['creature', 'thing'],
 'kundā': ['log', 'stump'],
 'kīl': ['head', 'hornless'],
 'lax': ['crape', 'turn'],
 'loq': ['cloth', 'clothes', 'clothing', 'rags'],
 'lu': ['say', 'say.IMP'],
 'luk': ['filled', 'whole'],
 'luq': ['cloth', 'clothes', 'rags'],
 'līng': ['shank', 'shin'],
 'lůd': ['say', 'speak'],
 'lův': ['say', 'say.IMP'],
 'm': ['ORD', '_', 'take', '∅'],
 'm-m': ['HEZ', 'uh-uh'],
 'mamlakat': ['country', 'land'],
 'man': ['ADR', 'PRN.1SG'],
 'maqsad': ['desire', 'goal'],
 'mase': ['Messiah', 'messiah'],
 'mast': ['daring', 'drunk', 'enjoying'],
 'mawlono': ['Mavlono', 'the Lord'],
 'maɣ̌': ['goat', 'sheep'],
 'maɣ̌ʒůnǰ': ['hungry', 'hungryr'],
 'mi': ['CONT2', 'D1.M.SG.O'],
 'miɣūnd': ['similar', 'such'],
 'miɣ̌īǰ': ['ram', 'sheep'],
 'mmm': ['mmm', 'uhuh'],
 'mo': ['PRN.1SG.O', '_', 'die', 'die.F/PL', 'weaken'],
 'moben': ['among', 'between'],
 'mol': ['animal',
  'cattle',
  'cattle (small)',
  'goods',
  'herd',
  'livestock',
  'lubricate',
  'process',
  'property',
  'rub',
  'small_cattle',
  'smear',
  'smudge',
  'trample',
  'wealth'],
 'moz': ['?', 'build', 'build.IMP'],
 'mu': ['PRN.1SG.O', 'die'],
 'mulk': ['country', 'land'],
 'mum': ['grandma', 'grandmother'],
 'murδā': ['calf', 'corpse', 'dead'],
 'muslāt': ['advice', 'conversation'],
 'musulmůn': ['moslem', 'muslim'],
 'muxtasar': ['briefly', 'short'],
 'mênat': ['labor', 'work'],
 'mā': ['D1.PL', 'NEG.IRR'],
 'māk': ['do.PROH', 'mak', 'neck'],
 'mālā': ['chamber', 'home', 'house', 'room'],
 'māni': ['meaning', 'sense'],
 'mātob': ['Moon', 'moon'],
 'mīr': ['die', 'mir (feodal ruler)', 'proud', 'weaken'],
 'mū': ['PRN.1SG.O', 'die', 'die.M.SG', 'weaken'],
 'mūm': ['grandfather', 'grandmother', 'granny'],
 'můndā': ['exhausted', 'tired'],
 'na': ['NEG', '_', 'not'],
 'narvůnd': ['ladder', 'step.ladder'],
 'naw': ['first.harvest', 'just', 'new', 'now', 'only'],
 'nawruz': ['Navruz', 'navruz'],
 'naxo': ['really?', 'so'],
 'nazar': ['looking', 'vision'],
 'naɣ̌ǰī': ['pass', 'pass.M.SG'],
 'naɣ̌ǰīδ': ['_', 'pass'],
 'naɣ̌ʒim': ['bring', 'carry out', 'lead', 'spend', 'spend time'],
 'nex': ['nech', 'nekh'],
 'nigā': ['care', 'looking'],
 'nis': ['_', 'sit', 'stay'],
 'nix̌ůn': ['mark', 'sign'],
 'niɣux̌': ['hear', 'listen'],
 'niɣůɣ̌': ['hear', 'listen'],
 'niθ': ['sit', 'sit.IMP', 'wait'],
 'nok': ['pear', 'pear (taj.)'],
 'nolān': ['groaning', 'wail'],
 'nos': ['sit.F/PL', 'watch'],
 'now': ['narrow', 'nine'],
 'noz': ['caprice', 'coquerty', 'show_off', 'whim'],
 'noziyůn': ['beloved', 'darling', 'loved'],
 'noɣ̌': ['spin', 'turn'],
 'nusk': ['mouth', 'muzzle'],
 'nêx': ['bunks', 'nech', 'plank bed'],
 'nêɣ̌': ['roam', 'walk'],
 'nā': ['NEG.Q', 'QUOT', 'whether'],
 'nārm': ['gentle', 'soft'],
 'nāš': ['full', 'many', 'much'],
 'nū': ['HEZ', 'nine', 'well'],
 'nūrůni': ['enlightened', 'saint'],
 'nūs': ['sit.M.SG', 'wait'],
 'nūsad': ['nine hundred', 'nine.hundred'],
 'o': ['?', 'ADD', 'HEZ', 'INTERFIX', 'OR', 'Oh', 'Q', 'VOC', '_'],
 'ob': ['_', 'water'],
 'obrūy': ['prestige', 'reputation'],
 'ol': ['state', 'status'],
 'olam': ['universe', 'world'],
 'osepi': ['fear', 'horror'],
 'osil': ['finally', 'harvest'],
 'ot': ['?', 'visible'],
 'oxir': ['actually', 'end', 'finally'],
 'oxirůn': ['final', 'finally', 'last'],
 'oxůn': ['master', 'teacher'],
 'oy': ['_', 'oh'],
 'oyistā': ['quietly', 'slowly'],
 'ozmūd': ['attempt', 'temptation'],
 'ozodā': ['charming', 'free'],
 'oš': ['osh', 'pottage'],
 'pac': ['son', 'son.PL'],
 'paloys': ['care', 'work'],
 'palê': ['_', 'side'],
 'palāng': ['leopard', 'panther'],
 'parǰīv': ['respect', 'take.over'],
 'parā': ['edge', 'village_outskirts'],
 'patêw': ['take_away', 'throw'],
 'pex̌': ['ask', 'before', 'forward'],
 'pečka': ['stove', 'stove (rus)'],
 'pigo': ['already', 'front'],
 'piniʒ': ['dress.IMP', 'put on', 'put_on'],
 'pinīz': ['put.on', 'put_on'],
 'piro': ['before', 'front'],
 'pis': ['GOAL', 'boil', 'cook'],
 'piyoz': ['onion', 'onions'],
 'piδi': ['burn', 'light'],
 'piδin': ['burn', 'light'],
 'piδiδ': ['burn', 'set fire'],
 'po': ['foot', 'leg', 'on'],
 'podx̌o': ['king', 'padishah'],
 'pol': ['floor', 'flour'],
 'por': ['across', 'crossing', 'tear'],
 'poy': ['REDUP', 'following', 'graze', 'herd'],
 'poθ': ['arrow', 'bullet', 'foot', 'shooting'],
 'prorok': ['prophet', 'prophet (ru)'],
 'prosta': ['just', 'simply'],
 'prosto': ['just', 'simply'],
 'pul': ['glimmer', 'money'],
 'pux̌tā': ['highlands', 'valley'],
 'pêx': ['boot', 'cook', 'pekh'],
 'pêɣům': ['message', 'news'],
 'pāspati': ['raise', 'slope'],
 'pāst': ['low', 'short'],
 'qadam': ['Qadam', 'step'],
 'qadri': ['authority', 'value', 'worth'],
 'qadīm': ['ancient', 'old'],
 'qalā': ['fortress', 'tower'],
 'qap': ['close', 'closed'],
 'qaror': ['calm', 'choice', 'decision', 'silent'],
 'qarori': ['peace', 'silence'],
 'qawm': ['relative', 'relatives'],
 'qiloɣ': ['mock', 'mocking', 'ridicule'],
 'qoydā': ['custom', 'rule'],
 'qunǰɣā': ['behind', 'seat'],
 'qurbůnī': ['sacrafice', 'sacrifice'],
 'qut': ['REDUP', 'cackle'],
 'qāp': ['hand', 'palm'],
 'qīw': ['call', 'call.IMP'],
 'qīč': ['belly', 'stomach', 'womb'],
 'rafīq': ['comrade', 'partner'],
 'raqam': ['number', 'variety'],
 'rax̌āb': ['all night', 'allnight'],
 'raz': ['_', 'crumble'],
 'rezā': ['crumbled', 'shred'],
 'ribū': ['put', 'put.M.SG'],
 'ricos': ['escape', 'run.F/PL'],
 'ricūs': ['flee', 'run'],
 'rimi': ['order', 'send'],
 'rimo': ['ask', 'order', 'send'],
 'rimoδ': ['delegate', 'order', 'send'],
 'risq': ['destiny', 'prey'],
 'rost': ['right', 'straight', 'truth'],
 'rozi': ['agree', 'agreed', 'willing'],
 'rozī': ['content', 'willing'],
 'rux': ['dawn', 'light', 'sunrise'],
 'rêʒ': ['den', 'nest'],
 'rām': ['compassion', 'complain', 'mercy', 'pity'],
 'rāng': ['SIMIL', 'color', 'colour'],
 'rū': ['face', 'spirit'],
 'rūsi': ['Russian', 'Russian (language)', 'russian'],
 'rūy': ['face', 'side'],
 'růʒ': ['roof_window', 'vent'],
 's': ['become', 'go'],
 'sa': ['become',
  'become.F/PL',
  'become.IMP',
  'go',
  'go.F/PL',
  'go.IMP',
  'three'],
 'saldāt': ['soldier', 'soldier (ru)'],
 'salůmat': ['health', 'healthy'],
 'samalyot': ['airplane', 'plane'],
 'samar': ['allowance', 'fruit'],
 'sar': ['beginning', 'most'],
 'sari': ['every', 'morning'],
 'savʒā': ['grass', 'greens'],
 'sawor': ['astride', 'riding'],
 'sayli': ['stroll', 'walk'],
 'sel': ['landslide', 'mudflow'],
 'sen': ['lift', 'pick up', 'pick_up', 'raise'],
 'ser': ['full', 'satisfied_with_food', 'well_fed'],
 'si': ['become', 'go', 'three'],
 'sifc': ['bead', 'bean'],
 'sifī': ['climb_up', 'climb_up.M.SG'],
 'sit': ['earth', 'go', 'ground', 'soil'],
 'sitůr': ['beeves', 'cattle (big)'],
 'soyib': ['host', 'master', 'owner'],
 'soz': ['fine', 'good', 'song'],
 'su': ['become', 'become.M.SG', 'go.M.SG'],
 'sust': ['feeble', 'powerless', 'weak'],
 'suδ': ['become', 'go'],
 'sêd': ['flat rock', 'stone.slab'],
 'sêr': ['seed', 'stalk'],
 'sêx': ['spit', 'stick'],
 'sā': ['_', 'become', 'go'],
 'sāf': ['formation', 'line'],
 'sār': ['head', 'morning', 'next day'],
 'sāw': ['become', 'go', 'go.IMP', 'three'],
 'sūrat': ['appearance', 'face'],
 'sů': ['become', 'go'],
 'sům': ['rouble', 'ruble', 'somoni'],
 't': ['?', 'EM', '∅'],
 'tagov': ['below', 'down', 'downward'],
 'tagovīn': ['down', 'low'],
 'tam': ['PRN.2PL', 'then'],
 'tamům': ['end', 'whole'],
 'taqlīd': ['imitation', 'taqlīd'],
 'taqsīm': ['distribution', 'division'],
 'tarz': ['kind', 'style'],
 'ti': ['?', 'SUP', '_', 'leave', 'leave.IMP', 'way'],
 'tikā': ['apart', 'teared'],
 'tilo': ['gold', 'stone'],
 'tir': ['SUP', 'raven'],
 'tis': ['poured', 'scattered'],
 'to': ['LIM1', 'SUBD3'],
 'tobistůn': ['summer', 'summertime'],
 'toq': ['alone', 'odd', 'window'],
 'toy': ['leave.F/PL', 'walk'],
 'tozagi': ['cleanliness', 'purity'],
 'tu': ['?', 'PRN.2SG'],
 'tuq': ['REDUP', 'rat', 'rattat', 'tat'],
 'tux̌p': ['dried buttermilk', 'sour'],
 'têp': ['start', 'turn', 'twist'],
 'têr': ['black', 'dark'],
 'tāk': ['snare', 'so'],
 'tāl': ['heap', 'pile'],
 'tām': ['PRN.2PL', 'then'],
 'tānā': ['blame', 'reproach'],
 'tārīx': ['history', 'story'],
 'tāx': ['boulder', 'mountain', 'stone'],
 'tāž': ['draw', 'pull'],
 'tīr': ['SUP', 'bullet', 'top'],
 'tītak': ['headscarf', 'kerchief'],
 'u': ['COORD4', 'D3.M.S.O', 'D3.M.SG', 'D3.M.SG.O', 'VOC', 'in order to'],
 'ukūmat': ['authority', 'government', 'state'],
 'um': ['? PRS.1SG', 'D3.LOC', 'ORD', 'PRN.1SG'],
 'umuman': ['generally', 'in.general'],
 'urmat': ['help', 'honour', 'respect'],
 'uxmānd': ['educated', 'taught', 'teacher', 'trained'],
 'ux̌': ['mind', 'oh'],
 'uže': ['already', 'already (rus)'],
 'v': ['PTCL', 'be', 'bring', 'give'],
 'va': ['COORD4',
  'PROL',
  'PTCL',
  'and (taj)',
  'be.F/PL',
  'bring',
  'bring.IMP',
  'give.IMP'],
 'vadxoz': ['Vadxoz', 'Vadxoz.'],
 'velik': ['bicycle', 'bike'],
 'viraɣ̌': ['break', 'break.IMP'],
 'virux̌': ['break', 'chop', 'crush'],
 'viručāt': ['help', 'rescue'],
 'vobšem': ['HEZ', 'anyway'],
 'vu': ['be', 'be.M.SG'],
 'vār': ['be', 'be_able', 'bring', 'can'],
 'vīr': ['all', 'bring', 'give', 'take'],
 'vīs': ['tie', 'tie_up'],
 'watan': ['homeland', 'motherland'],
 'wazmin': ['hard', 'heavy'],
 'wiloɣ': ['horse', 'pack animal'],
 'win': ['meet.IMP', 'resent', 'see'],
 'wirūv': ['stand', 'stand.M.SG'],
 'wix̌tak': ['swaddle', 'swaddled_baby'],
 'wizêw': ['pick.up', 'quench'],
 'wižīv': ['come back', 'return'],
 'wiδič': ['bird', 'sparrow'],
 'woqiyā': ['case', 'incident'],
 'wox̌': ['fall', 'grass'],
 'wux̌': ['attention', 'mind'],
 'wêδ': ['channel', 'lay', 'river', 'stream'],
 'wādā': ['promise', 'time'],
 'wāɣ': ['cry', 'weep'],
 'wāɣast': ['crying', 'scream', 'weeping'],
 'wīz': ['burden', 'cargo', 'fit', 'weight'],
 'wūvd': ['five', 'seven'],
 'xa': ['and', 'eat'],
 'xabar': ['acquainted', 'news'],
 'xabarkax̌': ['informer', 'messenger'],
 'xalos': ['end', 'free'],
 'xalīfā': ['caliph', 'khalifa'],
 'xamben': ['bring down', 'close', 'get.down', 'let down', 'move_down'],
 'xar': ['all', 'eat'],
 'xarīd': ['buy', 'purchase'],
 'xax̌': ['hard', 'strong', 'very'],
 'xe': ['read', 'thresh'],
 'xex̌': ['relative', 'relatives'],
 'xex̌i': ['match_making', 'matchmaking'],
 'xidorǰ': ['mill', 'thrashing'],
 'xist': ['moist', 'wet'],
 'xo': ['EMPH', 'spend'],
 'xob': ['good', 'night', 'sleep', 'well'],
 'xok': ['ground', 'soil'],
 'xolak': ['maternal.uncle', 'uncle'],
 'xor': ['degraded', 'garbage', 'harm'],
 'xu': ['COORD1', 'REFL'],
 'xudo': ['god', 'the God'],
 'xudowand': ['God', 'god'],
 'xulosa': ['briefly', 'result'],
 'xuši': ['happy', 'joy'],
 'xuɣ̌nůn': ['Shughnan', 'Shughni'],
 'xêr': ['HEZ', 'alright', 'nephew', 'well'],
 'xêx̌': ['branch', 'twig'],
 'xāt': ['lettering', 'line', 'note'],
 'xāy': ['HEZ', 'well'],
 'xāɣ̌': ['beautiful', 'pretty', 'sweet'],
 'xīr': ['eat', 'sun'],
 'x̌appast': ['prompt', 'quickly'],
 'x̌ar': ['rosehip', 'rozehip'],
 'x̌armandā': ['ashamed', 'disgraced'],
 'x̌arvo': ['bouillon', 'soup'],
 'x̌ey': ['learn', 'read', 'study'],
 'x̌ikū': ['look for', 'search'],
 'x̌itur': ['PRN.1SG.O', 'camel'],
 'x̌ičīf': ['crack', 'marmot'],
 'x̌ofc': ['sleep', 'sleep.IMP'],
 'x̌ogird': ['disciple', 'student'],
 'x̌ov': ['lie', 'sleep'],
 'x̌oy': ['_', 'heap', 'learn', 'pile of stones', 'read', 'read.IMP'],
 'x̌u': ['hear', 'listen'],
 'x̌êy': ['learn', 'read', 'thresh'],
 'x̌ā': ['khan', 'shah'],
 'x̌ūr': ['snitching', 'snitchning'],
 'x̌ům': ['dusk', 'twilight'],
 'x̌ůnči': ['fiance', 'groom'],
 'ya': ['D3.F.SG', '_', 'come', 'come.IMP', 'go', 'lets'],
 'yam': ['D1.SG', 'D3.LOC'],
 'yast': ['maybe', 'there_is'],
 'yat': ['EM', 'come'],
 'yawūd': ['Jew', 'Jewish'],
 'yaθ': ['ADV', 'come'],
 'ye': ['D2.LOC', 'VOC'],

If you don’t know the exact name of the text you’re looking for, you can search across the corpus by text names:

In [56]:
corpus.text(query="peri")

[Text("Peri (AND)"),
 Text("Interview experiment (SN72 & NR75)"),
 Text("Peri (OQD)"),
 Text("Peri (SDA)"),
 Text("Peri in a summer camp (SDA)")]